### ISSUE TITLE
Explicitly set constructor binding should stop convention from running

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#13891] opened 2018-11-05 19:04 UTC
```C#
    public class Project
    {
        public Project(string name, int anotherProp)
        {
            Name = name;
            AnotherProp = anotherProp;
        }

        public Project(string name, string lastname)
        {
            Name = name;
            Lastname = lastname;
        }

        public Project(string name, string lastname, int anotherProp)
            : this(name, lastname)
        {
            AnotherProp = anotherProp;
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Lastname { get; set; }
        public int AnotherProp { get; set;  }
    }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
            modelBuilder.Entity<Project>(e =>
            {
                e.Property(p => p.Name).UsePropertyAccessMode(PropertyAccessMode.FieldDuringConstruction);
                e.Property(p => p.AnotherProp).UsePropertyAccessMode(PropertyAccessMode.FieldDuringConstruction);
                e.Property(p => p.Lastname).UsePropertyAccessMode(PropertyAccessMode.FieldDuringConstruction);
            });
        }
```
```
Unhandled Exception: System.InvalidOperationException: Two constructors were found with the same number of parameters that could both be used by Entity Framework. The constructor to use must be configured explicitly. The two constructors are 'Project(string, int)' and 'Project(string, string)'.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConstructorBindingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeleted()
   at EFSampleApp.Program.Main(String[] args) in D:\code\EFSampleApp\EFSampleApp\Program.cs:line 15
```
EF Core version: 2.2.0-rtm-35637

**Comment by ajcvickers** [comment] 2018-11-05 20:47
This is currently by-design per: #10852, but also see #10865.

The constructor binding can be set explicitly using internal code.

> ### Warning: internal code should be used with caution, since it may be changed or removed in a breaking way in any new release.

```C#
modelBuilder.Entity<Project>(e =>
{
    var nameProperty = e.Property(p => p.Name).Metadata;
    var anotherProperty = e.Property(p => p.AnotherProp).Metadata;
    var lastNameProperty = e.Property(p => p.Lastname).Metadata;

    e.Metadata[CoreAnnotationNames.ConstructorBinding]
        = new DirectConstructorBinding(
            typeof(Project).GetConstructor(new [] { typeof(string), typeof(string), typeof(int) }),
            new []
            {
                new PropertyParameterBinding(nameProperty),
                new PropertyParameterBinding(lastNameProperty),
                new PropertyParameterBinding(anotherProperty),
            });
});
```

However, I found while working on this that the convention still runs and throws even though its result would not be used--this is a bug. I was able to workaround this by adding a private parameterless constrctor to the entity type:

```C#
public class Project
{
    private Project()
    {
    }

    ...
}
```
This allows the convention to succeed, with the result being that the explicitly configured constructor is used.

**Comment by ahedreville** [comment] 2019-03-19 11:07
Hi All
There is any update about when this bug will be fixed?
Thanks a lot in advance.

**Comment by ajcvickers** [comment] 2019-03-20 21:04
@ahedreville Currently planned for the 3.0 release; that's why the issue is in the "3.0" milestone.

**Closed** 2019-07-07 16:06 UTC
Labels: closed-fixed, customer-reported, type-bug
