### ISSUE TITLE
Using SeedData with enums generates non-compiling code

### ISSUE THREAD

**Issue by edwiles** [aspnet/EntityFrameworkCore#11114] opened 2018-03-01 12:07 UTC
When using EntityTypeBuilder.SeedData with an entity that has an enum property, updating the database reports the error "Build failed". This is because EF Core migrations generates code that fails to resolve the enum.

### Steps to reproduce
1. Create any enumeration:
```
    public enum TestEnum
    {
        EnumValue1,
        EnumValue2
    }
```

2. Use in an entity:
```
   public int Id { get; set; }
   public TestEnum MyTestEnum { get; set; }
   public string Name { get; set; }
```

3. In OnModelCreating, seed the table as follows:
```
            modelBuilder.Entity<Project>().SeedData(
                new { Id = 1, MyTestEnum = TestEnum.EnumValue1, Name = "Test Project" });
```

4. Drop and recreate the database via migrations:
```
dotnet ef database drop -f
dotnet ef migrations remove
dotnet ef migrations add InitialCreate
dotnet ef database update
```

This reports "Build failed". The offending code is in Migrations/20180301115050_InitialCreate.cs:

```
            migrationBuilder.InsertData(
                table: "Project",
                columns: new[] { "Id", "MyTestEnum", "Name" },
                values: new object[] { 1, TestEnum.EnumValue1, "Test Project" });
```

Above, "TestEnum" cannot be resolved.

In case of relevance, the entity classes are in a separate project named Domain - the EF code is in a project named Database. But judging from the usings in 20180301115050_InitialCreate.cs, I don't think it would find TestEnum even if everything was in the same project.

In step 3 above I tried replacing TestEnum.EnumValue1 with 0, but then updating the database rightly complained of a type mismatch: "The seed entity for entity type 'Project' cannot be added because the value provided for the property 'TestEnum' is not of the type 'Domain.Model.TestEnum'".

Fully qualifying TestEnum did not help either, as the generated code removed the qualification (not unreasonably).

In case of use, here is an extract from my csproj:
```
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.1.0-preview1-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.1.0-preview1-final" />
  </ItemGroup>
```

### Further technical details
EF Core version: 2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Professional
IDE: Visual Studio 2017 15.5.4

**Comment by ajcvickers** [comment] 2018-03-02 20:51
This looks like the same root cause as #11131, but in the case of database enums (e.g. Postgres) we need to be able to include the namespace for the enum in the snapshot. so assigning to @bricelam for that.

**Closed** 2018-04-12 16:44 UTC
Labels: closed-fixed, type-bug
