### ISSUE TITLE
Foreign key data attribute broken with upgrade from 2.0 to 2.1

### ISSUE THREAD

**Issue by vishnu4** [aspnet/EntityFrameworkCore#12237] opened 2018-06-05 02:16 UTC
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:The relationship from 'Parent.ReferenceTypeObject' to 'ReferenceType.ParentGU' with foreign key properties {'ReferenceTypeGUID' : Nullable<int>} cannot target the primary key {'ReferenceTypeGUID' : Guid} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship
Stack trace:
``` 

### Steps to reproduce

See example project here : https://github.com/vishnu4/EFCore21Test 
Created in response to this issue here : https://stackoverflow.com/questions/50685187/upgrade-to-2-1-breaks-existing-net-core-ef-logic 

simply load the github project above in visual studio, and run add-migration.  you will see the error i talk about.  This project works fine with EF core 2.0, the upgrade to 2.1 broke this functionality

### Further technical details
EF Core version:2.1
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 
IDE:  Visual Studio 2017 15.7

**Comment by ajcvickers** [comment] 2018-06-07 17:16
@vishnu4 Based on this model from your post:
```C#
public class Parent
{
     [Key()]
     public Guid ParentGUID {get;set;}
     public string SomeValue {get;set;}
     [ForeignKey("ReferenceTypeGUID")]
     public ReferenceType ReferenceTypeObject {get;set;}
}
public class ReferenceType
{
     [Key()]
     public Guid ReferenceTypeGUID{get;set;}
     public string SomeOtherValue {get;set;}
     public virtual ICollection<Parent> ParentGU { get; set; }
}
```
Can you describe what the expected database tables and FK constraints would be?

**Comment by vishnu4** [comment] 2018-06-07 18:54
Just the below basic structure.  The code i include in the git project works fine if you downgrade to version 2.0

Parent Table 
- ParentGUID  Primary key
- ReferenceTypeGUID as FK to ReferenceType Table

ReferenceType Table 
- ReferenceTypeGUID Primary key

**Comment by ajcvickers** [comment] 2018-06-07 20:11
@vishnu4 So you are intentionally using the attribute to have EF not only use this FK property, but also to create it in shadow state? (The reason I am clarifying is that this is pretty uncommon--it's much more common to use a configuration like this in error, with the intention to make the ReferenceTypeGUID property on ReferenceType by the FK, even though that doesn't make sense.)

**Comment by vishnu4** [comment] 2018-06-07 22:26
yeah, my goal was to put as much descriptor data in the business object instead of the dbcontext.  Felt cleaner to me that way, and since it worked in 2.0 i went with it.  but if that's anti-pattern i honestly have no problem going another way, just thought i should give a heads up that something that used to work doesn't anymore, and wanted to make sure it wasn't by accident.

**Comment by ajcvickers** [comment] 2018-06-08 18:20
@smitpatel to investigate if there are more ways of hitting this.

**Comment by smitpatel** [comment] 2018-06-08 20:41
```C#
// Model
    public class Game
    {
        public int GameId { get; set; }

        public GameDetails Details { get; set; }
    }

    public class GameDetails
    {
        public int GameDetailsId { get; set; }
    }

// OnModelCreating
            modelBuilder.Query<Game>().HasOne(x => x.Details).WithOne();
            Console.WriteLine(modelBuilder.Model.ToDebugString());
```
Prints model
```
Model:
  QueryType: Game
    Properties:
      GameId (int) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
      DetailsTempId (no field, Nullable<int>) Shadow FK Index 1 1 1 0 -1
    Navigations:
      Details (<Details>k__BackingField, GameDetails) ToPrincipal GameDetails 0 -1 2 -1 -1
    Keys:
      GameId PK
    Foreign keys:
      Game {'DetailsTempId'} -> GameDetails {'TempId'} Unique ToPrincipal: Details
    Annotations:
      RelationshipDiscoveryConvention:NavigationCandidates: System.Collections.Immutable.ImmutableSortedDictionary`2[System.Reflection.PropertyInfo,System.Type]
  EntityType: GameDetails
    Properties:
      GameDetailsId (int) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
      TempId (no field, int) Shadow Required AlternateKey AfterSave:Throw 1 1 1 0 -1
    Keys:
      GameDetailsId PK
      TempId
    Annotations:
      RelationshipDiscoveryConvention:NavigationCandidates: System.Collections.Immutable.ImmutableSortedDictionary`2[System.Reflection.PropertyInfo,System.Type]
Annotations:
  ProductVersion: 2.1.0-rtm-30799
  Relational:MaxIdentifierLength: 128
  SqlServer:ValueGenerationStrategy: IdentityColumn
```

TempId is not replaced with actual PK which is discovered by convention,

**Comment by smitpatel** [comment] 2018-06-08 20:43
cc: @AndriySvyryd

**Comment by ajcvickers** [comment] 2018-06-12 23:00
Notes from triage: original posted issue may be fixed in dev/nightly builds. Second issue posted by Smit looks different. @AndriySvyryd to investigate both.  We will not patch at this time, but if the root cause ends up being more common and/or more people hit this issue, then we will consider for patch.

**Comment by smitpatel** [comment] 2018-10-09 18:59
First issue reported here is already fixed in current release.
Generated model
```
Model: 
  EntityType: DependentShadowFk
    Properties: 
      DependentShadowFkId (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
        Annotations: 
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTypeMapping
      PrincipalShadowFkId (no field, Nullable<Guid>) Shadow FK Index 1 1 1 0 1
        Annotations: 
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTypeMapping
    Navigations: 
      Principal (<Principal>k__BackingField, PrincipalShadowFk) ToPrincipal PrincipalShadowFk Inverse: Dependends 0 -1 2 -1 -1
    Keys: 
      DependentShadowFkId PK
    Foreign keys: 
      DependentShadowFk {'PrincipalShadowFkId'} -> PrincipalShadowFk {'PrincipalShadowFkId'} ToDependent: Dependends ToPrincipal: Principal
    Annotations: 
      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.Internal.DirectConstructorBinding
  EntityType: PrincipalShadowFk
    Properties: 
      PrincipalShadowFkId (Guid) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
        Annotations: 
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.InMemory.Storage.Internal.InMemoryTypeMapping
    Navigations: 
      Dependends (<Dependends>k__BackingField, List<DependentShadowFk>) Collection ToDependent DependentShadowFk Inverse: Principal 0 -1 1 -1 -1
    Keys: 
      PrincipalShadowFkId PK
    Annotations: 
      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.Internal.DirectConstructorBinding
Annotations: 
  ProductVersion: 2.2.0-preview3-t000
```

**Comment by smitpatel** [comment] 2018-10-09 19:07
Second issue which I reported here is duplicate of #13382 

Generated model
```
Model:
  EntityType: Blog
    Properties:
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
        Annotations:
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.Storage.IntTypeMapping
          SqlServer:ValueGenerationStrategy: IdentityColumn
    Keys:
      Id PK
    Annotations:
      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.Internal.DirectConstructorBinding
      Relational:TableName: Blogs
  QueryType: Game
    Properties:
      GameId (int) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
        Annotations:
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.Storage.IntTypeMapping
          SqlServer:ValueGenerationStrategy: IdentityColumn
      DetailsGameDetailsId (no field, Nullable<int>) Shadow FK Index 1 1 1 0 1
        Annotations:
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.Storage.IntTypeMapping
    Navigations:
      Details (<Details>k__BackingField, GameDetails) ToPrincipal GameDetails 0 -1 2 -1 -1
    Keys:
      GameId PK
    Foreign keys:
      Game {'DetailsGameDetailsId'} -> GameDetails {'GameDetailsId'} Unique ToPrincipal: Details
    Annotations:
      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.Internal.DirectConstructorBinding
  EntityType: GameDetails
    Properties:
      GameDetailsId (int) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
        Annotations:
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.Storage.IntTypeMapping
          SqlServer:ValueGenerationStrategy: IdentityColumn
    Keys:
      GameDetailsId PK
    Annotations:
      ConstructorBinding: Microsoft.EntityFrameworkCore.Metadata.Internal.DirectConstructorBinding
Annotations:
  ProductVersion: 2.2.0-preview3-35433
  Relational:MaxIdentifierLength: 128
  SqlServer:ValueGenerationStrategy: IdentityColumn
```

**Comment by smitpatel** [comment] 2018-10-09 19:08
Assigning milestone of 2.2.0-preview1 as that is where first issue was resolved.

**Closed by smitpatel** 2018-10-09 19:08 UTC
Labels: customer-reported, regression, type-bug
