### ISSUE TITLE
Sqlite Vacuum command broken

### ISSUE THREAD

**Issue by phleb3** [aspnet/EntityFrameworkCore#19313] opened 2019-12-13 19:37 UTC
I have a vacuum command that is about 4 years old, suddenly give a sqlite error #1 

### To Reproduce

Just the sqlite error #1 on a readnext

### Additional context

Microsoft.Data.Sqlite version:
Target framework: uwp
Operating system:windows 10

**Comment by ajcvickers** [comment] 2019-12-16 18:41
@phleb3 We believe this is fixed in the 3.1 release. Can you give that a try?

**Comment by ajcvickers** [comment] 2019-12-23 17:21
**EF Team Triage:** Closing this issue as the requested additional details have not been provided and we have been unable to reproduce it.

*BTW this is a canned response and may have info or details that do not directly apply to this particular issue. While we'd like to spend the time to uniquely address every incoming issue, we get a lot traffic on the EF projects and that is not practical. To ensure we maximize the time we have to work on fixing bugs, implementing new features, etc. we use canned responses for common triage decisions.*

**Closed by ajcvickers** 2019-12-23 17:21 UTC
Labels: area-adonet-sqlite, customer-reported, type-bug

**Comment by bricelam** [comment] 2020-01-02 23:55
Fixed by #13830 in 3.0.0
