### ISSUE TITLE
Investigate deadlock in AsyncSimpleQueryTestBase tests using pooling

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#12138] opened 2018-05-24 18:04 UTC
The tests `Throws_on_concurrent_query_list` and `Throws_on_concurrent_query_first` cause deadlocks in other tests.

**Comment by ajcvickers** [comment] 2019-05-11 21:08
Closing as this is no longer relevant with the latest query changes.

**Comment by smitpatel** [comment] 2019-08-07 17:38
There is still deadlock in ConcurrencyDetectorTestBase

**Comment by smitpatel** [comment] 2019-08-07 18:48
Found the cause: re-entrant exception makes ConcurrencyDetector unusable and in pooling scenario, it would cause deadlock.

**Closed** 2019-08-08 17:16 UTC
Labels: area-test, closed-fixed, punted-for-2.2, punted-for-3.0, type-bug
