### ISSUE TITLE
Average returns "Unable to cast object of type 'System.Int32' to type 'System.Double'" - Regression in EF Core 2.2.1. 

### ISSUE THREAD

**Issue by JonPSmith** [aspnet/EntityFrameworkCore#14604] opened 2019-02-04 19:10 UTC
### UPDATED with more information

I updated some of my code to EF Core 2.2.1 and use of the `Average` method now throws an error with SQL Server (but not with Sqlite). **I have narrowed it down to a change in the SQL that EF Core creates. - see end of this issue.**

*NOTE see #9516 for the original discussion on the use of Average in LINQ. This worked in EF Core 2.0 and 2.1.*

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: 
System.InvalidCastException : Unable to cast object of type 'System.Int32' to type 'System.Double'.
Stack trace:
at System.Data.SqlClient.SqlBuffer.get_Double()
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Test.UnitTests.DataLayer.TestBookAverage.TestAverageReviewSqlServerOk() in C:\Users\Jon\Source\Repos\EfCoreSqlAndCosmos\Test\UnitTests\DataLayer\TestBookAverage.cs:line 68
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

The book class 
```c#
public class Book
{
    public const int PromotionalTextLength = 200;
    private HashSet<BookAuthor> _authorsLink;
    private HashSet<Review> _reviews;

    public int BookId { get; private set; }
    [Required(AllowEmptyStrings = false)]
    public string Title { get; private set; }
    public string Description { get; private set; }
    public DateTime PublishedOn { get; set; }
    public string Publisher { get; private set; }
    public decimal OrgPrice { get; private set; }
    public decimal ActualPrice { get; private set; }

    [MaxLength(PromotionalTextLength)]
    public string PromotionalText { get; private set; }

    public string ImageUrl { get; private set; }

    public IEnumerable<Review> Reviews => _reviews?.ToList();
    public IEnumerable<BookAuthor> AuthorsLink => _authorsLink?.ToList();
    //... other methods and ctors left out 
}
```
The unit test that fails. It fails on the query

```c#
[Fact]
public void TestAverageReviewSqlServerOk()
{
    //SETUP
    var options = this.CreateUniqueMethodOptionsWithLogging<SqlDbContext>(
        log => _output.WriteLine(log.Message));
    using (var context = new SqlDbContext(options))
    {
        context.Database.EnsureCreated();
        context.WipeAllDataFromDatabase();

        var book = DddEfTestData.CreateDummyBookOneAuthor();
        book.AddReview(5, "test", "test");
        context.Add(book);
        context.SaveChanges();

        //ATTEMPT
        var aveReviews = context.Books
            .Select(p => p.Reviews.Select(y => (double?)y.NumStars).Average())
            .ToList();

        //VERIFY
        //never get to here
    }
}

```

## Differences in SQL produced

For the LINQ command `p => p.Reviews.Select(y => (double?)y.NumStars).Average()` then I get different SQL output.

For EF Core 2.0 (and I assume 2.1) the sql looks like this
```sql
SELECT (
    SELECT AVG(CAST([y].[NumStars] AS float))
    FROM [Review] AS [y]
    WHERE [b].[BookId] = [y].[BookId]
)
FROM [Books] AS [p]
```
For EF Core 2.2 the sql looks like this
```sql
SELECT (
    SELECT AVG([y].[NumStars])
    FROM [Review] AS [y]
    WHERE [p].[BookId] = [y].[BookId]
)
FROM [Books] AS [p]
```
NOTE: If I do the same thing with Sqlite in-memory database the EF Core 2.2 outputs the same SQL but does not fail. 

### Further technical details
EF Core version: Microsoft.EntityFrameworkCore 2.1.1 (SqlServer and Sqlite)
Database Provider: fails of  Microsoft.EntityFrameworkCore.SqlServer, doesn't fail on Sqlite
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.6

**Comment by smitpatel** [comment] 2019-02-05 19:50
Caused by https://github.com/aspnet/EntityFrameworkCore/pull/12142
Should be resolved by #13908

**Comment by ajcvickers** [comment] 2019-02-11 21:48
@JonPSmith I was attempting to reproduce this to look into workarounds, but I don't see any errors. Could you post a runnable project/solution or complete code listing that demonstrates the error.

**Comment by JonPSmith** [comment] 2019-02-13 10:38
Hi @ajcvickers,

This problem occurred in a new project I built to look at using CosmosDb with EF Core 2.2. you can find the whole repo (which is public) at https://github.com/JonPSmith/EfCoreSqlAndCosmos. 

If you run the Test [TestBookAverage](https://github.com/JonPSmith/EfCoreSqlAndCosmos/blob/master/Test/UnitTests/DataLayer/TestBookAverage.cs) you will see it fails with `Unable to cast object of type 'System.Int32' to type 'System.Double'`. That test also outputs the EF Core logging (at information level) so you can see the SQL it creates, which is different to the original 2.0/2.1 version.

The main code failed too, so I have currently taken out the average calculation out of the [MapBookToDto](https://github.com/JonPSmith/EfCoreSqlAndCosmos/blob/master/ServiceLayer/BooksSql/QueryObjects/BookListDtoSelect.cs) method.

**Comment by ajcvickers** [comment] 2019-02-19 19:32
Minimal repro:
```C#
public class Review
{
    public int ReviewId { get; set; }
    public int NumStars { get; set; }

    public Guid BookId { get; set; }
}

public class Book
{
    public Guid BookId { get; private set; }
    public ICollection<Review> Reviews { get; set; }
}

public class BloggingContext : DbContext
{
    private static readonly LoggerFactory Logger
        = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder
            .UseLoggerFactory(Logger)
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
    }

    public DbSet<Book> Books { get; set; }
}

public class Program
{
    public static async Task Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            var book = new Book
            {
                Reviews = new List<Review>
                {
                    new Review {NumStars = 5}
                }
            };

            context.Add(book);
            context.SaveChanges();

            context.Books.Select(p => p.Reviews.Select(y => (double?)y.NumStars).Average()).ToList();
        }
    }
}
```
Query logs:
```
dbug: Microsoft.EntityFrameworkCore.Query[10101]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Compiling query model:
      'from Book p in DbSet<Book>
      select
          (from Review y in [p].Reviews
          select (Nullable<double>)(double)[y].NumStars).Average()'
dbug: Microsoft.EntityFrameworkCore.Query[10104]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      Optimized query model:
      'from Book p in DbSet<Book>
      select
          (from Review y in DbSet<Review>
          where  ?= Property([p], "BookId") == Property([y], "BookId") =?
          select (Nullable<double>)(double)[y].NumStars).Average()'
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      => Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor
      (QueryContext queryContext) => IEnumerable<Nullable<double>> _InterceptExceptions(
      |__ source: IEnumerable<Nullable<double>> _ShapedQuery(
      |   |__ queryContext: queryContext,
      |   |__ shaperCommandContext: SelectExpression:
      |   |       SELECT (
      |   |           SELECT AVG([y].[NumStars])
      |   |           FROM [Review] AS [y]
      |   |           WHERE [p].[BookId] = [y].[BookId]
      |   |       )
      |   |       FROM [Books] AS [p],
      |   |__ shaper: (QueryContext queryContext | ValueBuffer p) => (Nullable<double>)Nullable<double> TryReadValue(p, 0, null) ?? default(Nullable<double>)),
      |__ contextType: BloggingContext,
      |__ logger: DiagnosticsLogger<Query>,
      |__ queryContext: Unhandled parameter: queryContext)

dbug: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT (
          SELECT AVG([y].[NumStars])
          FROM [Review] AS [y]
          WHERE [p].[BookId] = [y].[BookId]
      )
      FROM [Books] AS [p]
```

**Closed** 2019-03-12 17:14 UTC
Labels: customer-reported, regression, servicing-consider, type-bug

**Comment by LiangZugeng** [comment] 2019-03-21 13:54
I encountered a similar issue, can you please let me know if the bug fix covers the scenario?

Code Repo:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace efcore22bug
{

    public class Book
    {
        public Guid BookId { get; private set; }
        public float Weight { get; set; }
    }

    public class BloggingContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder
                .UseMySql(@"Server=localhost;database=EFCore22Test;uid=root;password=Password");
        }

        public DbSet<Book> Books { get; set; }
    }

    public class Program
    {
        public static async Task Main()
        {
            using (var context = new BloggingContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var book = new Book
                {
                    Weight = 1.15f
                };

                context.Add(book);
                context.SaveChanges();

                var weight = await context.Books.SumAsync(b => b.Weight);
                Console.WriteLine(weight);
            }
        }
    }
}
```

.csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="2.2.0" />
  </ItemGroup>

</Project>
```

Error text:
```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'System.Single'.
   at MySql.Data.MySqlClient.MySqlDataReader.GetFloat(Int32 ordinal) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlDataReader.cs:line 224
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.GetResult[TResult](IAsyncEnumerable`1 valueBuffers, Boolean throwOnNullResult, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at efcore22bug.Program.Main() in /Users/james/Projects/temp/efcore22bug/Program.cs:line 45
   at efcore22bug.Program.<Main>()
```

I'm using .NET Core SDK 2.2.3.

**Comment by ajcvickers** [comment] 2019-03-21 19:24
@LiangZugeng I don't think so. The code you posted works for me using 2.2 and the SQL Server provider, so it looks like it may be an issue with the MySQL provider.
