### ISSUE TITLE
Allow to use navigations in model level entity filters

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFrameworkCore#8881] opened 2017-06-16 22:13 UTC

**Comment by pauldalyii** [comment] 2017-09-01 18:05
I just want to plug the referenced issue (#9539) that @smitpatel closed as duplicate of this.

It expands on the filter-by-tenant use case that is outlined in the [ef core / what's new](https://docs.microsoft.com/en-us/ef/core/what-is-new/#model-level-query-filters) documentation.

Any chance this might make it for 2.1?

**Comment by ajcvickers** [comment] 2017-09-05 17:06
@pauldalyii Thanks for the feedback and the detailed example in #9539--this gives us good information on one concrete way people would use this. Unfortunately, I don't think this will fit in the 2.1 time frame.

**Comment by pauldalyii** [comment] 2017-10-03 16:13
@ajcvickers, thanks for letting me know.  With some guidance, I'd be happy to try to implement this/get a rough PoC working.  It seems like It'd be a cool feature.

**Comment by ajcvickers** [comment] 2017-10-03 17:43
@anpete Can you give @pauldalyii some guidance here?

**Comment by smitpatel** [comment] 2017-10-03 22:05
One of the biggest blocker for this is nav expansion and filter application dependency. We expand navigations before applying filters so that we have entityQueryables for all the the ETs before applying filter (so that we can apply for all ETs appropriately). But having a navigation in filter means we need to expand navs after applying filter which can cause more filters to applied and that goes on (forever :trollface: ). We may need a way to integrate this inside nav expansion.

**Comment by HappyNomad** [comment] 2017-10-16 17:51
I just started tackling my EF-Core code's `TODO`s regarding filtering.  Doing it at the model-level looks like it will work for me.  But I only got as far as the second use-case, and it needs a navigation property.  The current limitation doesn't cut it.  Please keep up the good work on filtering by upgrading this issue's priority, and addressing it sooner rather than later.  It's still early so changing the API to accommodate the more general scenario, if that's what makes sense, is still okay I think.

**Comment by HappyNomad** [comment] 2017-10-17 03:55
I just started tackling my EF-Core code's `TODO`s regarding filtering.  I didn't get far before running up against the two limitations mentioned in [What's New](https://docs.microsoft.com/en-us/ef/core/what-is-new/).  My second use-case already needs both a navigation property and to be defined on a subclass Entity Type.

> Limitations
> - Navigation references are not allowed. This feature may be added based on feedback.
> - Filters can only be defined on the root Entity Type of a hierarchy.

As for the first limitation, please keep up the good work on filtering by upgrading this issue's priority.  As for the second limitation, it seems I could partially get around it by writing:

    HasQueryFilter( a => !(a is Subclass && a.IsFoo) )

Will this work?  Even if it does, it's not enough for my second use-case since I also need to access a property on the subclass.

    HasQueryFilter( a => !(a is Subclass && a.IsFoo && ((Subclass)a).IsBar) )

This likely won't work, right?  So where's the tracked issue for this second limitation or do I need to create it?

**Comment by HappyNomad** [comment] 2017-10-18 22:11
After further thought, I see how to work with both limitations in place.

At the top of every class hierarchy within my domain model, alongside `ID`, I'll add a persisted property like `IsDeleted` or perhaps the inverse `IsActive` that's a nullable boolean.  As for the predicate that I was previously trying to pass to `HasQueryFilter`, I'll instead calculate it in memory and persist the result in this new property.

I can then use `HasQueryFilter` to filter on that property, rather than passing in the more complex predicate that comprises it.  I'll do this concisely once for the entire model:

	foreach ( var root in
		from e in modelBuilder.Model.GetEntityTypes()
		where e.BaseType == null
		select e
	) root.QueryFilter = (Expression<Func<IEntity, bool>>)(e => e.IsActive == null || e.IsActive.Value);

Does this look like a reasonable way to use the API?  It does throw an exception, since the `Func` must accept a parameter with the `root.ClrType` instead of `IEntity`.  Does EF-Core really need to enforce that?  If not then please remove that check to make this scenario easier and more efficient.  Otherwise, I'll have to dynamically build the lambda expression.

**Comment by HappyNomad** [comment] 2017-10-19 17:47
For my last `TODO` regarding filtering, I see _I do_ at least need navigation property support.

    modelBuilder.Entity<ThingContainer>().HasQueryFilter( c =>
        c.PurchasedBy.Any( o => o.ID == TenantID )
    );

The work around I described above won't work here, since involved objects exist in the database but not local memory.

Please increase this issue's priority. 🙏

**Closed** 2018-04-19 16:31 UTC
Labels: closed-fixed, type-enhancement

**Comment by chumtoadafuq** [comment] 2019-01-12 18:06
did this ever get implemented?

**Comment by ajcvickers** [comment] 2019-01-12 23:38
@chumtoadafuq It shipped with EF Core 2.1.
