### ISSUE TITLE
Deadlock in DbContext.SaveChanges when the connection is open before the call and the transaction timeout has expired

### ISSUE THREAD

**Issue by bogoslovskiy** [aspnet/EntityFrameworkCore#17858] opened 2019-09-16 09:33 UTC
#### 1. Create table:
``` SQL
CREATE DATABASE EntityFrameworkBugSemaphore
GO
USE EntityFrameworkBugSemaphore
GO
CREATE TABLE Table1
(
    [Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    [Str] NVARCHAR(8) NOT NULL
)
```
#### 2. C# object and CustomDbContext:
``` C#
public class Table1Row
{
  public int Id { get; set; }
  public string Str { get; set; }
}

public class CustomDbContext : DbContext
{
  private readonly DbConnection _connection;

  public CustomDbContext(DbConnection connection)
  {
       _connection = connection;
  }

  protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
  {
       if (!optionsBuilder.IsConfigured)
       {
           optionsBuilder.UseSqlServer(_connection, x => x.UseRowNumberForPaging());
       }
  }

  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
       modelBuilder.Entity<Table1Row>(
           entity =>
           {
               entity.ToTable("Table1");
               entity.Property(e => e.Id).ValueGeneratedOnAdd();
               entity.Property(e => e.Str).HasMaxLength(maxLength: 8);
           }
       );
  }
}
```
#### 3. Main.cs:
``` C#
public static void Main(string[] args)
{
    var transactionOptions = new TransactionOptions
    {
        IsolationLevel = IsolationLevel.ReadCommitted,
        Timeout = TimeSpan.FromSeconds(5)
    };

    using (var scope = new TransactionScope(TransactionScopeOption.Required, transactionOptions))
    {
        var dbConnection = new SqlConnection(@"Data Source=.\;Initial Catalog=EntityFrameworkBugSemaphore;Integrated Security = true");
        var dbContext = new CustomDbContext(dbConnection);
        dbConnection.Open();
        dbContext.Set<Table1Row>().Add(new Table1Row() { Str = "sometext" });
        
        Thread.Sleep(TimeSpan.FromSeconds(7));
        dbContext.SaveChanges();
        
        scope.Complete();
    }
}
```

### Helpful info
HandleAmbientTransaction method call **this._semaphore.Wait()**, then subscribe to TransactionCompleted event, event add method call HandleTransactionCompleted where once again call **this._semaphore.Wait()** 

### Further technical details

EF Core version: 2.2.6
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Framework 4.7.2
Operating system: Windows 10
IDE: Visual Studio 2017 or JetBrains Rider 2019.2.2

**Comment by divega** [comment] 2019-09-16 18:15
@bogoslovskiy could you try the repro with `SET READ_COMMITTED_SNAPSHOT ON`? This enables an implementation of read committed isolation level that performs less locks, and it is the default for databases EF Core creates, and also always on on Azure SQL DB.

**Comment by bogoslovskiy** [comment] 2019-09-17 13:00
@divega, thanks for your attention. Setting this option did not solve the problem.

**Comment by roji** [comment] 2019-10-22 17:12
The deadlock repros on 2.2.6, but no longer occurs on 3.0.0 and latest 3.1.0, almost certainly thanks to 34a6ae7e583f9ed0d8ea57354824b1938945891f (see #14218): RelationalConnection.HandleTransactionCompleted no longer takes a semaphore (this is where the deadlock was occurring).

Since 3.0.0 we get `System.InvalidOperationException: The transaction associated with the current connection has completed but has not been disposed.  The transaction must be disposed before the connection can be used to execute SQL statements.`. While the exception text isn't very informative, this is what SqlClient throws when trying to use a cancelled ambient transaction even without EF Core, so we're getting the expected behavior.

For reference, here's the full repro code used:

```c#
class Program
{
    const string ConnectionString = @"...";

    static void Main(string[] args)
    {
        using (var conn1 = new SqlConnection(ConnectionString))
        using (var ctx = new CustomDbContext(conn1))
        {
            ctx.Database.EnsureDeleted();
            ctx.Database.EnsureCreated();
        }

        using (var scope = new TransactionScope(TransactionScopeOption.Required, TimeSpan.FromSeconds(1)))
        {
            var dbConnection = new SqlConnection(ConnectionString);
            var dbContext = new CustomDbContext(dbConnection);
            dbConnection.Open();

            // With EF Core:
            // dbContext.Set<Blog>().Add(new Blog() { Name = "sometext" });
            // Thread.Sleep(TimeSpan.FromSeconds(2));
            // dbContext.SaveChanges();

            // With SqlClient ADO.NET:
            Thread.Sleep(TimeSpan.FromSeconds(2));
            using var cmd = new SqlCommand("SELECT 1", dbConnection);
            cmd.ExecuteNonQuery();

            scope.Complete();
        }
    }
}

public class CustomDbContext : DbContext
{
    public DbSet<Blog> Blogs { get; set; }

    readonly DbConnection _connection;

    public CustomDbContext(DbConnection connection)
    {
        _connection = connection;
    }

    static ILoggerFactory ContextLoggerFactory
        => LoggerFactory.Create(b => b.AddConsole().AddFilter("", LogLevel.Debug));

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(_connection)
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(ContextLoggerFactory);
        }
    }
}

public class Blog
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```

**Closed by roji** 2019-10-22 17:12 UTC
Labels: customer-reported, type-bug
