### ISSUE TITLE
Support mapping ulong, uint, ushort, sbyte, and char on SQL Server

### ISSUE THREAD

**Issue by markolbert** [aspnet/EntityFrameworkCore#6480] opened 2016-09-06 22:49 UTC
I have the following enum:

```
    [Flags]
    public enum Factor : long
    {
        Parent = ( 1 >> 0 ),
        PastSupporter = ( 1 >> 1 ),
    }

```

When I utilize the enum in an entity class, dotnet ef migrations add has a problem:

> dotnet : System.InvalidOperationException: The property 'Voter.Factors' is of type 'Factor' which is not supported by current database provider. Either change the 
> property CLR type or manually configure the database type for it.
> At line:1 char:1
> - dotnet ef migrations add SimplifyContactsFactors
> - ```
>   ```
>   - CategoryInfo          : NotSpecified: (System.InvalidO...se type for it.:String) [], RemoteException
>   - FullyQualifiedErrorId : NativeCommandError
>   
>   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
>   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
>   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
>   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>   
>   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
>   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
>   
>   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
>   
>   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
>   
>   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
>   
>   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
>   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
>   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
>   
>   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
>   
>   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
>   
>   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
>   
>   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.Execute(CommonOptions commonOptions, String name, String outputDir, String context, String 
>   environment, Action`1 reporter)
>   
>   at Microsoft.EntityFrameworkCore.Tools.Cli.MigrationsAddCommand.<>c__DisplayClass0_0.<Configure>b__0()
>   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
>   at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args)
> 
> The property 'Voter.Factors' is of type 'Factor' which is not supported by current database provider. Either change the property CLR type or manually configure the 
> database type for it.

By experimentation I've determined that it's the unsigned portion of the spec that's causing a problem (i.e., long works just fine).

Are unsigneds not supported? I ask because I'm looking to have as large a bitfield as I can to store options.

**Comment by ajcvickers** [comment] 2016-09-08 00:48
@markolbert Unsigned longs, ints, and shorts are not yet supported for SQL Server because the underlying ADO.NET provider for SQL Server ("a.k.a. SQL Client") does not support them. They can be used with other providers, such as SQLite. We plan to support them for SQL Server when type conversions are implemented. This is being tracked by issue #242. Closing this as a duplicate of that issue.

**Comment by markolbert** [comment] 2016-09-08 00:54
Thanx for the quick reply, and explanation.

- Mark
Sent from my iPhone

On Sep 7, 2016, at 5:49 PM, Arthur Vickers <notifications@github.com<mailto:notifications@github.com>> wrote:


@markolbert<https://github.com/markolbert> Unsigned longs, ints, and shorts are not yet supported for SQL Server because the underlying ADO.NET<http://ado.net> provider for SQL Server ("a.k.a. SQL Client") does not support them. They can be used with other providers, such as SQLite. We plan to support them for SQL Server when type conversions are implemented. This is being tracked by issue #242<https://github.com/aspnet/EntityFramework/issues/242>. Closing this as a duplicate of that issue.

-

**Comment by ajcvickers** [comment] 2017-10-16 17:06
These are the default conversions:

* sbyte -> smallint
* ushort -> int
* uint -> bigint
* ulong -> decimal(20, 0)
* char -> nchar(1)

These can be used by changing the store type:

* sbyte -> byte (not order preserving)
* ushort -> short (not order preserving)
* uint -> int (not order preserving)
* ulong -> long (not order preserving)
* char -> other string types of any size: char, nchar, varchar, nvarchar, text
* char -> int

**Closed by ajcvickers** 2017-10-16 17:06 UTC
Labels: type-enhancement
