### ISSUE TITLE
Query: SQL for queries which are projecting out single result from collection in projection

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#10001] opened 2017-10-06 21:20 UTC
```C#
var query = db.Users.Select(
        u => new
        {
            u.Text,
            T = u.Notifications.FirstOrDefault()
        })
    .ToList();
```
Generates following SQL
```SQL
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [u].[Text], [u].[Id]
      FROM [Users] AS [u]
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (3ms) [Parameters=[@_outer_Id='1'], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [n].[Id], [n].[Message], [n].[UserId]
      FROM [Notifications] AS [n]
      WHERE @_outer_Id = [n].[UserId]
```
It is N+1 queries. Since there is `FirstOrDefault` operator (hence only 1 related row max), instead of going through 2 queries form like include, we can just do cross apply (which include tries to avoid with 2 queries) since there is no duplicated data.

Expected SQL:
```
SELECT [u].[Text], [u].[Id], [t].[Id], [t].[Message], [t].[UserId]
FROM [Users] AS [u]
CROSS APPLY (
	SELECT TOP(1) [n].[Id], [n].[Message], [n].[UserId]
	FROM [Notifications] AS [n]
	WHERE [u].[Id] = [n].[UserId]
) AS [t]
```

**Comment by xmlapi** [comment] 2018-05-31 15:02
Can we get an ETA on this fix? Right now, we have several lateral joins (cross/outer apply) and it's resulting in N + 1 queries. If there are a 100 rows, it results in 101 queries instead of 1 query. Sometimes, we have several lateral joins....this can results in 100s of queries just for 1 query. It increases the CPU usage and increases the latency.

In Entity Framework 6, this would be 1 query (for 100 rows).....in Entity Frame Core 2.1 Final, it's 101 queries (for 100 rows).

Example:
SELECT Courses.CourseId, Courses.Category, LastDetail.*
FROM Courses
OUTER APPLY
(
   SELECT Details.Title, Details.Status, Details.Created
   FROM Details
   WHERE Details.CourseId = Course.CourseId
   ORDER BY Details.Created DESC
) LastDetail

LINQ:
var query = (from c in db.Courses
                    let ld = (from ld in db.Details
                                 where ld.CourseId == c.CourseId
                                orderby ld.Created descending
                                select new  { ld.Title, ld.Status, ld.Created }).FirstOrDefault()
                    select new { c.CourseId, c.Category, LastDetail = (ld == null) ? null : ld}).ToList()



Rewriting the "LINQ" for all these queries "just to make it work" is costly and not a good solution.

**Comment by zulander1** [comment] 2018-06-24 02:47
@xmlapi Do you have an example of "we have to let ld = from db.Details.Where().OrderBy().FirstOrDefault() and then left join again to db.Details." I am facing this issue and we cannot wait for 3.0
Thank's

**Comment by NiekGr** [comment] 2018-06-27 20:10
It's too bad this got postponed. But thanks for the update.

**Comment by zulander1** [comment] 2018-09-16 02:03
Hi,

Any possibility to have this issue fixed as soon as possible, in the next minor/major release ? 

Thank you

**Comment by ajcvickers** [comment] 2018-09-17 23:19
@zulander1 It's currently in the 3.0 milestone, which realistically is the best we can hope to do at this point.

**Comment by Looooooka** [comment] 2018-10-04 10:15
While people on the OLD EF can write queries...I have to use the OLD EF to generate the best query...then copy the resulting working SQL query and use FromSQL...and hack away to make this usable.
Needless to say this is the single most painful slowdown of programming since switching to .NET Core.
I have to say that for any non-basic queries this platform so far is pretty much useless. The main reason being this unacceptable performance loss due to generated multiple queries which SQL server can otherwise process in a second given the proper SQL syntax.

On the other hand I've refreshed my TSQL skills due to this bug. So I guess that's a "plus"

**Comment by kevindqc** [comment] 2018-11-08 15:39
It also seems to break `.Distinct()`. In EF6, since my query was done all in SQL Server, the DISTINCT was done there too and I would get one result back. But now because of this N+1 query, the `Distinct()` is called in C# and doesn't remove duplicates because while the objects all have the same property values, they are different objects.

**Comment by Rubis61** [comment] 2018-11-27 12:47
Hi,

I'm having the same issue. As many to many is not already supported, creating a request to retrieve information from this kind of relationship like Role and User dbset, it will make N+1 queries.

### Steps to reproduce

```c#
Context = new MainContext();
            
var request = Context.Users.Select(data => new UserDTO
{
	Id = data.Id,
	Roles = data.UserRoles.Select(x => x.Role.Name),
})
.ToList(); // We also tried without it

// Foreach to demonstrate request executing in console
foreach (var item in request)
{
	var roles = item.Roles;
}

Console.ReadLine();
```

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: W10
IDE: Visual Studio 2017 15.8.9

**Comment by zulander1** [comment] 2019-01-21 22:32
> @zulander1 It's currently in the 3.0 milestone, which realistically is the best we can hope to do at this point.

@ajcvickers are will still on target for this ?

**Comment by muchman** [comment] 2019-01-24 19:47
I wanted to add an additional issue I have seen with this.  After calling FirstOrDefault in a projection, only the first table after that point is joined.

```C#
var query = Context.Invoice.Select(invoice => new InvoiceSummary
{
    OriginCity = invoice.Transactions.OrderByDescending(t =>
    t.TransactionNumber).FirstOrDefault().Location.PostalAddress.City
});
```

Something like this will result in a null reference exception.  Location is joined but PostalAddress is not and is null.  Even if I add Include() statements to the start of the query it is ignored.

**Comment by Dona278** [comment] 2019-03-11 13:05
Same issue of @muchman...

**Comment by ajcvickers** [comment] 2019-07-24 17:40
Triage: we need to make this work for Sqlite also--so try window function or SQlite specific re-write.

**Comment by maumar** [comment] 2019-08-01 21:08
@muchman and @Dona278 issues are fixed in the latest bits - previously member pushdown (pushing member access that happens after FirstOrDefault, before it) only worked on one level of navigation access. In the new pipeline logic is recursive so arbitrary depth of navigation chains are supported

**Closed** 2019-08-21 02:36 UTC
Labels: closed-fixed, punted-for-2.1, query, type-enhancement

**Comment by cgountanis** [comment] 2019-09-05 16:47
Does this work with includes and sub where now?
