### ISSUE TITLE
Added entities are not detected/inserted when reloading entity

### ISSUE THREAD

**Issue by iokill** [aspnet/EntityFrameworkCore#15794] opened 2019-05-24 09:21 UTC
Hi!

I ran into a strange issue with EF Core 2.1 (I'm stuck on 2.1 for now):

I have a 3-level model hierarchy:

```csharp
public class Level1
{
    public int Id { get; set; }
    public ICollection<Level2> Children { get; set; } = new List<Level2>();
}

public class Level2
{
    public int Id { get; set; }
    public ICollection<Level3> Children { get; set; } = new List<Level3>();
}

public class Level3
{
    public int Id { get; set; }
    public string Value { get; set; }
}
```
If I update a `Level2` entity by modifying its `Children` collection through adding new entries and updating existing ones, `SaveChanges()` properly detects these changes and persists them.

If I however, before calling `SaveChanges()`, load the parent `Level1` entity with related entities like below, any newly added entities the the `Level2.Children` collection are ignored and only the modifications the existing are persisted:

```csharp
// modify entity1
var lvl2 = context.Level2
    .Include(l2 => l2.Children)
    .Single(l2 => l2.Id == lvl2Id);

lvl2.Children.First().Value = "changed";
lvl2.Children.Add(new Level3 { Value = "5" });

// load level1 parent
// XXX: this seems to confuse change tracking in EF Core to
// ignore the previously added Level3 instance
entity1 = context.Level1
    .Include(l1 => l1.Children)
        .ThenInclude(l2 => l2.Children)
    .Single(l1 => l1.Id == lvl1Id);

context.SaveChanges();
```
I'm actually not sure if this is intended behavior I just don't know about, or if this is a bug?

### Steps to reproduce

I've created a sample project here: https://github.com/iokill/EFCoreCollectionSaveBug

### Further technical details
EF Core version: 2.1.11
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: macOS 10.14.5

**Comment by ajcvickers** [comment] 2019-05-24 16:40
@iokill This is expected behavior. Since the query is executed by the database, it will only return entities that exist in the database. Entities that have not yet been saved can be accessed using `DbSet.Local` or `context.ChangeTracker.Entries()`.

**Comment by iokill** [comment] 2019-05-26 08:18
@ajcvickers Yes, that I understand. My issue is that this code

```csharp
// modify entity1
var lvl2 = context.Level2
    .Include(l2 => l2.Children)
    .Single(l2 => l2.Id == 1);

lvl2.Children.First().Value = "changed";
lvl2.Children.Add(new Level3 { Value = "5" });
context.SaveChanges();
```

works fine. It will result in `SaveChanges()` adding a new entry `Level3` to the `Children` collection which properly is persisted to the database. 

While doing this will **not** insert the new `Level3` entry into the database:

```csharp
// modify entity1
var lvl2 = context.Level2
    .Include(l2 => l2.Children)
    .Single(l2 => l2.Id == 1);

lvl2.Children.First().Value = "changed";
lvl2.Children.Add(new Level3 { Value = "5" });

// This code here is not intended to modify the lvl2 instance from above,
// but simply loads lvl2's parent entity. In reality this happens hidden in some
// middleware
entity1 = context.Level1
    .Include(l1 => l1.Children)
        .ThenInclude(l2 => l2.Children)
    .Single(l1 => l1.Id == lvl1Id);

// this is intended to persist the changes to lvl2 from above
context.SaveChanges();
```

After this `SaveChanges` the new `Level3` entry with `Value = "5"` is not in the database! I checked this by directly looking into the sqlite database file. So somehow EF Core ignores or skips this change: `lvl2.Children.Add(new Level3 { Value = "5" });`

**Comment by ajcvickers** [comment] 2019-05-27 18:56
@iokill Sorry about that--I missed that important details.

Note for triage: also repros on 2.2.4.

**Comment by iokill** [comment] 2019-05-28 12:53
@ajcvickers no worries. I should have explained it better from the start. 😄

**Comment by ajcvickers** [comment] 2019-08-01 19:08
Verified that this is fixed in the current [nightly builds](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md)

**Closed by ajcvickers** 2019-08-01 19:08 UTC
Labels: closed-fixed, customer-reported, type-bug
