### ISSUE TITLE
Replacing a property with owned type doesn't work if there is owned types nesting in v2.1 RC1

### ISSUE THREAD

**Issue by andriysavin** [aspnet/EntityFrameworkCore#12118] opened 2018-05-23 14:21 UTC
I'm trying to use replacing properties with owned types since it was [promised](https://github.com/aspnet/EntityFrameworkCore/issues/9803#issuecomment-333918319) to fix in 2.1.  This feature seems to be working ok with 1 level of owned types nesting. However, if you have 2 nested owned types, EF discards changes on the entity property. Its better to provide an example:

```C#
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace TestEfCtorInjectionWithOwnedTypes
{
    public class MyEntity
    {
        public int Id { get; set; }
        public OwnedEntity Owned { get; set; }
        private MyEntity() { }
        public MyEntity(OwnedEntity owned) => Owned = owned;
    }

    public class OwnedEntity
    {
        public OwnedOwnedEntity OwnedOwnedProperty { get; private set; }
        private OwnedEntity() { }
        public OwnedEntity(OwnedOwnedEntity ownedOwnedProperty)
            => OwnedOwnedProperty = ownedOwnedProperty;
    }

    public class OwnedOwnedEntity
    {
        public double MyProperty { get; private set; }
        private OwnedOwnedEntity() { }
        public OwnedOwnedEntity(double myProperty) => MyProperty = myProperty;
    }

    class MyDbContext : DbContext
    {
        public MyDbContext(DbContextOptions options) : base(options) { }

        public DbSet<MyEntity> MyEntities { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MyEntity>(cb =>
            {
                cb.OwnsOne(seg => seg.Owned, b =>
                {
                    b.OwnsOne(e => e.OwnedOwnedProperty);
                });
            });
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var services = new ServiceCollection();

            services.AddDbContext<MyDbContext>(options =>
                options.UseInMemoryDatabase("MyDatabase"));

            using (var sp = services.BuildServiceProvider())
            {
                int entityId;

                using (var scope = sp.CreateScope())
                {
                    var dbContext = scope.ServiceProvider.GetRequiredService<MyDbContext>();

                    var entity = new MyEntity(new OwnedEntity(new OwnedOwnedEntity(4242)));

                    dbContext.MyEntities.Add(entity);

                    dbContext.SaveChanges();

                    entityId = entity.Id;
                }

                using (var scope = sp.CreateScope())
                {
                    var dbContext = scope.ServiceProvider.GetRequiredService<MyDbContext>();

                    var entity = dbContext.MyEntities.Find(entityId);

                    System.Console.WriteLine("MyProperty before changing: " +
                        entity.Owned.OwnedOwnedProperty.MyProperty);

                    entity.Owned = new OwnedEntity(new OwnedOwnedEntity(4848));

                    System.Console.WriteLine("MyProperty before saving changes: " + 
                        entity.Owned.OwnedOwnedProperty.MyProperty);

                    dbContext.SaveChanges();

                    System.Console.WriteLine("MyProperty after saving changes: " +
                        entity.Owned.OwnedOwnedProperty.MyProperty);
                }
            }
        }
    }
}


```

The output I'm getting:

```
MyProperty before changing: 4242
MyProperty before saving changes: 4848
MyProperty after saving changes: 4242
```

**Comment by andriysavin** [comment] 2018-05-26 15:12
Just to give a more real life example, here are some of my models (simplified).
GeoPosition and GeoSegment are Owned Types. And assigning `MyEntity.Location = new GeoSegment(new GeoPosition(...), new GeoPosition(...))` is not saved, as described earlier.

```
 public sealed class GeoPosition
 {
        public double Latitude { get; private set; }
        public double Longitude { get; private set; }

        private GeoPosition(){}

        public GeoPosition(double latitude, double longitude)
        {
            Latitude = latitude;
            Longitude = longitude;
        }
}

public sealed class GeoSegment
{
        public GeoPosition Start { get; private set; }
        public GeoPosition End { get; private set; }

        private GeoSegment(){}

        public GeoSegment(GeoPosition start, GeoPosition end)
        {
            Start = start;
            End = end;
        }
}

public class MyEntity
{
        public int Id { get; set; }
        public GeoSegment Location { get; set; }

        public MyEntity(GeoSegment location)
        {
            Location = location;
        }
}
```

**Comment by AndriySvyryd** [comment] 2018-05-29 18:56
@ajcvickers The issue here is that when we attach `OwnedEntity` the initial fixup finds the existing `OwnedOwnedEntity` and overrides the new navigation with the old dependent. Fixing this is potentially a breaking change.

The workaround is to set the dependent after the new owned entity is fixed up:
```C#
using (var context = new MyDbContext(options))
{
    var entity = context.MyEntities.Find(entityId);

    Console.WriteLine("MyProperty before changing: " +
                             entity.Owned.OwnedOwnedProperty.MyProperty);

    entity.Owned = new OwnedEntity(null);

    context.ChangeTracker.DetectChanges();

    context.Entry(entity).Reference(e => e.Owned).TargetEntry.Reference(e => e.OwnedOwnedProperty).CurrentValue
        = new OwnedOwnedEntity(4848);

    Console.WriteLine("MyProperty before saving changes: " +
                             entity.Owned.OwnedOwnedProperty.MyProperty);

    context.SaveChanges();

    Console.WriteLine("MyProperty after saving changes: " +
                             entity.Owned.OwnedOwnedProperty.MyProperty);
}
```

**Comment by ajcvickers** [comment] 2018-06-01 22:01
Note from triage: non-owned case with conflicting FK should throw, but low priority.

**Comment by Ranmoro** [comment] 2018-07-10 13:03
The problem is repeated at the first level of the object, as well as with of one to one relationship.

**Comment by Alantoo** [comment] 2018-09-09 07:03
Hi everyone.

I had similar issue. I was unable to update property of owned type of an entity.
Hope it will be helpful for someone as temporary fixup until we get solution from ef team.
Here a code snipped which works for me to update entity with immutable owned types:

```
public static EntityEntry<TEntity> UpdateImmutable<TEntity>(this DbContext context,
            TEntity immutableEntity)
            where TEntity : class, IEntity
        {
            var oldEntity = context.ChangeTracker.Entries<TEntity>()
                .FirstOrDefault(_ => _.Entity.Id == immutableEntity.Id);

            if (oldEntity != null)
            {
                oldEntity.State = EntityState.Detached;
            }

            var updatedEntry = context.Entry(immutableEntity);

            if (oldEntity != null)
            {
                foreach (PropertyEntry property in updatedEntry.Properties)
                {
                    var oldPropertyName = property.Metadata.Name;
                    var oldProperty = oldEntity.Property(oldPropertyName);

                    if (property.Metadata.IsConcurrencyToken)
                    {
                        property.CurrentValue = oldProperty.CurrentValue;
                        property.OriginalValue = oldProperty.OriginalValue;
                    }
                }

                foreach (ReferenceEntry navigation in updatedEntry.Navigations.OfType<ReferenceEntry>())
                {
                    var oldNavigationName = navigation.Metadata.Name;
                    var oldNavigation = oldEntity.Navigation(oldNavigationName);
                    var entityEntry = context.Entry(oldNavigation.CurrentValue);
                    
                    if (entityEntry.State != EntityState.Detached && !Equals(oldNavigation.CurrentValue, navigation.CurrentValue))
                    {
                        entityEntry.State = EntityState.Detached;
                        context.Entry(navigation.CurrentValue).State = EntityState.Modified;
                    }
                }
            }

            updatedEntry.State = EntityState.Modified;

            return updatedEntry;
        }
```

If someone can suggest better approach it would be nice.

**Comment by smariussorin** [comment] 2018-09-26 18:50
@Alantoo Does it fix the nested own types?

I solved like his for anyone for a quick fix ( We have only a entity with own type so this approach is simpler for me, without reflexion)

`context.Entry(entityExisting).Reference(p => p.OwnTypeA).TargetEntry.CurrentValues.SetValues(entityUpdate.OwnTypeA);
context.Entry(entityExisting).Reference(p => p.OwnTypeB).TargetEntry.CurrentValues.SetValues(entityUpdate.OwnTypeB);
context.Entry(entityExisting.OwnTypeB).Reference(p => p.OwnTypeB_SubOwnType).TargetEntry.CurrentValues.SetValues(entityUpdate.OwnTypeB.OwnTypeB_SubOwnType);
context.Entry(entityExisting).CurrentValues.SetValues(entityUpdate);

context.Entry(entityExisting).Reference(p => p.OwnTypeA).TargetEntry.State = EntityState.Modified;
context.Entry(entityExisting).Reference(p => p.OwnTypeB).TargetEntry.State = EntityState.Modified;
context.Entry(entityExisting.OwnTypeB).Reference(p => p.OwnTypeB_SubOwnType).TargetEntry.State = EntityState.Modified;
context.Entry(entityExisting).State = EntityState.Modified;`

I`m waiting for a live so I can remove redundant code

**Comment by FabriDamazio** [comment] 2018-10-01 13:15
I can confirm that @smariussorin workaround works. =))

Tested with a owned type with 5 nested owned types

**Comment by NickCook-StruMIS** [comment] 2018-10-10 14:07
I have this problem as well, although @smariussorin solution did not work for me but @AndriySvyryd solution works perfectly. Do we know when this problem will be resolved so I can remove my temporary work around. Thanks.

**Comment by ytzhakov** [comment] 2018-10-17 19:17
This issue makes the whole 'owned entity types' useless.
I imagine that owned types were created with DDD in mind but this is a show stopper.

Is there a workaround, perhaps by overriding SaveChanges(), that will recursively fix this for all owned entities as well as for nested owned entities?

**Comment by AndriySvyryd** [comment] 2019-01-08 22:19
@Mortana89 I think that's actually another manifestation of https://github.com/aspnet/EntityFrameworkCore/issues/13578

**Comment by NickCook-StruMIS** [comment] 2019-01-09 12:22
Yes, I am still waiting for a fix to this. I have temporary workaround code in my BaseContext that I want to remove because it is causing other knock on issues for our software now. Is this Issue being resolved in Core version 3.0?

Thanks

**Comment by ajcvickers** [comment] 2019-01-09 17:35
@NickCook-StruMIS This issue is in the 3.0 milestone, which means that it is tentatively planned to be fixed in the 3.0 release.

**Closed** 2019-03-14 00:52 UTC
Labels: breaking-change, customer-reported, type-bug

**Comment by chanido** [comment] 2019-03-23 10:55
I've had this issue and written [a post](http://www.codegrimoire.com/2019/03/configuring-and-updating-nested-value.html) on how we resolved it.

I hope this helps someone else.

**Comment by vertonghenb** [comment] 2019-03-26 19:23
Just an update, not working in the Preview 3, still throws the following exception when replacing an owned owned type with a new one:
System.InvalidOperationException: The instance of entity type 'SalesOrderLineItem.Price#UnitPrice' with the key value '{SalesOrderLineItemSalesOrderLineId: 14}' is marked as 'Deleted', but the instance of entity type 'SalesOrderLineItem' with the key value '{SalesOrderLineId: 14}' is marked as 'Modified' and both are mapped to the same row.

**Comment by AndriySvyryd** [comment] 2019-03-26 19:34
@vertonghenb The fix will be shipped in 3.0 preview 4

**Comment by lonix1** [comment] 2019-07-07 11:13
None of the workarounds work when using `UserManager<TUser>` instead of `DbContext`.

Does someone have this use case, and has a small snippet of working code to share?

e.g.
`User` is entity
`User.Token` is owned type
`User.Token.Hash` is owned-owned type

**Comment by Cogax** [comment] 2019-07-16 12:03
> None of the workarounds work when using `UserManager<TUser>` instead of `DbContext`.
> 
> Does someone have this use case, and has a small snippet of working code to share?
> 
> e.g.
> 
> 
> // `User` is entity
> // `User.Token` is owned type
> // `User.Token.Hash` is owned-owned type
> user.Token = someNewToken;
> await userManager.UpdateAsync(user);
> // user.Token and user.Token.Hash are not updated
> I posted by use case to [SO here](https://stackoverflow.com/questions/56939294/updating-owned-owned-entities-in-ef-2-2).


Try something like that:
```
// `User` is entity
// `User.Token` is owned type
// `User.Token.Hash` is owned-owned type
user.Token = someNewToken;

var hash = user.Token.Hash
context.ChangeTracker.DetectChanges();
context.Entry(user).Reference(x => x.Token).TargetEntry.Reference(x => x.Hash).CurrentValue = hash;
context.Entry(user).State = EntityState.Modified;
await context.SaveChangesAsync();
```

**Comment by M-okhovvat** [comment] 2020-12-22 07:20
@AndriySvyryd currently I'm using ef core 5 preview and still have the same issue which @andriysavin mentioned earlier. 
In order to respect the separation of concern with a DDD approach, I don't have access to the dbContext in the application layer of my application, in which entity with owned type should be updated...
is there any workaround by overriding the SaveChanges method???

**Comment by AndriySvyryd** [comment] 2021-01-05 20:54
@m-okhovat This issue was fixed in 3.0.0, if you are still experiencing it in 5.0.0 file a new issue with a small repro project

**Comment by virzak** [comment] 2021-03-24 22:55
I'm not sure if this is the same issue, but `EntityEntry<T>.CurrentValues` does not include Owned entity properties. This results in `CurrentValues.SetValues(disconnected)` to skip the owned entity's properties.

**Comment by AndriySvyryd** [comment] 2021-03-24 23:07
@virzak That's by design, you need to traverse navigations by calling `entityEntry.Reference("OwnedReference").EntityEntry`
