### ISSUE TITLE
ThenInclude failure

### ISSUE THREAD

**Issue by myblindy** [aspnet/EntityFrameworkCore#15543] opened 2019-05-01 06:09 UTC
Using `ThenInclude` on a collection parent `Include` throws a thoroughly opaque exception:

```
System.InvalidOperationException: 'Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'join Status .Status in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ndrdb.Data.Status]) on Property([h], "StatusId") equals Property([.Status], "Id")' could not be translated and will be evaluated locally.'. This exception can be suppressed or logged by passing event ID 'RelationalEventId.QueryClientEvaluationWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.'
```

If I read that right, it believes including the status table needs to be evaluated locally?

The code to reproduce (it's long):

The context:

```c#
    public partial class ndrdbContext : DbContext
    {
        public ndrdbContext()
        {
        }

        public ndrdbContext(DbContextOptions<ndrdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Dr> Dr { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Status> Status { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Server=(localdb)\\drdb;Database=ndrdb;Trusted_Connection=True;");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "3.0.0-preview6.19230.3");

            modelBuilder.Entity<Dr>(entity =>
            {
                entity.ToTable("dr");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Description1)
                    .IsRequired()
                    .HasColumnName("description1")
                    .IsUnicode(false);

                entity.Property(e => e.Description2)
                    .HasColumnName("description2")
                    .IsUnicode(false);

                entity.Property(e => e.DrNumber).HasColumnName("dr_number");

                entity.Property(e => e.Priority).HasColumnName("priority");

                entity.Property(e => e.ProjectId).HasColumnName("project_id");

                entity.HasOne(d => d.Project)
                    .WithMany(p => p.Dr)
                    .HasForeignKey(d => d.ProjectId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__dr__project_id__276EDEB3");
            });

            modelBuilder.Entity<History>(entity =>
            {
                entity.HasKey(e => new { e.DrId, e.HistNum })
                    .HasName("PK__history__049BDF4DF5E52A1F");

                entity.ToTable("history");

                entity.Property(e => e.DrId).HasColumnName("dr_id");

                entity.Property(e => e.HistNum).HasColumnName("hist_num");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasColumnName("description")
                    .IsUnicode(false);

                entity.Property(e => e.StatusId).HasColumnName("status_id");

                entity.HasOne(d => d.Dr)
                    .WithMany(p => p.History)
                    .HasForeignKey(d => d.DrId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__history__dr_id__2A4B4B5E");

                entity.HasOne(d => d.Status)
                    .WithMany(p => p.History)
                    .HasForeignKey(d => d.StatusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__history__status___2B3F6F97");
            });

            modelBuilder.Entity<Project>(entity =>
            {
                entity.ToTable("project");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnName("name")
                    .HasMaxLength(80)
                    .IsUnicode(false);

                entity.Property(e => e.Number)
                    .IsRequired()
                    .HasColumnName("number")
                    .HasMaxLength(15)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Status>(entity =>
            {
                entity.ToTable("status");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnName("name")
                    .HasMaxLength(15)
                    .IsUnicode(false);
            });
        }
    }
```

Dr.cs:
```c#
    public partial class Dr
    {
        public Dr()
        {
            History = new HashSet<History>();
        }

        public int Id { get; set; }
        public int DrNumber { get; set; }
        public int Priority { get; set; }
        public int ProjectId { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }

        public virtual Project Project { get; set; }
        public virtual ICollection<History> History { get; set; }
    }
```

History.cs:

```c#
    public partial class History
    {
        public int DrId { get; set; }
        public int HistNum { get; set; }
        public string Description { get; set; }
        public int StatusId { get; set; }

        public virtual Dr Dr { get; set; }
        public virtual Status Status { get; set; }
    }
```

Project.cs:

```c#
    public partial class Project
    {
        public Project()
        {
            Dr = new HashSet<Dr>();
        }

        public int Id { get; set; }
        public string Number { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Dr> Dr { get; set; }
    }
```

Status.cs:

```c#
    public partial class Status
    {
        public Status()
        {
            History = new HashSet<History>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<History> History { get; set; }
    }
```

Calling code:

```c#
        public IActionResult Index([FromServices] ndrdbContext context)
        {
            return View(new IndexViewModel
            {
                Drs = context.Dr
                    .Include(w => w.Project)
                    .Include(w => w.History).ThenInclude(history => history.Status)
                    .Take(30).ToList(),
            });
        }
```

### Further technical details
EF Core version: EF Core 3.0.0-preview6*
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: VS 2019 16.0.2

**Comment by myblindy** [comment] 2019-05-02 19:57
It's actually even worse, if I remove the `ThenInclude` portion, it refuses to join on the `history` table, and accessing fields from the `History` property later fires off individual queries:

```c#
                Drs = context.Dr
                    .Include(w => w.Project)
                    .Include(w => w.History)//.ThenInclude(history => history.Status)
                    .Take(30).ToList(),
```

```sql
exec sp_executesql N'SELECT [t].[id], [t].[description1], [t].[description2], [t].[dr_number], [t].[priority], [t].[project_id], [w.Project].[id], [w.Project].[name], [w.Project].[number]
FROM (
    SELECT TOP(@__p_0) [d].[id], [d].[description1], [d].[description2], [d].[dr_number], [d].[priority], [d].[project_id]
    FROM [dr] AS [d]
) AS [t]
INNER JOIN [project] AS [w.Project] ON [t].[project_id] = [w.Project].[id]',N'@__p_0 int',@__p_0=30

exec sp_executesql N'SELECT [h].[dr_id], [h].[hist_num], [h].[description], [h].[status_id]
FROM [history] AS [h]
WHERE @_outer_Id = [h].[dr_id]',N'@_outer_Id int',@_outer_Id=2

exec sp_executesql N'SELECT [h].[dr_id], [h].[hist_num], [h].[description], [h].[status_id]
FROM [history] AS [h]
WHERE @_outer_Id = [h].[dr_id]',N'@_outer_Id int',@_outer_Id=8

-- and so on
```

**Comment by myblindy** [comment] 2019-05-02 20:23
Oh...

Well I figured out what's wrong: it doesn't support tables with multiple-field keys. I replaced the primary key with a plain auto-increment integer and everything worked as expected. 

I'll keep this for now, but it would be very useful if the query compiler supported sub-tables like this:

```sql
create table history (
	dr_id int not null, 
	hist_num int not null,
	[description] varchar(max) not null, 
	status_id int not null,
	primary key(dr_id, hist_num),
	foreign key(dr_id) references dr(id),
	foreign key(status_id) references [status](id));
```

**Comment by maumar** [comment] 2019-08-01 21:00
verified this works in current bits. we produce the following sql:

```sql
SELECT t.id, t.description1, t.description2, t.dr_number, t.priority, t.project_id, p.id, p.name, p.number, t0.dr_id, t0.hist_num, t0.description, t0.status_id, t0.id, t0.name
    FROM 
    (
        SELECT TOP(@__p_0) d.id, d.description1, d.description2, d.dr_number, d.priority, d.project_id
        FROM dr AS d
    ) AS t
    INNER JOIN project AS p ON t.project_id == p.id
    LEFT JOIN Projection Mapping:
    (
        SELECT h.dr_id, h.hist_num, h.description, h.status_id, s.id, s.name
        FROM history AS h
        INNER JOIN status AS s ON h.status_id == s.id
    ) AS t0 ON t.id == t0.dr_id
    ORDER BY t.id ASC, p.id ASC, t0.dr_id ASC, t0.hist_num ASC, t0.id ASC
```

No need to add regression test since we already have cases of include for entities with composite kesy (GearsOfWar model) - closing

**Closed by maumar** 2019-08-01 21:00 UTC
Labels: customer-reported, query, type-bug, verify-fixed
