### ISSUE TITLE
System InvalidOperationException ("Invalid attempt to call NextResult when reader is closed.") in Microsoft.Data.Sqlite

### ISSUE THREAD

**Issue by bmanners** [aspnet/EntityFrameworkCore#18307] opened 2019-10-10 03:32 UTC
When using EF core 3.0 and calling some of the DbContext methods there is a System InvalidOperation exception thrown. If I change the exception settings in VS to stop on this type of exception the description is "Invalid attempt to call NextResult when reader is closed." For the application i am working on the exception is thrown many times in a tight loop which slows down VS considerably. When running my application outside VS it works as expected so the exception must be handled inside EF core somewhere.

This could be related to issue https://github.com/aspnet/EntityFrameworkCore/issues/17614#issuecomment-540163786 which is where I got the code to reproduce the issue.

The methods causing the exception are: 
context.Collection.ToList();
context.SaveChanges();
dbContext.MyObject.Find(ID);  <- not able to repo this one in a simple project but is happening in the codebase I am working on.

### To Reproduce
The attached simple console app reproduces the issue.

```
using System.ComponentModel.DataAnnotations;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace EFCore_Test
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new MyDbContext())
            {
                context.Database.EnsureCreated();

                var result = context.Collection.ToList();   // Throws exception.
                context.Collection.Add(new MyObject());
                context.SaveChanges();                      // Throws exception.
                result = context.Collection.ToList();       // Throws exception.

            }
        }
    }

    class MyDbContext : DbContext
    {
        public DbSet<MyObject> Collection { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var connection = new SqliteConnection("Data Source=dbFile.Db");
            connection.Open();
            optionsBuilder.UseSqlite(connection);
        }
    }

    class MyObject
    {
        public int Id { get; set; }
    }

}

```

### Additional context

Microsoft.Data.Sqlite version:  3.0.0
Target framework: NET Core 3.0
Operating system: Win 10 1903
EF Core 3.0.0
Visual Studio version 16.3.2

**Comment by ajcvickers** [comment] 2019-10-10 16:14
@bmanners I am not able to reproduce this. However, the code above does leak an open SqliteConnection object because the connection is created and opened outside of EF. This will eventually result in the connection being garbage collected (once the context goes out of scope) and finalized, which may be where the error is coming from.

/cc @bricelam

**Comment by ajcvickers** [comment] 2019-10-11 21:54
@bmanners Can you try using the latest [daily build](https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md) Without a way to reproduce this we don't have much to go on.

**Comment by bmanners** [comment] 2019-10-12 11:14
If you are not getting the same exception with the same code could it be environment related? version of SQLite ? 64 vs 32 bit? Windows version? anything else that could be different?

Note: Visual studio, I think,  by default will not catch this type of exception but you see it in the output window OR you can change the exception settings so Visual Studio will Break on this exception.

I will try test the daily build next week.

Cheers
Brett

**Comment by ajcvickers** [comment] 2019-10-14 16:06
@bmanners It might help if you attached the Visual Studio solution so that we can rule out some of the potential differences you mentioned,

**Comment by bmanners** [comment] 2019-10-16 06:40
[EF Core test.zip](https://github.com/aspnet/EntityFrameworkCore/files/3732770/EF.Core.test.zip)

Solution attached. Let me know if the Bin / Obj folders are of any use and i can upload those as well.

I haven't had a chance to test out the latest build of EF core yet either.

Cheers
Brett

**Comment by ajcvickers** [comment] 2019-10-16 18:13
@bmanners I ran your code on a fresh install of Visual Studio 2019 16.4 preview 2 on a fresh install of Windows 10 64-bit and did not see any errors, either in the debugger or running outside of the debugger.

**Comment by szpeplinski** [comment] 2019-10-17 09:06
I had the same problem as @bmanners. After upgrading entity framework core from 2.2.6 to 3.0.0
I started getting the same exception no matter what operation I do with DBContext. 
Upgrading Visual Studio from 16.3.5 to 16.4 preview 2 fixed the problem.

**Comment by bigworld12** [comment] 2019-10-18 00:26
I am also getting bombarded with these exceptions on any operation to the DB.
but the transactions do complete, the error is just caught via visual studio, but doesn't affect the actual end result at all (at least from what i saw).

package version : 3.1.0-preview1.19506.2
project target framework : wpf .netcore 3
dotnet version : 3.0.100
windows version : Version 10.0.18999.1

**Comment by bmanners** [comment] 2019-10-18 01:13
Thanks @szpeplinski , I updated my preview install of VS to 16.4 preview 2, ran the code I posted above and the exceptions stopped. Looks like they changed something in the compiler??

Cheers
Brett

**Comment by ajcvickers** [comment] 2019-10-18 21:38
Looks like this has been fixed in something that shipped with the latest VS preview, so closing this as external.

**Comment by roji** [comment] 2019-10-24 13:29
Looked into this as part of #18509, and reproduced the issue.

When Dispose or Closed is called on the same SqliteDataReader more than once, the dispose logic is repeated. Part of that logic is [to execute NextResult](https://github.com/aspnet/EntityFrameworkCore/blob/1051fd76d1db1ccbbe28b47a48a742ef34aa2182/src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs#L243), which throws an exception is the reader has already been closed/disposed. That exception is caught and ignored in Dispose, but it does cause a needless perf slowdown and disrupts the debugging experience.

Submitted #18572 to exit Dispose early if the reader has already been closed/disposed.

**Comment by roji** [comment] 2019-10-24 13:31
PS not sure why the issue disappeared for users above, but it's likely to be related to VS exception setting changes across versions. Confirmed that with regular EF Core code (e.g. `ctx.Blogs.ToList()`) an exception is generated internally before #18572.

**Closed** 2019-10-25 13:11 UTC
Labels: area-adonet-sqlite, closed-fixed, customer-reported
