### ISSUE TITLE
Migrations after Rename field with Datetime type doesn't work 

### ISSUE THREAD

**Issue by vRITHNER** [aspnet/EntityFrameworkCore#9344] opened 2017-08-06 11:47 UTC
I just renamed field in many tables with type DateTime
Then I add a migration but the Up() method is empty
but it works well with string fields

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.
Rename a field Datetime 
Add a migration

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
//before modification:
  public DateTime CreatedDateFrm { get; set; }
//after modification:
  public DateTime CreatedFrm { get; set; }
```
In command shell:
`dotnet ef migrations add "data_5" -c Db -v -p ..\GrrDev2.Data\GrrDev2.Data.csproj`

Migration class:

```
 public partial class data_5 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
```

### Further technical details
EF Core version: (found in project.json or packages.config)
Microsoft.EntityFrameworkCore (2.0.0)
Database Provider: 
Microsoft.EntityFrameworkCore.SqlServer (2.0.0)
Operating system: 

```
Microsoft Visual Studio Enterprise 2017 Preview
Version 15.3.0 Preview 7.0
VisualStudio.15.Preview/15.3.0-pre.7.0+26730.0
Microsoft .NET Framework
Version 4.7.02542

```
```
.NET Command Line Tools (2.1.0-preview1-007012)

Product Information:
 Version:            2.1.0-preview1-007012
 Commit SHA-1 hash:  b60272d64d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16257
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.0-preview1-007012\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by bricelam** [comment] 2017-08-07 18:07
Confirmed. Something is wrong. I get the following on the latest 2.0.0 bits.
```csharp
migrationBuilder.DropColumn(
    name: "DateTime",
    table: "Entities");

migrationBuilder.AddColumn<DateTime>(
    name: "Updated",
    table: "Entities",
    type: "datetime2",
    nullable: false,
    defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
```
For some reason, the Migrations model differ isn't pairing up the old an new column.

**Comment by bricelam** [comment] 2017-08-07 18:17
Hmm, I'm getting this for all types, not just `DateTime`.

**Comment by bricelam** [comment] 2017-08-17 20:41
Looks like the model snapshot returns `null` for `IProperty.Relational().ColumnType` if it's not configured, but the model always returns a type.

@ajcvickers @AndriySvyryd Should we change the way `ColumnType` works on the snapshot or just compensate in the model differ?

**Comment by bricelam** [comment] 2017-08-17 20:43
If we want to make it consistent, we could either:
1. Always serialize the type into the snapshot, or
2. Lazily compute it using the current provider after the snapshot is loaded.

**Comment by bricelam** [comment] 2017-08-17 20:46
```csharp
var oldType = new MyContextModelSnapshot().Model
    .FindEntityType("MyProject.MyEntity")
    .FindProperty("MyProperty")
    .Relational().ColumnType;

var newType = new MyContext().Model
    .FindEntityType("MyProject.MyEntity")
    .FindProperty("MyProperty")
    .Relational().ColumnType;

Assert.Equal(oldType, newType);
```

**Comment by AndriySvyryd** [comment] 2017-08-17 21:13
@bricelam Probably need a design meeting, as we've already discussed this at least twice

**Comment by bricelam** [comment] 2017-08-17 21:16
Will cue it up. Although this is mostly orthogonal to #8624.

**Comment by bricelam** [comment] 2017-08-17 21:19
I'm leaning towards writing it into the model snapshot and compensating for older snapshots.

**Comment by ajcvickers** [comment] 2017-08-18 15:44
Agree with @bricelam.

**Comment by bricelam** [comment] 2017-08-18 16:34
I changed my approach (see the PR). There were a few other places we only want the value if it was explicitly configured by the user. Also, while writing them in the snapshot is fine, that would make it more difficult to keep them out of the migrations where they definitely shouldn't be.

**Comment by stewshka** [comment] 2017-09-04 16:04
@bricelam 
Hello, after 2.0 my migrations are being generated with explicit types. 

Example: my GUID columns are being generated with this:
``` C#
migrationBuilder.AddColumn<Guid>(... type: "BLOB" ... );
migrationBuilder.CreateTable(name: "X", columns: table => new {
                                 Id = table.Column<Guid>(type: "BLOB", nullable: false)
} ...
```
Since i generate migrations with a mode=memory sqlite database, and my application runs on postgres (that dont understand BLOB), its breaking now.


Your pull request already fixes this issue, right?
Thanks!

**Comment by bricelam** [comment] 2017-09-05 17:04
Yes, that is another symptom of the same underlying bug that was fixed.

**Comment by Eilon** [comment] 2017-09-15 15:54
This patch bug is **approved** for the 2.0.x patch. Please send a PR to the `feature/2.0.1` branch and get it reviewed and merged. When we have the `rel/2.0.1` branches ready please port the commit to that branch.

**Closed** 2017-10-11 23:22 UTC
Labels: closed-fixed, patch-approved, regression, type-bug

**Comment by smitpatel** [comment] 2017-10-17 18:18
@bricelam - Are we sure, that the cause of issue in first post is the same? I am not able to repro empty migration.

**Comment by bricelam** [comment] 2017-10-18 16:26
I wasn't able to repro it either, but I did find the bug that we ended up fixing while trying.

**Comment by Eilon** [comment] 2017-10-23 22:50
Hi, we have a public test feed that you can use to try out the ASP.NET/EF Core 2.0.3 patch!

To try out the pre-release patch, please refer to the following guide:
* https://github.com/aspnet/Announcements/issues/274 (info)
* https://github.com/aspnet/Home/issues/2254 (discussions and questions)

We are looking for feedback on this patch. We'd like to know if you have any issues with this patch by updating your apps and libraries to the latest packages and seeing if it fixes the issues you've had, or if it introduces any new issues. If you have any issues or questions, please reply on this issue to let us know as soon as possible.

Thanks,
Eilon
