### ISSUE TITLE
QUery: Contains(entity) on closure variable throws exception

### ISSUE THREAD

**Issue by snoopydoopi** [aspnet/EntityFrameworkCore#10081] opened 2017-10-15 18:46 UTC
### Description

I have a simple query which worked fine in EF Core 1.1, but is not working anymore in EF Core 2.0. This is a blocker for our project in order to migrate to ASP.NET 2.0 / EF Core 2.0. Do you plan to release a bugfix release soon? I have seen that there are quite some issues with Includes (which is a very fundamental functionality). Therefore it would be really appreciated if you could consider relasing a bugfix version before the next bigger version 2.1 which is announced for somewhen in Q1 2018. 

### Steps to reproduce

Entities:

```C#
    public class Author
    {
        public int AuthorId { get; set; }
        public string Name { get; set; }
        public List<Blog> Blogs { get; set; }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
        public List<Post> Posts { get; set; }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }
```

Sample Data:

```C#
    var myBlog = new Blog { Url = "http://blogs.msdn.com/adonet" };
    var myFirstPost = new Post { Blog = myBlog, Title = "Title 1", Content = "Hello 1" };
    var mySecondPost = new Post { Blog = myBlog, Title = "Title 2", Content = "Hello 2" };
    var myBlogList = new List<Blog>();
    myBlogList.Add(myBlog);
    var myAuthor = new Author { Name = "Steven", Blogs = myBlogList };

    db.Authors.Add(myAuthor);
    db.Blogs.Add(myBlog);
    db.Posts.Add(myFirstPost);
    db.Posts.Add(mySecondPost);
    var count = db.SaveChanges();
```

Query:

```C#
    // query author
    var author = db.Authors.Include(x => x.Blogs).Where(x => x.Name.Equals("Steven")).Single();
    // query posts of author
    var postsOfAuthor = db.Posts.Where(x => author.Blogs.Contains(x.Blog));
    // next line....
    postsOfAuthor.ToList();
    // ...results in: Unhandled Exception: System.InvalidOperationException: No mapping to a relational type can be found for the CLR type 'Blog'

```

This was working perfectly in EF Core 1.1.

What happening is that db.Posts do not have the Blog as navigation property. Even when including Blogs like in the following line it is not working in EF Core 2.0.

```C#
var postsOfAuthor = db.Posts.Include(x => x.Blog).Where(x => author.Blogs.Contains(x.Blog));
```

```C#
Exception message: System.InvalidOperationException occurred
  HResult=0x80131509
  Message=No mapping to a relational type can be found for the CLR type 'Blog'.
  Source=Microsoft.EntityFrameworkCore.Relational
StackTrace:
   at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapperExtensions.GetMapping(IRelationalTypeMapper typeMapper, Type clrType)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.VisitConstant(ConstantExpression constantExpression)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.ProcessExpressionList[T](IReadOnlyList`1 items, Action`1 itemAction, Action`1 joinAction)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.ProcessExpressionList(IReadOnlyList`1 expressions, Action`1 joinAction)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.VisitIn(InExpression inExpression)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.GeneratePredicate(Expression predicate)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.GenerateSql(IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.GetRelationalCommand(IReadOnlyDictionary`2 parameters)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Tests.Program.Main(String[] args) in 
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio Enterprise 2017, version 15.3.5

**Comment by smitpatel** [comment] 2017-10-15 21:55
Possible duplicate of #9424

**Closed** 2017-10-17 19:24 UTC
Labels: closed-fixed, type-bug
