### ISSUE TITLE
SqlServer provider: unexpected command parameter dbtype for fixed length ansi strings 

### ISSUE THREAD

**Issue by elBranchi** [aspnet/EntityFrameworkCore#14555] opened 2019-01-30 12:42 UTC
The situation is the following:

We are currently working in a new application that has to use a database with a quite old design (lots of CHAR(n) columns, even for keys and FK's).

Recently, we noticed that we were having quite poor/slow performance when inserting new data in tables. 

After reviewing the resulting INSERT, we noticed that instead of using CHAR(n) parameters, VARCHAR(n) are used instead, that when used in a **sp_executesql** statement can result in bad performances.

Then we reviewed the model (generated via scaffolding), and we noticed that we had no **_.IsFixedLength()_** for the CHAR(n) properties/columns involved in the inserts (is the scaffolding doing the right thing here?).

Once corrected, we tried again, but the INSERT's were performing still bad, reviewing the newly generated statement, VARCHAR parameters are still being used.

After this, I have decided to dive into the code and I think that I might have found the reason of this behaviour, in **SqlServerStringTypeMapping** I have found the following:

```c#
public SqlServerStringTypeMapping(
    [CanBeNull] string storeType = null,
    bool unicode = false,
    int? size = null,
    bool fixedLength = false,
    StoreTypePostfix? storeTypePostfix = null)
    : this(
        new RelationalTypeMappingParameters(
            new CoreTypeMappingParameters(typeof(string)),
            storeType ?? GetStoreName(unicode, fixedLength),
            storeTypePostfix ?? StoreTypePostfix.Size,
            GetDbType(unicode, fixedLength),
            unicode,
            size,
            fixedLength))
{
}

private static string GetStoreName(bool unicode, bool fixedLength) => unicode
    ? fixedLength ? "nchar" : "nvarchar"
    : fixedLength
        ? "char"
        : "varchar";

private static DbType? GetDbType(bool unicode, bool fixedLength) => unicode
    ? (fixedLength ? System.Data.DbType.String : (DbType?)null)
    : System.Data.DbType.AnsiString;
```
The method **GetDbType** is unconditionally using _System.Data.DbType.AnsiString_ for non-unicode strings. Is there any reason why it shouldn't be using _System.Data.DbType.AnsiStringFixedLength_ for fixed length strings? 

In case that there is a good reason for this behaviour, is there any way to trigger the usage of CHAR(n) parameters instead of VARCHAR(n)?

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

**Comment by ajcvickers** [comment] 2019-01-30 20:44
Notes from triage: I believe we are not using the fixed length DbTypes because it causes SQLClient to pad the strings passed to it, which then causes issues. However, I can't find where we did this explicitly. @AndriySvyryd can you find anything?

**Comment by AndriySvyryd** [comment] 2019-01-31 19:50
@ajcvickers A test that show the failure that this would cause is `SimpleQueryTestBase.Comparing_to_fixed_string_parameter`:
```C#
from c in cs
where c.CustomerID.StartsWith(prefix)
select c.CustomerID;
```
`CustomerID` is mapped as `char(5)` if the value supplied in `prefix` is less than 5 characters it will be padded with whitespace and the query will return no results.

**Comment by ajcvickers** [comment] 2019-01-31 21:37
@elBranchi I believe you are hitting two issues here. The first looks like a duplicate of #14160, which is fixed for 3.0 already. The second is that the use of non-fixed length DbTypes is by design due to the padding that SqlClient does, which is a problem in scenarios like shown by @AndriySvyryd above. I doubt this is something we will change even though the perf characteristics are problematic. However, we will look into making it easier for an application to change the DbType if needed.

**Comment by elBranchi** [comment] 2019-01-31 23:51
So, if I understand it correctly, the scaffolding issue could be avoided/solved by switching to version 3.0.

On the other side, for the scenario shown in the test I assume that problem would result by using a CHAR(5) parameter for prefix? Is there any reason that prevents from adjusting the size of the parameter to match the real length of the string in case of using fixed strings? 

Just wondering.

**Comment by AndriySvyryd** [comment] 2019-02-01 00:03
@elBranchi Currently our mapping doesn't depend on the values, it would require significant infrastructure changes. Also in general we try to use the same type of paramaters for the same query to avoid cache fragmentation.

**Comment by elBranchi** [comment] 2019-02-01 06:59
@AndriySvyryd that's more or less the answer that I was fearing/expecting and that also makes a lot of sense :-\
In this case, the only thing remaining I imagine that would be devising/designing the mechanism that would allow the applications to tell EFC that certain DbTypes are to be used instead of the selected by the model.
In any case it would need to be appliable to queries and also insert/updates, so I don't have a clear picture of how I would include such feature in a clean and consistent way. One way would be enabling the change in the model, and the other would be applying some modification on an operation by operation basis.

**Comment by ajcvickers** [comment] 2019-02-01 17:53
@AndriySvyryd We already [configure the parameter Size differently based on the length of the string](https://github.com/aspnet/EntityFrameworkCore/blob/master/src/EFCore.SqlServer/Storage/Internal/SqlServerStringTypeMapping.cs#L86). Maybe if the mapping is for fixed length, the length is specified, and the size of the string matches the length, then we can set the DbType to fixed. Thoughts?

**Comment by AndriySvyryd** [comment] 2019-02-01 19:33
@ajcvickers Good idea, we can actually set `DbType` to fixed and adjust `Size` to match the string length, this avoids padding.

**Comment by elBranchi** [comment] 2019-02-01 21:36
@ajcvickers @AndriySvyryd 
Ok, this starts to sound really good me, it will make happy my colleagues also.
I'm already planning on trying the 3.0 preview on a different branch, and having this change on either 2.2.x or a later 3.0 preview would be perfect.

**Comment by ajcvickers** [comment] 2019-02-02 21:41
@ErikEJ Yes, but only if using fixed-length types with variable length strings, which seems like a reasonable compromise to make.

**Comment by divega** [comment] 2019-02-04 06:21
Clearing up to look at it again in triage. 

I am just wondering if we can fix the inference code to copy the fixed length facet (and let the padding happen), but only for certain operations like comparison and assignment. That should help with cases like SimpleQueryTestBase.Comparing_to_fixed_string_parameter (in which we are inferring the facees for the argument of a function) without introducing cache pollution. 

BTW, re the current proposal, I am not sure that operations between fixed length parameters and fixed length columns when the length is different perform better than between variable length and fixed length (maybe this is something that we can test). 

> @ErikEJ Yes, but only if using fixed-length types with variable length strings, which seems like a reasonable compromise to make.

Maybe I am missing something, but that sounds pretty much any time we use string parameters with fixed length string columns, and that seems a lot.

**Closed** 2019-12-30 22:14 UTC
Labels: closed-fixed, customer-reported, punted-for-3.0, type-bug

**Comment by wdnijdam** [comment] 2020-01-14 11:53
See #19579: a work around is to use 

.FromSql("select * from [tablename]")
.Where(condition on char column)

In this case EF core generates a query with a local variable using limited length and the index is used.
