### ISSUE TITLE
Scaffolding broken for nvarchar(4000)

### ISSUE THREAD

**Issue by mfields3** [aspnet/EntityFrameworkCore#9188] opened 2017-07-17 16:20 UTC
When using SQL Server and a table has a column type of nvarchar(4000) (which is the maximum), the scaffolding outputs .HasColumnType("nvarchar"). This causes an exception when accessing the context for the model.

Believe it's a bug in the scaffolding code. 

```
Exception message: System.ArgumentException: Data type 'nvarchar' is not supported in this form. Either specify the length explicitly in the type name, for example as 'nvarchar(16)', or remove the data type and use APIs such as HasMaxLength to allow EF choose the data type. 
Stack trace: at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerTypeMapper.ValidateTypeName(String storeType)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateDataTypes(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__0(Object k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
```

Thrown on line 236 at https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.SqlServer/Storage/Internal/SqlServerTypeMapper.cs
This is because the HasColumnType is set to nvarchar which is in the _disallowedMappings HashSet.

### Steps to reproduce
Create a new database containing a single table. Ensure there is a nvarchar(4000) column.
Scaffold the dbContext and create a controller/view and try and load the page.
The following should be scaffolded:
```c#
entity.Property(e => e.Notes)
                    .HasColumnName("notes")
                    .HasColumnType("nvarchar");
```

The issue appears to be `GetStoreType` in _EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs_ where it is not returning "nvarchar(max)" because the `maxLength` parameter isn't set to -1.

### Further technical details
EF Core version: 2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: W10
IDE:Visual Studio 2017 Preview 2

**Comment by smitpatel** [comment] 2017-07-17 17:42
`nvarchar(4000)` is different from `nvarchar(max)` (difference of 1).
SQL Server shows weird behavior for max_length for that specific type (or similar types almost at the max).

| Type | max_length value |
|-------|--------------------|
| nvarchar(200)|400|
|nvarchar(4000)|NULL|
|nvarchar(max)|-1|

We should report this to SQL Server team. Meanwhile we can handle this case specifically depending on timeline of former.

**Comment by mfields3** [comment] 2017-07-17 19:37
That isn't an issue with SQL Server. Written in the scaffolding is some raw SQL which returns the data you've shared in the above table. There is a check to see if the size of the field is equal to maximum size of that type of field and if so, return NULL. Therefore perhaps that should be changed to return -1 if that's what the code expects?

**Comment by ErikEJ** [comment] 2017-07-18 05:41
Look at: https://github.com/aspnet/EntityFramework/blob/dev/src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs#L365

**Comment by mfields3** [comment] 2017-07-18 06:59
^^ Exactly. Should that therefore be returning -1 instead of NULL?

**Comment by ErikEJ** [comment] 2017-07-18 07:08
@mfields3  It should actually return 8000 for nvarchar(4000) !

https://docs.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql

**Comment by mfields3** [comment] 2017-07-18 10:41
@ErikEJ It does return 8000, yet whoever wrote this CASE statement as part of scaffolding decided that when the length is equal to the maximum length of the field to return NULL.

Yet I believe as far as EF Core is concerned, the length of the string should be 4000, not 8000 nor MAX.
nvarchar(max) allows 2 GB. Yet the field is defined as nvarchar(4000) which uses 8000 bytes, yet has a max length of 4000.

**Comment by smitpatel** [comment] 2017-07-18 16:27
The case statement is incorrect. It should return 8000. There seem to be no usefuleness of nulling out when length is maximum. When its `type(max)` SqlServer will return -1 anyway. I will make the change when I will get time to fix the issue.

**Comment by Lave4269** [comment] 2017-08-15 20:00
Scaffolding is also broken for varchar(8000) for I'm guessing is the same problem as above.

**Comment by ADefWebserver** [comment] 2017-08-26 02:06
If you are stuck (as I was) you can use [SQLite / SQL Server Compact Toolbox ](https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox) to scaffold your tables.

**Comment by JuanIrigoyen** [comment] 2017-08-30 00:08
I have the same problem with fields with different lengths nvarchar(100), nvarchar(50) and the error is in runtime. When will be the new version that fixes this issue?

**Comment by ajcvickers** [comment] 2017-08-30 17:43
@JuanIrigoyen The runtime isn't going to change. If you want to specify the store type abstractly, including the size, unicode, etc., then do so using the appropriate APIs/attributes (e.g. MaxLength, IsUnicode) and don't specify any explicit store type. If you want to specify an explicit store type, then do it fully, including the size.

**Comment by Gaelmart** [comment] 2017-08-31 00:01
Could some give actual example of what to  do  here:
 entity.Property(e => e.Sessionid)
                    .IsRequired()
                    .HasColumnName("sessionid")
                    .HasMaxLength(100)
                    .IsUnicode(false);

**Comment by ajcvickers** [comment] 2017-08-31 00:03
@Gaelmart That code looks right to me. Is it doing something unexpected?

**Comment by AxelAndersen** [comment] 2017-09-22 17:17
I think it is unexpected that the autogenerated code fails like that, so yes!

When i create my models like this:
Scaffold-DbContext "Server=(local);Database=MyDB;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models

this is what i get in one of the fields:

entity.Property(e => e.Text)
                    .IsRequired()
                    .HasColumnType("nvarchar");

and when running the code I get this error:
Data type 'nvarchar' is not supported in this form. Either specify the length explicitly in the type name, for example as 'nvarchar(16)', or remove the data type and use APIs such as HasMaxLength to allow EF choose the data type.

So there must be an error in the scaffolding.
This code and database worked before 2.0

**Comment by RCVarley** [comment] 2017-09-24 20:03
I'm getting this same error when trying to build a Controller by scaffolding in EF Core 2.0.  Oddly, the model that I'm referencing in the wizard was generated from a database in as per a [tutorial](https://docs.microsoft.com/en-gb/ef/core/get-started/aspnetcore/existing-db) in MS Docs.  The difference being that I'm using AdventureWorksLT, an example DB made available in Azure.

I'm wondering if it's the User Defined Data Types causing the issue.  Specifically Name:nvarchar(50).

Output
```
Finding the generator 'controller'...
Running the generator 'controller'...
Attempting to compile the application in memory.
Attempting to figure out the EntityFramework metadata for the model and DbContext: 'Customer'
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\Ryan Varley\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Data type 'nvarchar' is not supported in this form. Either specify the length explicitly in the type name, for example as 'nvarchar(16)', or remove the data type and use APIs such as HasMaxLength to allow EF choose the data type. StackTrace:
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerTypeMapper.ValidateTypeName(String storeType)
Data type 'nvarchar' is not supported in this form. Either specify the length explicitly in the type name, for example as 'nvarchar(16)', or remove the data type and use APIs such as HasMaxLength to allow EF choose the data type.   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateDataTypes(IModel model)

   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__0(Object k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass22_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.VisualStudio.Web.CodeGeneration.EntityFrameworkCore.EntityFrameworkServices.TryCreateContextUsingAppCode(Type dbContextType, Type startupType)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
```

TableSQL
```
CREATE TABLE [SalesLT].[Product](
	[ProductID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [dbo].[Name] NOT NULL,
	[ProductNumber] [nvarchar](25) NOT NULL,
	[Color] [nvarchar](15) NULL,
	[StandardCost] [money] NOT NULL,
	[ListPrice] [money] NOT NULL,
	[Size] [nvarchar](5) NULL,
	[Weight] [decimal](8, 2) NULL,
	[ProductCategoryID] [int] NULL,
	[ProductModelID] [int] NULL,
	[SellStartDate] [datetime] NOT NULL,
	[SellEndDate] [datetime] NULL,
	[DiscontinuedDate] [datetime] NULL,
	[ThumbNailPhoto] [varbinary](max) NULL,
	[ThumbnailPhotoFileName] [nvarchar](50) NULL,
	[rowguid] [uniqueidentifier] NOT NULL,
	[ModifiedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Product_ProductID] PRIMARY KEY CLUSTERED 
(
	[ProductID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF),
 CONSTRAINT [AK_Product_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF),
 CONSTRAINT [AK_Product_ProductNumber] UNIQUE NONCLUSTERED 
(
	[ProductNumber] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF),
 CONSTRAINT [AK_Product_rowguid] UNIQUE NONCLUSTERED 
(
	[rowguid] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF)
)
GO
```

**Comment by jvelezc** [comment] 2017-09-27 00:46
I am getting the same error but for varchar(MAX) and varchar(4000) and VARCHAR(8000).

**Comment by AxelAndersen** [comment] 2017-09-27 04:54
Exactly what i experienced, there is for sure a bug in the scaffolding tool, or the EF Core

**Comment by ajcvickers** [comment] 2017-09-29 16:45
Marking for re-triage

**Comment by RCVarley** [comment] 2017-09-29 17:10
Sorry for the slow response.  It turns out that my particular issue was a result of (hangs head in shame) a stray nvarchar value in my DbContext class, which has already been reported and addressed.  Fortunately I can confirm that the Alias didn't screw anything up.

**Comment by ErikEJ** [comment] 2017-10-04 05:26
@ajcvickers Is this being reconsidered for 2.0.1 ?

**Comment by MrBirdman** [comment] 2017-10-04 10:58
Is there maybe a workaround for this?

**Comment by ErikEJ** [comment] 2017-10-04 11:21
@MrBirdman I will consider a fix for EF Core Power Tools - does a replace of "nvarchar" => nvarchar(4000)" work for you?

**Comment by MrBirdman** [comment] 2017-10-04 11:45
What about when we input more than 4000 characters?

**Comment by MrBirdman** [comment] 2017-10-04 11:46
@ErikEJ yeah it might work for a while, i've used your tool to generate the context but it came out the same so i dropped it :)

**Comment by ErikEJ** [comment] 2017-10-04 12:05
@MrBirdman Fixed in the latest daily release, pls try it out and let me know if it solves your problem, then I will publish the fix on VS Marketplace - https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools

**Comment by MrBirdman** [comment] 2017-10-04 12:15
@ErikEJ I'm getting a "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." message when i try to download SQLite / SQL Server Compact Toolbox v4.7.384

**Comment by ErikEJ** [comment] 2017-10-04 12:34
@MrBirdman  This link works for me: http://vsixgallery.com/extensions/f4c4712c-ceae-4803-8e52-0e2049d5de9f/extension.vsix

**Comment by MrBirdman** [comment] 2017-10-04 12:59
Actually i'm not sure this has done anything:
https://s1.postimg.org/1v7mlicdot/image.png

**Comment by ErikEJ** [comment] 2017-10-04 13:02
Do not see anything relating to nvarchar on that screenshot. What is the runtime error you get?

**Comment by MrBirdman** [comment] 2017-10-04 13:05
The left side is generated with EF, while the right side is with the toolbox. This table has several varchar(max) and nvarchar(max) columns, and it doesn't add or change anything to the model.

**Comment by ErikEJ** [comment] 2017-10-04 13:11
@MrBirdman  Do not use the Toolbox, use EF Core Power Tools (as per my wiki and direct link above)! Again, what runtime error do you get?

**Comment by ajcvickers** [comment] 2017-10-04 16:25
@ErikEJ We're going to discuss it, but no promises yet. Even if the team decides that it meets the bar, it will still need to go through patch approval before we will know for sure.

**Comment by ajcvickers** [comment] 2017-10-04 20:02
Triage: we're going to try to get this fix into 2.0.1. See #9963.

**Closed by ajcvickers** 2017-10-04 20:02 UTC
Labels: closed-fixed, type-bug

**Comment by gate21** [comment] 2018-02-15 17:27
I am getting 'varchar is not supported' when connecting to sql 2008 r2.  I have tried all the suggestions above; any ideas.

**Comment by ErikEJ** [comment] 2018-02-15 18:03
@gate21 replace "varchar" with "varchar(4000)" in the generated code... Or use EF Core Power Tools

**Comment by gate21** [comment] 2018-02-15 18:09
I am using Code first.
I have tried "varchar(xxx)", HasMaxLength(xxx), HasColumnType("varchar").HasMaxLength(maxLength)...
I noticed when connecting to a Sql azure db for another project I do not have an issue, but when I connect to SQL 2008 R2 I get the issue.

**Comment by ErikEJ** [comment] 2018-02-15 18:15
Have you tried  : ?

   HasColumnType("varchar(4000)")

**Comment by gate21** [comment] 2018-02-15 18:26
yes I have.

**Comment by ajcvickers** [comment] 2018-02-15 20:43
@gate21 Please file a new issue including a runnable project/solution or complete code listing that demonstrates the behavior you are seeing so that we can investigate.

**Comment by gate21** [comment] 2018-02-15 21:10
Guys thanks for your help.

While trying to debug the issue I was having, I left the RegisterConfigurationFromAssembly code in place "this was picking up other configuration that I have not fixed".  Once I saw that removed it and registered the congifurationObject I was debugging "varchar(xxx)" did fix the issue."

Regards
