### ISSUE TITLE
Broken tests: Create_checks_for_existence_and_ultimately_gives_up_waiting et al

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/EntityFrameworkCore#12706] opened 2018-07-18 18:45 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=507760&buildTypeId=XPlat_Windows_Win8_Universe) occasionally with the following error:
```
Assert.Throws() Failure
Expected: typeof(System.Data.SqlClient.SqlException)
Actual:   typeof(System.ArgumentException): Keyword not supported: 'PoolBlockingPeriod'.
   at System.Data.SqlClient.SqlConnectionStringBuilder.Reset(Keywords index)
   at System.Data.SqlClient.SqlConnectionStringBuilder.Clear()
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.CreateCreateOperations() in /_/src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs:line 110
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Create() in /_/src/EFCore.SqlServer/Storage/Internal/SqlServerDatabaseCreator.cs:line 61
```

**Comment by smitpatel** [comment] 2018-07-18 18:49
Just need to wait for SqlClient dependency to update with appropriate version.

**Comment by Eilon** [comment] 2018-07-18 20:36
Thanks @smitpatel . I'm assigning to you so that you can close once we have a build where this is fixed.

**Comment by AfsanehR** [comment] 2018-07-19 22:38
@ryanbrandenburg I am unable to open the CI log you posted. Which branch are those tests running against? 
@Eilon @smitpatel  Reason I am asking is that I had a quick look, the PoolBlockingPeriod feature is not present in UWP6.1, It was merged in master branch, so not sure why it is picking it up in the first place.

**Comment by ryanbrandenburg** [comment] 2018-07-19 23:17
Yeah, the link above is to an internal build system, so it won't be visible. The branch the failure targeted was master. I'll make a note to have my script start including that information in the post.

**Comment by ryanbrandenburg** [comment] 2018-07-24 23:33
CreateAsync_checks_for_existence_and_ultimately_gives_up_waiting [failed again](http://aspnetci/viewLog.html?buildId=513798&buildTypeId=XPlat_Windows_Win10Universe).

**Comment by smitpatel** [comment] 2018-07-24 23:36
I have added comment asking for more details at https://github.com/dotnet/corefx/issues/30720
But there may be bigger issue here.
The packages being used on master branch which are compiled for .NET Core are adding new APIs. Since its a major version release, they are adding new APIs which are not available/compiled on netcoreapp2.0. It may be possibility that the master branch packages of corefx cannot run against netcoreapp2.x anymore and we may need to remove those tfm from testing.

**Comment by ryanbrandenburg** [comment] 2018-07-24 23:38
Create_checks_for_existence_and_ultimately_gives_up_waiting [failed again](http://aspnetci/viewLog.html?buildId=513800&buildTypeId=XPlat_Windows_Win7_Universe).

**Comment by ryanbrandenburg** [comment] 2018-07-24 23:43
Create_checks_for_existence_and_ultimately_gives_up_waiting [failed again](http://aspnetci/viewLog.html?buildId=513794&buildTypeId=XPlat_Windows_Win8_Universe).

**Comment by ryanbrandenburg** [comment] 2018-07-24 23:48
Create_checks_for_existence_and_ultimately_gives_up_waiting [failed again](http://aspnetci/viewLog.html?buildId=513790&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

**Comment by ryanbrandenburg** [comment] 2018-07-24 23:52
Create_checks_for_existence_and_ultimately_gives_up_waiting [failed again](http://aspnetci/viewLog.html?buildId=513788&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

**Comment by Eilon** [comment] 2018-07-25 20:12
Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)


@smitpatel - can you please update the TODO's/checkboxes workflow above with the current state of this flaky test investigation?

**Closed** 2018-07-25 22:37 UTC
Labels: area-test, closed-fixed
