### ISSUE TITLE
Max causes QueryClientEvaluationWarning

### ISSUE THREAD

**Issue by slubowsky** [aspnet/EntityFrameworkCore#9726] opened 2017-09-07 20:52 UTC
Using Max in a Linq query causes QueryClientEvaluationWarning to be thrown but if not configured to throw on this warning then looking at the generated SQL I can see that the Max is actually done on the server, not on the client.

My code:
```
await context.People.Where(a => a.CompanyId == companyId).MaxAsync(or => or.SystemNumber)
```
The generated SQL (seen in log and profiler) when not throwing on warning:
```
SELECT MAX([a].[SystemNumber])
FROM [People] AS [a]
WHERE [a].[CompanyId] = @__companyId_0
```

Exception message when configured to throw on warning:
`Warning as error exception for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning': The LINQ expression 'Max()' could not be translated and will be evaluated locally. To suppress this Exception use the DbContextOptionsBuilder.ConfigureWarnings API. ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.`

### Further technical details
EF Core version: 2.0.0 (and latest 2.1.0 preview)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: e.g. Visual Studio 2017

**Comment by smitpatel** [comment] 2017-09-07 22:20
Duplicate of #9516

**Comment by anpete** [comment] 2017-09-08 16:44
It looks like we are incorrectly producing the client-eval warning in this case. We are setting RequiresClientResultOperator = true, which causes the warning to be generated. We need to set that flag sometimes, but probably don't for a top-level query.

**Closed** 2018-01-24 22:00 UTC
Labels: type-bug
