### ISSUE TITLE
Problem with dotnet cli ef tools after upgrading to vs 2017 15.4.4 and november .net core rollup 

### ISSUE THREAD

**Issue by spnm** [aspnet/EntityFrameworkCore#10298] opened 2017-11-15 14:58 UTC
Not sure if its an EFCore issue or cli

#  Steps to reproduce
Using Visual Studio Enterprise 2017 (v 15.4.4)
# Add migration
dotnet ef migrations add [MigrationName]
# Expected behavior
Migration created

# Actual behavior
Error message :
The specified framework version '2.0' could not be parsed
The specified framework 'Microsoft.NETCore.App', version '2.0' was not found.
Check application dependencies and target a framework version installed at:
\\
Alternatively, install the framework version '2.0'.

My project is a console library and the content of .csproj file is below:
``` csproj
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Reflection.Metadata" Version="1.5.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.1" PrivateAssets="All" />
  </ItemGroup>
  
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
  </ItemGroup>
</Project>
```

So i tried to use global.json in the root of my project  : 
```
{
  "sdk": {
    "version": "2.0.3"
  }
}

```

and the error was the same.
But when I changed global.json content to this :

```
{
  "sdk": {
    "version": "2.0.2"
  }
}

```
It worked.

**Comment by dalibor983** [comment] 2017-11-15 15:59
I have the same problem.

**Comment by marcwmiller** [comment] 2017-11-15 18:36
I have same issue.

**Comment by lccarvalho** [comment] 2017-11-15 21:06
Scaffold-DbContext fails silently after that same upgrade to VS 15.4.4

**Comment by Wind010** [comment] 2017-11-16 01:59
I have the same predicament.

**Comment by alexzaytsev-newsroomly** [comment] 2017-11-16 02:05
Can confirm that 2.0.2 workaround works. Not really clear why.

**Comment by jorgeyanesdiez** [comment] 2017-11-16 11:35
I get exactly the same problem with `dotnet xunit`, and probably all other dotnet commands are affected.
Lets hope this gets fixed soon.

**Comment by jorgeyanesdiez** [comment] 2017-11-16 11:53
This is probably a dupe of https://github.com/dotnet/cli/issues/7901

**Comment by ajcvickers** [comment] 2017-11-16 18:10
@Eilon @natemcmaster @livarcocc Any ideas on this?

**Comment by livarcocc** [comment] 2017-11-16 18:14
I have been trying to repro this for a while now without much success, but this does seem like a CLI problem.

**Comment by livarcocc** [comment] 2017-11-16 18:54
This is a CLI/SDK bug that we now understand. I am duping this one to the one in the CLI: https://github.com/dotnet/cli/issues/7901

We will explain it there why this happens and a workaround and we are figuring out the vehicle to carry a fix for this.

@ajcvickers can you close this bug?

**Comment by ajcvickers** [comment] 2017-11-16 18:54
Thanks @livarcocc. Closing.

**Comment by bricelam** [comment] 2017-11-16 23:55
Re-opening since it looks like there's work to do on our side too.

**Comment by heku** [comment] 2017-11-17 11:47
The suggestion in comments don't work for `netstandard2.0` project like below. 

Windows 10 + VS 2017 15.4.4 + NetCore 2.0.3 SDK

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
  </ItemGroup>

</Project>
```

**Comment by lccarvalho** [comment] 2017-11-17 11:50
Neither for the 'Scaffold-DbContext' problem in a netcoreapp2.0 project

**Comment by marcwmiller** [comment] 2017-11-17 14:48
I used the project config below, and it resolved the issue in my environment (Windows 10 + VS 2017 15.4.4 NetCore 2.0.3 SDK) for 'Scaffold-DbContext'

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.3</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />
  </ItemGroup>
</Project>
```

**Comment by ajcvickers** [comment] 2017-11-17 17:24
@lccarvalho This sounds like it could be a different issue. Can you please file a new issue including a sample project that reproduces what you are seeing?

@heku .NET Standard class libraries are not supported directly by the EF tooling. You will need to target an actual framework (e.g. netcoreapp2.0) or specify a startup project that targets a framework. This issue is not about that, but about using a class library that targets on netcoreapp when there is no usable startup project.

**Comment by bricelam** [comment] 2017-11-17 22:55
I've filed #10338 to improve the silently failing PMC commands.

**Comment by bricelam** [comment] 2017-11-17 23:28
Workaround
===
Adding the following to the project should also make it work.
``` xml
<PropertyGroup>
  <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
</PropertyGroup>
```

**Comment by lccarvalho** [comment] 2017-11-18 00:01
Tks, @bricelam, can confirm that your workaround works. @ajcvickers: will file new issue with sample project during weekend, please let me know if it is not necessary anymore.

**Comment by heku** [comment] 2017-11-18 07:19
@ajcvickers 
>@heku .NET Standard class libraries are not supported directly by the EF tooling. You will need to target an actual framework (e.g. netcoreapp2.0) or specify a startup project that targets a framework. This issue is not about that, but about using a class library that targets on netcoreapp when there is no usable startup project.

Thanks for response. I specified the startup project indeed，but didn't wok. I open another issue #10342 to describe my problem in detail.

**Comment by lccarvalho** [comment] 2017-11-18 16:51
@ajcvickers no need for a new issue, with help of the messages I could see that there was an error on my Scaffold command, everything works fine for me now

**Comment by Eilon** [comment] 2017-12-01 01:07
Keeping the issue open for tracking purposes.

**Comment by 68681395** [comment] 2017-12-12 03:44
There is the same problem with my project, the workaround to resolve it successfully is that remove the item 'C:\Program Files (x86)\dotnet' from the Path of Environment Variable because I found I did not install the right netcore version under X86.  I have not tried to install the proper version with x86,  appreciate that you tell me if you have done that test.

**Comment by Eilon** [comment] 2018-01-17 18:28
This patch is **approved** for the Feb 2018 patch. Please send a PR to the appropriate branch, get it reviewed, and merge.

Please consider adding a [quirks-mode switch](https://github.com/aspnet/Home/wiki/Quirks-mode-switches-in-patches) for this change.

**Comment by ivanov961** [comment] 2018-01-20 19:53
I found out that the dotnet cli commands can't run from ClassLibraries it needs .exe in order to execute the command. So I fixed my problem by adding new .netCoreConsoleApp then I've added my ClassLibraries as references to the ConsoleApp. Then run the command [dotnet ef --startup-project ../CoreUI migrations add init ] but failed with that Microsoft.EntityFrameworkCore.Design is required in order to execute the command I did it. And it worket

**Closed** 2018-01-22 22:49 UTC
Labels: closed-fixed, patch-approved, type-bug

**Comment by gitfortee** [comment] 2018-01-30 14:55
@bricelam your workaround([link](https://github.com/aspnet/EntityFrameworkCore/issues/10298#issuecomment-345393326)) has fixed the same kind of error i got. 

Could you please help me understand what this setting does? could you provide some details on how it fixes the issue?

**Comment by bricelam** [comment] 2018-01-30 17:17
`GenerateRuntimeConfigurationFiles` forces an `*.runtimeconfig.json` file to be generated for the project. The file looks like this:
``` json
{
  "runtimeOptions": {
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "2.0.0"
    }
  }
}
```
This tells `dotnet` to execute the code using a version of .NET Core compatible with version `2.0.0`.

Without the file, EF Tools pass `--fx-version 2.0` to `dotnet` which forces it to run on .NET Core `2.0`, but since it's missing a digit, it can't find it.

**Comment by bricelam** [comment] 2018-01-30 17:20
Setting `RuntimeFrameworkVersion` (as suggested by @Wind010) changes the value we pass to `--fx-version`. This will work; however, it means your app may require .NET Core version 2.0.3, so if you publish it to a server that only has version 2.0.0, it may fail.

**Comment by gitfortee** [comment] 2018-01-30 17:54
Never mind. I believe i found the answer.. it works because of [this](https://github.com/dotnet/cli/issues/7901#issuecomment-345033407) ??

**Comment by gitfortee** [comment] 2018-01-30 17:56
thanks!

**Comment by cgountanis** [comment] 2018-02-27 23:17
Still getting this error via Core 2.1.4 SDK within ClassLibrary. When will we be able to add EF to these using NUGET vs. manually as well (<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />)...

>dotnet ef migrations add InitialCreate
The specified framework version '2.0' could not be parsed
The specified framework 'Microsoft.NETCore.App', version '2.0' was not found.
  - Check application dependencies and target a framework version installed at:  \
  - Alternatively, install the framework version '2.0'.

**Comment by alexzaytsev-newsroomly** [comment] 2018-02-28 00:42
@cgountanis i still use the `global.json` workaround. but yeah, it is mighty annoying.

**Comment by ajcvickers** [comment] 2018-02-28 21:17
@cgountanis Unfortunately, the patch containing this fix has not yet been released. Release dates for patches is not something the EF team can influence very much, and there have been various reasons for delaying the patch release that are outside our control. I realize that this is frustrating and I apologize for that. We are, across .NET Core, working on making this process better, so hopefully it won't be such an issue going forward.

**Comment by cgountanis** [comment] 2018-02-28 21:57
Sounds good, will that fix the error when adding the tools via NUGET as well. Right now we have to add that line manually to do migrations etc...

`<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.1" />`

**Comment by ajcvickers** [comment] 2018-02-28 22:02
@cgountanis No, that's a separate NuGet issue, tracked here: https://github.com/NuGet/Home/issues/4190
