### ISSUE TITLE
Insert throws ArgumentNullException when Entity is referenced by DbQuery object

### ISSUE THREAD

**Issue by Kloizdena** [aspnet/EntityFrameworkCore#14226] opened 2018-12-21 15:40 UTC
I have an issue inserting multiple entities to the Database when there is a reference to one of the entities from a DbQuery.

```
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.FindIdentityMap(IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetDependents(InternalEntityEntry principalEntry, IForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 containingPrincipalKeys, IReadOnlyList`1 containingForeignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 keys, IReadOnlyList`1 foreignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean setModified)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.PropagateResults(ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(DbContext _, ValueTuple`2 parameters, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IReadOnlyList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Program.Main(String[] args) in D:\Dev\Test\EFBug\EFBug\Program.cs:line 19
   at Program.<Main>(String[] args)
```

### Steps to reproduce

```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

internal class Program
{
    private static async Task Main(string[] args)
    {
        using (var context = new MyContext())
        {
            await context.Database.EnsureCreatedAsync();
            context.Bs.Add(new B
            {
                Value = "B Value",
                A = new A { Value = "A Value" },
                Cs = { new C { Value = "C Value" } }
            });
            await context.SaveChangesAsync();
        }
        Console.ReadLine();
    }
}

public class MyContext : DbContext
{
    public virtual DbSet<B> As { get; set; }
    public virtual DbSet<B> Bs { get; set; }
    public virtual DbSet<C> Cs { get; set; }
    public virtual DbQuery<MyView> MyView { get; set; }

    public MyContext() : base(new DbContextOptionsBuilder<MyContext>()
            .UseSqlServer("Data Source=.;Initial Catalog=Test;Integrated Security=True")
            .Options)
    {

    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Query<MyView>().ToView("MyView", "dbo");
    }
}

public class A
{
    public int Id { get; set; }
    public string Value { get; set; }
    public virtual ICollection<B> Bs { get; set; } = new HashSet<B>();
}
public class B
{
    public int Id { get; set; }
    public string Value { get; set; }
    public int AId { get; set; }
    public virtual A A { get; set; }
    public virtual ICollection<C> Cs { get; set; } = new HashSet<C>();
}
public class C
{
    public int Id { get; set; }
    public string Value { get; set; }
    public int BId { get; set; }
    public virtual B B { get; set; }
}

public class MyView
{
    public int BId { get; set; }
    public virtual B B { get; set; }
}

```

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.9.4

**Comment by smitpatel** [comment] 2018-12-21 20:05
Regression introduced by https://github.com/aspnet/EntityFrameworkCore/pull/13468
There are few more places where we need to ignore FK on QueryType inside NavigationFixer.
Superseded by #14194 in 3.0

**Comment by michaelkargl** [comment] 2019-01-07 11:17
We just ran into this bug in one of our customer projects and are eagerly trying to figure out what exactly the problem is and how to work around it until this issue is closed. Unfortunately I can not really make sense of the linked Issues and PRs. Can someone be so kind and explain briefly how this is caused or why it is happening in 2.2 and not in 2.1? 😄

**Comment by Kloizdena** [comment] 2019-01-07 11:56
@michaelkargl I solved this by removing the navigation properties from the DbQuery class. The navigation property was used in a query, so I had to replace the navigation with a Join:
```c#
// original:
var query = context.MyView.Where(...).Select(v => v.B);
// modified:
var query = context.MyView.Where(...).Join(context.Bs, v => v.BId, b => b.Id, (v, b) => b);
```

**Comment by michaelkargl** [comment] 2019-01-07 14:33
> 
> 
> @michaelkargl I solved this by removing the navigation properties from the DbQuery class. The navigation property was used in a query, so I had to replace the navigation with a Join:
> 
> ```cs
> // original:
> var query = context.MyView.Where(...).Select(v => v.B);
> // modified:
> var query = context.MyView.Where(...).Join(context.Bs, v => v.BId, b => b.Id, (v, b) => b);
> ```

Thank you for the quick response. The problem is that we are not using any Select or Where clauses in our code, rather constructing an entity, adding it to the context and flushing with SaveChanges().

We are having a simple DataImport table/entity with Rows and Columns getting created in one swoop.
```csharp
public class DataImport {
    public long Id { get; set; }
    public IList<DataImportColumn> UsedColumns { get; set; }
    public IList<DataImportRow> Rows { get; set; }
}

// ... DataImportRow/Column with navigation properties back to the DataImport

var dataImport = new DataImport {
   Columns = ParseColumns(file); 
   Rows = ParseRows(file);
}

_context.DataImport.Add(dataImport);
_context.SaveChanges();
```

Where in this scenario is the breaking code?
Or asked from a different angle, what caused your ```csharp context.MyView.Where(...).Select(v => v.B); ``` to bork?

**Comment by michaelkargl** [comment] 2019-01-07 16:10
> 
> 
> @michaelkargl I solved this by removing the navigation properties from the DbQuery class. The navigation property was used in a query, so I had to replace the navigation with a Join:
> 
> ```cs
> // original:
> var query = context.MyView.Where(...).Select(v => v.B);
> // modified:
> var query = context.MyView.Where(...).Join(context.Bs, v => v.BId, b => b.Id, (v, b) => b);
> ```

You sur, are a master. Someone put a view in the middle of our Context. 
Marking the views' navigation-property as [NotMapped] worked for us.

```csharp
public class DataImportRowData {
        public long DataImportId { get; set; }

        [NotMapped]
        public DataImport DataImport { get; set; }

        // ...
```

**Comment by ilmax** [comment] 2019-01-17 13:06
Same here, removing navigation properties from the view fixed the problem.
Any chance to get this fixed in 2.2.2?

**Comment by gbiellem** [comment] 2019-01-21 06:14
I also hit this.  Thanks @Kloizdena  for the workaround

**Comment by MCFHTAGENTS** [comment] 2019-01-31 19:16
Is there any form of workaround to this other than removing the navigation properties - it happens in my data migration loader where I am iterating a SQLReader to move data into my EF managed tables. I really don't want to drop navigation properties across the project!

**Comment by Kloizdena** [comment] 2019-02-01 02:03
@MCFHTAGENTS saving the entities in two turns also worked for me:
```c#
            var b = new B
            {
                Value = "B Value",
                A = new A { Value = "A Value" },
            };
            context.Bs.Add(b);
            await context.SaveChangesAsync();
            context.Cs.Add(new C { Value = "C Value", B = b });
            await context.SaveChangesAsync();
```
instead of the original:
```c#
            context.Bs.Add(new B
            {
                Value = "B Value",
                A = new A { Value = "A Value" },
                Cs = { new C { Value = "C Value" } }
            });
            await context.SaveChangesAsync();
```

**Comment by MCFHTAGENTS** [comment] 2019-02-01 07:07
Hmmm
I have the situation where I have three tiers of nested objects
```class A
{
[Key]
public int AId {get; set;}

public ICollection<B> {get; set;}
}

public class B
{
[Key]
public int BId {get; set;}

[ForeignKey("AId")]
public A A {get; set;}
public int AId {get; set;}

public ICollection<C> {get; set;}
}

public class C
{
public int CId {get; set;}

[ForeignKey("BId")]
public B B {get; set;}

public int BId {get; set;}}
```

I read in the data from another SQL source with a pattern like this:
```
List<X> newX = new List<X>();
while(reader.HasRead())
{
   var X = X(){ 
};
  newX.Add(X);
}
foreach(var Item in newX) {context.X.Add(Item)}
context.SaveChanges()
```
I find that when X is an A it works fine. In the B case the constructor includes a reference to A. I have tried both setting the 
when X is a B it crashes out.

**Comment by MCFHTAGENTS** [comment] 2019-02-13 07:54
Hi there, I have just updated to 2.2.104 and am still seeing this:
` System.ArgumentNullException: Value cannot be null.
Parameter name: key
  at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.FindIdentityMap(IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetDependents(InternalEntityEntry principalEntry, IForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 containingPrincipalKeys, IReadOnlyList`1 containingForeignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.KeyPropertyChanged(InternalEntityEntry entry, IProperty property, IReadOnlyList`1 keys, IReadOnlyList`1 foreignKeys, Object oldValue, Object newValue)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectKeyChange(InternalEntityEntry entry, IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.PropertyChanged(InternalEntityEntry entry, IPropertyBase propertyBase, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.PropertyChanged(InternalEntityEntry entry, IPropertyBase property, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetProperty(IPropertyBase propertyBase, Object value, Boolean setModified)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetCurrentValue(IPropertyBase propertyBase, Object value)
   at Microsoft.EntityFrameworkCore.Update.ColumnModification.set_Value(Object value)
   at Microsoft.EntityFrameworkCore.Update.ModificationCommand.PropagateResults(ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagation(Int32 commandIndex, RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.Consume(RelationalDataReader reader)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
`

**Comment by ajcvickers** [comment] 2019-02-13 16:58
@MCFHTAGENTS The fix is scheduled to be released as part of the EF Core/.NET Core 2.2.3 patch.

**Closed** 2019-02-14 20:33 UTC
Labels: closed-fixed, customer-reported, regression, servicing-approved, type-bug

**Comment by Eirenarch** [comment] 2019-03-06 14:23
When is 2.2.3 expected?'

**Comment by ajcvickers** [comment] 2019-03-06 16:24
@Eirenarch It is expected to ship later this month.

**Comment by MCFHTAGENTS** [comment] 2019-03-12 12:43
Thanks all - looks like 2.2.3  has solved my problem 👍
