### ISSUE TITLE
[3.0] Owned types are null when Select, Skip and Take are used with Sqlite

### ISSUE THREAD

**Issue by BrightSoul** [aspnet/EntityFrameworkCore#18734] opened 2019-11-04 00:07 UTC
Hello there, I've found an eerie behavior with EFCore 3.0 and Sqlite. Owned types are null when I use Select, Skip and Take because their fields do not appear in the SQL query. Here's a repro project.
[https://github.com/BrightSoul/repro-skip-take-issue](https://github.com/BrightSoul/repro-skip-take-issue)

Here's the gist of it: a simple entity having a `CurrentPrice` property of type `Money`.
```cs
    public class Course
    {
        public int Id { get; private set; }
        public string Title { get; private set; }
        public Money CurrentPrice { get; private set; }
    }
```
And here's `Money`, very simple.
```cs
    public class Money
    {
        public decimal Amount { get; set; }
        public Currency Currency { get; set; } //Currency is just an enum type
        
        public override string ToString()
        {
            return $"{Currency} {Amount:#.00}";
        }
    }
```
Here's the mapping for `Course`. As you can see, `Money` is an owned type.
```cs
modelBuilder.Entity<Course>(entity =>
            {
                entity.OwnsOne(course => course.CurrentPrice, builder => {
                    builder.Property(money => money.Currency).HasConversion<string>();
                });
            });
```
Now I run this LINQ query. As you can see there's a Select invoking a static mapping method (because reasons) and Skip and Take are used.
```
var courseList1 = await dbContext.Courses
                    .Select(course => CourseViewModel.FromEntity(course))
                    .Skip(0).Take(3)
                    .AsNoTracking()
                    .ToListAsync();
```
Here's the issue: all items in `courseList1` have a null `CurrentPrice` property. I had no problem with ASP.NET Core 2.2.

If, instead, I omit Skip and Take, everything is working fine. All of the items in `courseList2` have a proper value for the `CurrentPrice` property.
```
var courseList2 = await dbContext.Courses
                    .Select(course => CourseViewModel.FromEntity(course))
                    //.Skip(0).Take(3) //Omit this
                    .AsNoTracking()
                    .ToListAsync();
```

Again, here's the repro. It's a very simple ASP.NET Core application.
[https://github.com/BrightSoul/repro-skip-take-issue](https://github.com/BrightSoul/repro-skip-take-issue)

I know I should have made a Unit Test project but it's 1 AM and I'm about to fall asleep on the keyboard after trying to understand this problem for 3 hours. Sorry.

Would you please take a look?

Thanks,
Moreno

**Comment by ajcvickers** [comment] 2019-11-04 21:19
@smitpatel Is this a duplicate of #18672 If so, maybe we should prepare a patch.

**Comment by smitpatel** [comment] 2019-11-05 04:13
Both of them happens in same area but this has different root cause. Above case specifically is about doing client projection in non-last operation. Any operation which does pushdown can cause not loading the properties.
#18672, we still have entity references just in a form which we did not recognize. Above case, we don't even have entity left after client projection. Nav expansion moves skip/take before select, and that is where things are going wrong. If we don't move then above query is non-translatable as is.

The fix would be somewhat non-trivial because we are going to change what we have been doing in processing skip/take in nav expansion since we have moved to new pipeline. It can make some queries which are getting translated right now fail.

**Comment by ajcvickers** [comment] 2019-11-08 20:40
Note from triage: Putting this in 5.0 for the same reason as #18672

**Closed** 2020-01-01 03:03 UTC
Labels: area-query, closed-fixed, customer-reported, type-bug
