### ISSUE TITLE
Using OrderBy object type in dynamic linq expression causes client eval

### ISSUE THREAD

**Issue by teichmandaniel** [aspnet/EntityFrameworkCore#11453] opened 2018-03-28 12:16 UTC
Group by multiple fields using Date part of DateTime causes Sql error.

Stack Trace:
System.Data.SqlClient.SqlException : Incorrect syntax near the keyword 'AS'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LightSail.DataAccess.Repositories.ReadingTimePerPageRepository.TestGroupByDate() in C:\AgileWork\LightSail.API.v2\src\DataAccess\Repositories\ReadingTimePerPageRepository.cs:line 116
   at IntegrationTests.DataAccess.Users.Sessions.Reading.ReadingTimePerPageRepositoryTester.TestGroupByDate() in C:\AgileWork\LightSail.API.v2\src\IntegrationTests\DataAccess\Users\Sessions\Reading\ReadingTimePerPageRepositoryTester.cs:line 60

```

### Steps to reproduce
```c#        public void TestGroupByDate()
        {
            DbContext.ReadingTimePerPages.GroupBy(r => new { r.UserId, r.CreatedDateTime.Date}).Select(r => new { r.Key, Total = r.Sum(x => x.TimeSpent) }).ToList();
        }
```
Generates the following Sql query:
`SELECT [r].[UserId], CONVERT(date, [r].[CreatedDateTime]) AS [Date], SUM([r].[TimeSpent])
FROM [dbo].[ReadingTimePerPage] AS [r]
GROUP BY [r].[UserId], CONVERT(date, [r].[CreatedDateTime]) AS [Date]`

### Further technical details
EF Core version:        2.1.0-preview1-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.6

**Comment by smitpatel** [comment] 2018-03-28 14:15
Duplicate of #11218

**Comment by daaa57150** [comment] 2018-06-22 13:48
Hi,
I just updated everything to version 2.1.1 and I'm still experiencing this bug.
Was it packaged in the latest release ?

**That's the generated query** (I had to obfuscate some things)
```
SELECT DATEPART(year, [mv].[Date]) AS [Annee], DATEPART(month, [mv].[Date]) AS [Mois], [mv.Auteur].[IsActive], [mv.Auteur].[UserName] AS [Login], [mv.Auteur].[LastName] AS [Nom], [mv.Auteur].[FirstName] AS [Prenom], SUM([mv].[Montant]) AS [Montant]
FROM [MV] AS [mv]
INNER JOIN [AspNetUsers] AS [mv.Auteur] ON [mv].[AuteurId] = [mv.Auteur].[Id]
INNER JOIN [EV] AS [mv.Ev] ON [mv].[EvId] = [mv.Ev].[Id]
WHERE (([mv].[Discriminator] IN (N'MvUtilisateur', N'MvClient', N'Mv') AND [mv.Ev].[Discriminator] IN (N'TU', N'TC', N'AR')) AND ((([mv].[Discriminator] = N'MvClient') AND ([mv].[ClientId] = @__clientId_0)) OR (([mv].[Discriminator] = N'MvUtilisateur') AND [mv].[UserId] IN (
    SELECT [user].[Id]
    FROM [AspNetUsers] AS [user]
    WHERE [user].[ClientId] = @__clientId_1
)))) AND ([mv.Ev].[Discriminator] = N'AR')
GROUP BY [mv.Auteur].[IsActive], [mv.Auteur].[UserName], [mv.Auteur].[LastName], [mv.Auteur].[FirstName], DATEPART(year, [mv].[Date]), DATEPART(month, [mv].[Date])
ORDER BY DATEPART(year, [mv].[Date]) AS [Year], DATEPART(month, [mv].[Date]) AS [Month], [Nom], [Prenom]
OFFSET @__p_2 ROWS FETCH NEXT @__p_3 ROWS ONLY
```
=> `AS [Year]` and `AS [Month]` should not be in the `ORDER BY`.

**The code to generate that query looks like this** (obfuscated a little)
```
 	var userIds = from user in _context.Users where user.ClientId == 'clientId' select user.Id;
 	var mvs = _context.Mvs
                .Where(mv =>
                    (
                        mv is MvClient
                        &&
                        ((MvClient)mv).Client.ID == 'clientId')
                    ||
                    (
                        mv is MvUtilisateur
                        &&
                        userIds.Contains(((MvUtilisateur)mv).User.Id)
                    )
                ) 
                .Where(mv => mv.Ev is AR)
		.GroupBy(mv => new {
                	mv.Auteur.IsActive,
                	mv.Auteur.UserName,
                	mv.Auteur.LastName,
                	mv.Auteur.FirstName,
                	mv.Date.Year,
                	mv.Date.Month
            	})
            	.Select(g => new CPerMonth()
            	{
                	Annee = g.Key.Year,
                	Mois = g.Key.Month,
                	Utilisateur = new CPerMonth.Auteur()
                	{
                	    IsActive = g.Key.IsActive,
                	    Login = g.Key.UserName,
                	    Nom = g.Key.LastName,
                	    Prenom = g.Key.FirstName
                	},
                	Montant = g.Sum(m => m.Montant)
            	})
		.OrderBy(c => c.Annee)
		.ThenBy(c => c.Mois)
		.ThenBy(c => c.Utilisateur.Nom)
		.ThenBy(c => c.Utilisateur.Prenom)
		.Skip(0)
		.Take(20);
```

**Here is what the `dotnet --info` command spits out:**
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.301\

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]
  2.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

Did I do something wrong?

**Comment by ralmsdeveloper** [comment] 2018-06-22 17:54
Fyi:
@ajcvikers I did not find where ... But I'm pretty sure to have a PR that @Smitpatel worked on.

**Comment by ajcvickers** [comment] 2018-06-27 20:43
@daaa57150 Can you post a runnable project/solution that demonstrates this behavior, or at least the shape of the entity types involved and their configuration?

**Comment by daaa57150** [comment] 2018-06-28 11:53
I'll try to post a runnable project demonstrating the problem.

**Comment by daaa57150** [comment] 2018-06-29 13:19
So, the query executed exactly as I wrote it previously:
- in a fresh project => WORKS
- in MY project => ALSO WORKS!

I was really puzzled but by splitting the query step by step to match the code in my project, I finally found the culprit. 

Here is an exerpt of the faulty code:
```
var transfers = _context.MoneyTransfers.Where(etc...).Etc();
Expression<Func<ConsumptionPerMonth, object>>[] expressions = {
        c => c.Year,
        c => c.Month,
        c => c.User.LastName,
        c => c.User.FirstName
};
transfers = transfers
        .OrderBy(expressions[0])
        .ThenBy(expressions[1])
        .ThenBy(expressions[2])
        .ThenBy(expressions[3]);
```

The full project demonstrating this can be found [here](https://github.com/daaa57150/DotNetBugGroupByDatePart).
Just execute the `BugGroupByDatePart.Tests.EFTests.TestGroupByDatePart()` method in debug mode, so you'll have the generated SQL in the debugger.
I didn't include anything to create the DB, the exception happens before realising the tables aren't here; but a connection to a real DB is needed, and configurable in the `appsettings.json` file.

So, is this really a bug or is my code just wrong?

**Comment by daaa57150** [comment] 2018-07-06 18:36
Why was this closed? Won't fix?

**Comment by ajcvickers** [comment] 2018-07-06 20:43
@daaa57150 Basically because you said that it works in both a fresh project and in your project. We had trouble interpreting what you wrote, but the concensous was that there was no issue. I assume from your response this is not correct, in which case I'll re-open.

**Comment by smitpatel** [comment] 2018-07-06 20:47
Related https://github.com/aspnet/EntityFrameworkCore/issues/12493#issuecomment-401103445

Using `Func<ConsumptionPerMonth, object>` can easily throw off translation pipeline and cause a client eval.

**Comment by daaa57150** [comment] 2018-07-06 22:43
Ok, sorry I wasn't clear enough.

**Comment by mark-szabo** [comment] 2018-08-12 10:08
Guys, this is not just for OrderBy but for GroupBy too.
I have oversimplified my query to show only the problem:

```
_context.Reservation
.GroupBy(r => r.DateFrom.Date)
.Select(g => new
{
    g.Key.Date,
    TimeSum = g.Sum(r => r.TimeRequirement)
})
//.Where(d => d.TimeSum >= limit)
.Select(d => d.Date)
```

The `.Where` part is not important, included just to show why would I use `.Select` two times. 
So this translates to:

```
SELECT CONVERT(date, CONVERT(date, [r].[DateFrom]) AS [Key])
FROM [Reservation] AS [r]
GROUP BY CONVERT(date, [r].[DateFrom])
```

Converting two times is redundant, and more importantly throws an error if used with `AS`: `Incorrect syntax near the keyword 'AS'.`

**Comment by mark-szabo** [comment] 2018-08-12 12:39
Even better example:

```csharp
_context.Reservation
.GroupBy(r => r.DateFrom)
.Select(g => g.Key.Hour)
```
translates to:
```sql
SELECT DATEPART(hour, [r].[DateFrom] AS [Key])
FROM [Reservation] AS [r]
GROUP BY [r].[DateFrom]
```

Error as always: `Incorrect syntax near the keyword 'AS'.` 

The problem is clearly with the insertion of `AS [Key]`.

**Comment by mark-szabo** [comment] 2018-08-13 20:15
Thanks

**Comment by cdwaddell** [comment] 2019-01-29 19:43
I ran into this issue today after upgrading, I have an extra item in my orderby statement that is causing the query execution plan to go out the window and my query to timeout.

```
_context.UserProfiles.AsNoTracking()
                .OrderByDescending(p => p.User.LastLogin)
```

Is turned into 

```
(@__p_1 int,@__p_0 int)
SELECT ... FROM [com].[UserProfiles] AS [p] 
INNER JOIN [sec].[Users] AS [p.User] ON [p].[UserId] = [p.User].[Id] 
ORDER BY [p.User].[LastLogin] DESC, [p.User].[Id] OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
```

**Comment by smitpatel** [comment] 2019-01-29 19:54
The extra item in order by is to do collection include. If that is causing the query to slow down then collection include query is going to be even slower.

**Comment by cdwaddell** [comment] 2019-01-29 19:56
Why does the include affect the order by? FYI, this was not the query executed before upgrading to the latest EF Core.

**Closed** 2019-09-10 00:15 UTC
Labels: closed-fixed, punted-for-3.0, type-bug

**Comment by onionhammer** [comment] 2019-10-24 16:44
I'm getting something very similar to this issue (maybe the same?)

If I translate an expression from a string into an expression dynamically, I get the exact same resulting expression, based on a diff of the `DebugView` property, but on `q2` in the picture, I get an 'InvalidOperationException'

![image](https://user-images.githubusercontent.com/969938/67506774-4ca34e00-f653-11e9-9bad-ab900f03a943.png)

![image](https://user-images.githubusercontent.com/969938/67506929-9a1fbb00-f653-11e9-8074-c8a996fdb792.png)

**Comment by smitpatel** [comment] 2019-10-24 16:52
@onionhammer - Please file a new issue with detailed repro code. If the tree generated is different from what compiler generates then it may not get translated.

**Comment by onionhammer** [comment] 2019-10-24 17:00
@smitpatel I will.. but the tree is exactly the same as far as the debug view shows

**Comment by smitpatel** [comment] 2019-10-24 17:13
@onionhammer - It is not necessarily true. Even though 2 member access would read the same, the underlying MemberInfo could be different. And incorrect in certain cases. There could be convert nodes which are converting to different types. Looking at the screenshots it is hard to tell anything.

**Comment by onionhammer** [comment] 2019-10-24 20:26
@smitpatel Opened issue #18584
