### ISSUE TITLE
An exception occurred while reading a database value. The expected type was 'System.Decimal' but the actual value was of type 'System.Double'

### ISSUE THREAD

**Issue by samzhou2** [aspnet/EntityFrameworkCore#13587] opened 2018-10-11 05:49 UTC
An aggregation query with cast will throw  InvalidOperationException

```
Exception message:
An exception occurred while reading a database value. The expected type was 'System.Decimal' but the actual value was of type 'System.Double'. ---> System.InvalidCastException: Specified cast is not valid.

Stack trace:
Exception thrown: 'System.InvalidOperationException' in Microsoft.EntityFrameworkCore.dll
System.InvalidOperationException: An exception occurred while reading a database value. The expected type was 'System.Decimal' but the actual value was of type 'System.Double'. ---> System.InvalidCastException: Specified cast is not valid.
   at System.Data.SqlServerCe.SqlCeDataReader.GetDecimal(Int32 ordinal)
   at lambda_method(Closure , DbDataReader )
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Metadata.Internal.EntityMaterializerSource.ThrowReadValueException[TValue](Exception exception, Object value, IPropertyBase property)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.GetResult[TResult](IEnumerable`1 valueBuffers, Boolean throwOnNullResult)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at TestHostInvalidCast.Tests.InvalidCastTest.<>c.<SqlCe_InvalidOperationException_Thrown>b__0_0(DataContext context) in D:\Projects\EfCoreRepro\InvalidCast\Tests\InvalidCastTest.cs:line 20
```

### Steps to reproduce

Entity:
```c#
    public class InventoryPool
    {
        [Key]
        public int Id { get; set; }
        public double Quantity { get; set; }
    }
```

Query to reproduce error
```c#
context.Set<InventoryPool>().Sum(p => (decimal) p.Quantity);
```

Repro included at https://github.com/avinash-phaniraj-readify/EFCoreTestBed/tree/InvalidCast

### Further technical details
EF Core version: 2.1.4
Database Provider: SqlServer and SqlCE
Operating system: Win 10
IDE: VS 2017 15.8.1

**Comment by ajcvickers** [comment] 2018-10-11 15:57
Note for triage: was able to easily repro this.

**Comment by optiks** [comment] 2018-10-11 21:39
@ajcvickers, if there’s any way of getting this into a 2.1 patch we’d be greatly appreciative. Totally understand if you can’t though.

**Comment by bricelam** [comment] 2018-10-12 22:18
Dupe of #10642?

**Comment by smitpatel** [comment] 2018-10-15 23:54
This is regression introduced in https://github.com/aspnet/EntityFrameworkCore/pull/8861 unintentionally.

**Comment by ajcvickers** [comment] 2019-08-10 01:02
Reopening because failing tests are disabled referencing this issue:
* 

```
ystem.InvalidOperationException : Operation is not valid due to the current state of the object.
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateGroupBy(ShapedQueryExpression source, LambdaExpression keySelector, LambdaExpression elementSelector, LambdaExpression resultSelector) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 337
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\QueryableMethodTranslatingExpressionVisitor.cs:line 161
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\aspnet\EntityFrameworkCore\src\EFCore.Relational\Query\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 74
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\QueryCompilationContext.cs:line 68
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async) in C:\aspnet\EntityFrameworkCore\src\EFCore\Storage\Database.cs:line 71
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 106
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0() in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 96
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 84
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 59
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 92
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 79
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator() in C:\aspnet\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryable`.cs:line 94
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.GearsOfWarQueryTestBase`1.Include_collection_group_by_reference() in C:\aspnet\EntityFrameworkCore\test\EFCore.Specification.Tests\Query\GearsOfWarQueryTestBase.cs:line 5676
   at Microsoft.EntityFrameworkCore.Query.GearsOfWarQuerySqlServerTest.Include_collection_group_by_reference() in C:\aspnet\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\Query\GearsOfWarQuerySqlServerTest.cs:line 5563
```

**Comment by ajcvickers** [comment] 2019-08-12 17:06
@smitpatel to follow up.

**Comment by smitpatel** [comment] 2019-08-12 23:01
Filed #17111

**Closed by smitpatel** 2019-08-12 23:01 UTC
Labels: closed-fixed, customer-reported, regression, type-bug
