### ISSUE TITLE
Where_subquery_correlated_client_eval test not providing stable results

### ISSUE THREAD

**Issue by cincuranet** [aspnet/EntityFrameworkCore#14874] opened 2019-02-28 14:05 UTC
The `Where_subquery_correlated_client_eval` test has the `Take(5)` before `OrderBy`, which means it's taking "random" 5 records and then sorting those. It's visible in _SqlServer_ tests.

```sql
SELECT [t].[CustomerID], [t].[Address], [t].[City], [t].[CompanyName], [t].[ContactName], [t].[ContactTitle], [t].[Country], [t].[Fax], [t].[Phone], [t].[PostalCode], [t].[Region]
FROM (
    SELECT TOP(@__p_0) [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region]
    FROM [Customers] AS [c]
) AS [t]
ORDER BY [t].[CustomerID]
```

I think the `Take(5)` should be after the `OrderBy`, hence the 5 records is explicit in respect to ordering. I'll create a PR, if we agree it's a valid change.

**Comment by smitpatel** [comment] 2019-02-28 19:32
It's a valid change. Feel free to create a PR.
SqlServer has default ordering which matches L2O ordering so we ended up with tests which passes by co-incidence. We have run into similar issue with PostgreSQL in past which does not have such default ordering. If you encounter any test which does skip/take without OrderBy, you can submit PR to correct it.

In future, we are going to have tests with Take without OrderBy, which will generate unstable results (by design). But the test would be marked as such to indicate that.

**Closed** 2019-03-01 15:28 UTC
Labels: customer-reported
