### ISSUE TITLE
Auto-bootstrap design time provider services through Attribute

### ISSUE THREAD

**Issue by tonysneed** [aspnet/EntityFrameworkCore#10154] opened 2017-10-25 13:56 UTC
As described in #5617, EF Core tooling currently scans the startup assembly for a class that implements `IDesignTimeServices`, then invokes `ConfigureDesignTimeServices`.  This allows for registering implementations of EF Core interfaces in order to customize behavior.  However, the ability to customize the EF Core toolchain could be improved, so that the requirement for the developer to add a `IDesignTimeServices` implementation class can be removed.

If EF tooling can scan referenced assemblies for a `IDesignTimeServices` implementation, then services can be configured by a class library or NuGet package rather than the developer who is consuming an extension to the EF tooling.  This helps reduce the amount of friction so that the only thing a developer as to do is add a package that is self-configuring.  EF tooling can scan the startup assembly first and use an `IDesignTimeServices` if one exists, so the developer can still control the process.  But if the startup assembly does not contain an `IDesignTimeServices`, then EF tooling can scan referenced assemblies for an `IDesignTimeServices` and use it if it finds one.

In addition to bringing in `IDesignTimeServices` from referenced assemblies, I would suggest adding an argument to `dotnet ef dbcontext scaffold` for the name of a NuGet package containing an `IDesignTimeServices` implementation.  That way, a project can reference multiple packages containing `IDesignTimeServices` implementations and the developer can select the one to use when executing the scaffolding command.  So for example, a .NET Core library can reference a package that generates C# class as well as one that generates TypeScript classes, then he or she can pass the name of one package or the other to `dotnet ef dbcontext scaffold` in order to generate either C# or TypeScript classes.

**Comment by bricelam** [comment] 2017-10-25 16:11
We do a similar thing with providers. The user specifies the provider in `Scaffold-DbContext`, we load the assembly and look `[assembly: DesignTimeProviderServices]`, then use that type to add design-time services.

I hate the idea of scanning referenced assemblies. This always turns into a can of worms. I'd rather look into using NuGet to put a list of these assemblies somewhere (either in the startup assembly or somewhere under the `obj` directory)

**Comment by bricelam** [comment] 2017-10-25 16:13
We recently discussed a similar need for EF6. We can probably kill two birds with one stone when designing this.

**Comment by tonysneed** [comment] 2017-10-25 16:36
I like the idea of taking the same approach as specifying the provider in `Scaffold-DbContext` and using NuGet to list the assemblies.  Happy to help with this effort.

**Comment by bricelam** [comment] 2017-10-25 19:38
Putting this on the backlog since our higher priority is #4038 (which involves cleaning up the existing APIs and removing them from the `.Internal` namespace).

If you're eager to start implementing this, I'd be happy to work with you on a design.

**Comment by tonysneed** [comment] 2017-10-25 20:08
Yes, it would be great to design this along the lines of your [comment](https://github.com/aspnet/EntityFrameworkCore/issues/10154#issuecomment-339383819), getting NuGet to add the list of assemblies, loading them and looking for `[assembly: DesignTimeProviderServices]`.

**Comment by bricelam** [comment] 2017-10-25 20:38
Let's create a new attribute instead of overloading that one.

I'm not sure the best way of getting a list of them. I would hate to compile design-time code into the application assembly, but doing it all with MSBuild will be tricky.

I might have to prototype something to get us started.

**Comment by bricelam** [comment] 2017-10-25 20:41
I've been wanting to prototype this for VB and F# Migrations anyway, so I'll play around with it when I get a chance.

Feel free to experiment a bit yourself too

**Comment by tonysneed** [comment] 2017-10-25 22:13
Sounds good .. I’ll experiment and see what I come up with.

**Comment by tonysneed** [comment] 2017-10-27 13:36
@bricelam I've been poking around the EFCore.Tools project and noticed [EntityFrameworkCore.psm1](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Tools/tools/EntityFrameworkCore.psm1#L246.  I see a [GetProviders](https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Tools/tools/EntityFrameworkCore.psm1#L533) function in there that looks for a package with the same name as that supplied to the command line arg.

Would we want to take the same approach to locating a package that provides design time services?

**Comment by bricelam** [comment] 2017-10-27 18:21
I don't think the user should have to specify anything in the `dotnet ef dbcontext scaffold` or `Scaffold-DbContext` commands.

My hope is that merely installing a plug-in package will make it's services available at design time.

One way to do this using MSBuild is to have each package add a file like this to their NuGet pacakge under `build\netstandard2.0\MyPackage.targets`.
``` xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <MSBuildAllProjects>$(MSBuildAllProjects);$(MSBuildThisFileFullPath)</MSBuildAllProjects>
    <MyPackageDesignTimeServicesFile>$(IntermediateOutputPath)MyPackageDesignTimeServices$(DefaultLanguageSourceExtension)</MyPackageDesignTimeServicesFile>
  </PropertyGroup>
  <Target Name="AddMyPackageDesignTimeServices"
          BeforeTargets="CoreCompile"
          DependsOnTargets="PrepareForBuild"
          Condition="'$(DesignTimeBuild)' != 'True'"
          Inputs="$(MSBuildAllProjects)"
          Outputs="$(MyPackageDesignTimeServicesFile)">
    <ItemGroup>
      <MyPackageDesignTimeServices Include="Microsoft.EntityFrameworkCore.Design.DesignTimeServicesAttribute">
        <_Parameter1>MyPackage</_Parameter1>
        <_Parameter2>MyPackage.MyDesignTimeServices</_Parameter2>
      </MyPackageDesignTimeServices>
    </ItemGroup>  
    <WriteCodeFragment AssemblyAttributes="@(MyPackageDesignTimeServices)"
                       Language="$(Language)"
                       OutputFile="$(MyPackageDesignTimeServicesFile)">
      <Output TaskParameter="OutputFile" ItemName="Compile" />
      <Output TaskParameter="OutputFile" ItemName="FileWrites" />
    </WriteCodeFragment>  
  </Target>
</Project>
```

This will add the following code to the project the package is installed into.

``` csharp
using Microsoft.EntityFrameworkCore.Design;

[assembly: DesignTimeServices("MyPackage", "MyPackage.MyDesignTimeServices")]
```

The EF Tools can then scan the startup and target projects, look for this attribute and load the specified assembly and type to add the design-time services.

**Comment by tonysneed** [comment] 2017-10-27 21:25
I like the idea of just installing a package and having the EF tools pick that up. The question I have is what if more than one of these kinds of packages are installed? How do we tell the tooling which one to use with a specific scaffolding command? For example, I may want to install one package for server C# entities and another for TypeScript client entities. I should be able to execute a command to generate one or the other, so maybe a command line arg might enable this?

**Comment by bricelam** [comment] 2017-10-27 23:42
Interesting. You effectively want to flow command-line arguments into the code generator. This possibly relates to issue #8332...

Would you generate both in the same project? If not, you could put the C# templates in one and the TypeScript templates in another.

Maybe the your code generator just needs to allow multiple entity type templates and invoke each one...

I've started down the path of C# vs VB vs F# in [bricelam:lang](https://github.com/aspnet/EntityFrameworkCore/compare/dev...bricelam:lang), by I was just going to infer it from the project, not let the user specify it.

**Comment by tonysneed** [comment] 2017-10-28 00:12
> Interesting. You effectively want to flow command-line arguments into the code generator. This possibly relates to issue #8332...

Actually, I'm thinking of just adding something like a `--design-time-services` option that can accept a comma separated list of packages that have the `[assembly: DesignTimeServices]` attribute you [described](https://github.com/aspnet/EntityFrameworkCore/issues/10154#issuecomment-340047623). (More than one could be specified.) . Then those could each be passed to `DesignTimeServicesBuilder.ConfigureDesignTimeServices`.

> Would you generate both in the same project? If not, you could put the C# templates in one and the TypeScript templates in another.

I think it's most common to create a single .NET Core app or lib where you do all the code gen from, outputting to different locations.  But that could be taken care of by my [suggestion](https://github.com/aspnet/EntityFrameworkCore/issues/1836#issuecomment-340124502) in #1836.

> Maybe the your code generator just needs to allow multiple entity type templates and invoke each one...

The developer could use multiple code generators from different authors, so I think good to provide a way to select which one(s) to use when scaffolding.

**Comment by bricelam** [comment] 2017-10-30 21:40
My brain has churning on this, and I think `--design-time-services` is too coarse-grained for what we want. It should be fine to add lost of design-time services (e.g. a pluralizer, a Migrations code generator, a Reverse Engineer code generator, etc.). The problem comes when two of those things conflict (i.e. there ends up being more than one of the same service). We mitigate this a bit by flowing in the project language (e.g. we won't pick an F# scaffolder on a C# project), but you could still have two flavors of scaffolding for the same project language.

I wonder, however, if this problem is specific to your tool. If you added a new command (as discussed in #10156), you could replace the scaffolding factory (drafted in [bricelam:lang](https://github.com/aspnet/EntityFrameworkCore/compare/dev...bricelam:lang)) with one that selects based on user-input on the command line. Outside of your tool, conflicts could be resolved by the user adding their own `IDesignTimeServices` implementation.

**Comment by smitpatel** [comment] 2017-10-30 22:22
Sorry I couldn't get my head around the misleading title 😥

**Comment by tonysneed** [comment] 2017-10-30 22:53
I think adding a `IDesignTimeServices` implementation isn't too much to ask the developer if the package developer provides an extension method (which is what I do).  But it's just a bit nicer to be able to add package and have the EF tooling just pick that up.

So the auto-bootstrapping idea would reduce the friction there.  Maybe an error could be shown if there's a conflict, so the user can either uninstall the conflicting package or add their own `IDesignTimeServices` implementation.

**Comment by bricelam** [comment] 2017-10-31 18:25
Yes, we definitely need a warning. I agree, if there's no conflict, installing the package should be enough. My ideal workflow is something like:

    dotnet add package Microsoft.EntityFrameworkCore.Pluralizers.English
    dotnet add package Microsoft.EntityFrameworkCore.VisualBasic
    dotnet ef dbcontext scaffold...

**Comment by tonysneed** [comment] 2017-10-31 18:55
Sounds like a great idea to me. Let me know if I can help implement it.

**Closed** 2017-12-15 21:34 UTC
Labels: closed-fixed, type-enhancement

**Comment by bricelam** [comment] 2017-12-16 00:34
@tonysneed I've ported the EF6 pluralizer and packaged it appropriately in [bricelam/EFCore.Pluralizer]https://github.com/bricelam/EFCore.Pluralizer).

**Comment by ErikEJ** [comment] 2017-12-16 14:47
@bricelam I assume this is "better" than this: https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/ReverseEngineer20/ReverseEngineer/Inflector.cs ? I will use this instead in EF Core Power Tools, then

**Comment by ErikEJ** [comment] 2017-12-16 14:49
@bricelam  No Nuget package?

**Comment by bricelam** [comment] 2017-12-18 03:11
Definitely not "better" as far as pluralizers go. It's mostly a sample that also happens to be useful as an EF6-compatible pluralizer. Not on NuGet until 2.1.0-preview1-final ships.

**Comment by bricelam** [comment] 2017-12-18 03:13
Would be good to package and publish inflector this way too.

**Comment by Erutan409** [comment] 2024-04-08 02:25
I'm in the process of migrating an EF6 codebase to EF Core 8. I know, better late never, right? Anyway, I have a base library that my team uses for custom code migrations. And this was much simpler to implement in the EF6 version. I am able to get my custom [CSharpMigrationsGenerator](https://github.com/dotnet/efcore/blob/main/src/EFCore.Design/Migrations/Design/CSharpMigrationsGenerator.cs) implemented using the [IDesignTimeServices](https://learn.microsoft.com/en-us/ef/core/cli/services) approach. Problem is (as I've gleaned from the OP's similar situation), I can't seem to get this to work by declaring this configuration from the base class my project(s) would be inheriting from.

So...

I read through these comments and the merged [PR](https://github.com/dotnet/efcore/pull/10567). I couldn't find any relative [official] documentation to help me understand how to effectively use the implemented attribute(s). But I suspect this may still not solve for the issue I'm having making this an abstract/default configuration from all derived contexts with the EF Core version of my class.

Is this truly now a requirement that every project will need to implement, that was once a breeze to configure by default back with EF6? Hoping it's a misunderstanding on my part.

Thank you!

**Comment by ajcvickers** [comment] 2024-04-10 09:51
@Erutan409 If this isn't working for you, then please open a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.
