### ISSUE TITLE
Joining DbSet<>s in differend DbContext

### ISSUE THREAD

**Issue by armanpetrosyan23** [aspnet/EntityFrameworkCore#13775] opened 2018-10-26 10:46 UTC
How to join two DbSet<> in different db contexts in EF Core? I have written the following code: Here I have got `NullReferenceException`

Exception message:
System.ArgumentNullException

  Message=Value cannot be null.
Parameter name: entityType
  Source=Microsoft.EntityFrameworkCore.Relational

Code
var collections = (from l in _logcontext.Logs join p in _applicationdbcontext.Users on l.UserID equals p.Id select new { i = l.TableName }).ToList();

 ScreenShot 

![capture](https://user-images.githubusercontent.com/35919382/47561997-16db6480-d92e-11e8-816f-fc65c1288313.PNG)

**Comment by smitpatel** [comment] 2018-10-26 17:55
Duplicate of #11101

**Comment by smitpatel** [comment] 2018-10-26 17:55
Which version of EF Core are you using?

**Comment by armanpetrosyan23** [comment] 2018-10-26 18:03
I use ef core 2.1 version

**Comment by armanpetrosyan23** [comment] 2018-10-26 18:31
@smitpatel #11101 here is writed that this issue has been solved in 2.1 version and  even if i use low version for example 2.0.3  i only see followin exception notsuportedoperatiom but as we see throw diferent exceptiom is being

**Comment by armanpetrosyan23** [comment] 2018-10-29 06:11
@smitpatel ?????

**Comment by smitpatel** [comment] 2018-10-29 06:16
@armanpetrosyan23 - We will need full repro code here to investigate in the issue.

**Comment by armanpetrosyan23** [comment] 2018-10-29 06:28
@smitpatel 
 That error occurs everywhere and our source code does not matter

**Comment by armanpetrosyan23** [comment] 2018-10-29 07:13
@smitpatel This is my project link where i occurs problems
https://github.com/armanpetrosyan23/Test_Seed.git

**Comment by nfdevil** [comment] 2018-11-06 14:20
I'm having the same issue when trying to join my ASP.NET Core Identity dbcontext with my ApplicationDbContext:

`_dbContext.Comments.Join(_identityDbContext.Users, comment => comment.CreatedById, user => user.Id, (comment, user) => new { comment.Body, comment.Id });`

When using the same DbContext in the join, this works perfectly:

`_dbContext.Comments.Join(_dbContext.HospitalizationRequests, comment => comment.HospitalizationRequestId, request => request.Id, (comment, request) => new { comment.Body, comment.Id })`

I'm receiving the following error: 

"Value cannot be null. Parameter name: entityType"

Both DbContexts are using the same database, but are on other schema's:

_dbContext is on schema "HospitalizationRequests"
_identityDbContext is on schema "Authz"

Hope this helps when trying to solve this.

**Comment by smitpatel** [comment] 2018-11-06 20:10
This is a bug. We missed out specific code path when DbSet properties on context are used directly. This has been fixed in new funcletizer already.

**Closed** 2018-11-15 00:14 UTC
Labels: closed-fixed, customer-reported, type-bug

**Comment by a-a-k** [comment] 2020-05-28 15:03
so, are we able to join different contexts now? in which EF version? it's not clear from the discussion
