### ISSUE TITLE
Query: Result mismatch likely due to null semantics

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#16093] opened 2019-06-14 01:02 UTC
```
        [ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task Contains_with_subquery_optional_navigation_and_constant_item(bool isAsync)
        {
            return AssertQuery<Level1>(
                isAsync,
                l1s => l1s.Where(l1 => l1.OneToOne_Optional_FK1.OneToMany_Optional2.Distinct().Select(l3 => l3.Id).Contains(1)),
                l1s => l1s.Where(
                    l1 => MaybeScalar<bool>(
                              l1.OneToOne_Optional_FK1,
                              () => l1.OneToOne_Optional_FK1.OneToMany_Optional2.Distinct().Select(l3 => l3.Id).Contains(1)) == true),
                elementSorter: e => e.Id,
                elementAsserter: (e, a) => Assert.Equal(e.Id, a.Id));
        }
```

**Comment by maumar** [comment] 2019-06-19 01:39
related to #15798

**Comment by maumar** [comment] 2019-11-05 20:10
dupe of #15798

**Comment by smitpatel** [comment] 2019-11-06 03:16
There are more tests disabled with this issue number.

**Closed** 2019-11-08 22:09 UTC
Labels: closed-fixed, type-bug
