### ISSUE TITLE
GroupBy constant and element selector produces invalid SQL

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/EntityFrameworkCore#11993] opened 2018-05-14 15:02 UTC
Version: `2.1.0-rc1`

Similar to #11905:

```c#
_nwind.Orders

     // caused by this line
    .Select(i => new { i.OrderId, i.Freight })

    .GroupBy(obj => 1)
    .Select(g => new {
        Sum = g.Sum(obj => obj.Freight)
    })
    .ToArray();
```

The use case for this: `Select` is done by a user (pre-select data of interest), the rest of the query is added by a DevExpress product (data aggregation).

The query doesn't fail in `2.1.0-preview1-final` (with in-memory evaluation).
EF6 is ok too.

**Comment by ajcvickers** [comment] 2018-05-14 18:38
@AlekseyMartynov Do you know if this used to work in the EF Core 2.0 releases?

**Comment by AlekseyMartynov** [comment] 2018-05-14 18:50
@ajcvickers Yes this code works with 2.0.3, with in-memory grouping though.

**Comment by smitpatel** [comment] 2018-05-14 18:51
@AlekseyMartynov - Can you share the northwind context you are using? Are you using the one from EF functional tests?

**Comment by AlekseyMartynov** [comment] 2018-05-14 18:58
[11993.zip](https://github.com/aspnet/EntityFrameworkCore/files/2002156/11993.zip)

Generated with `Scaffold-DbContext "Server=.\sqlexpress;Database=northwind;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models -Tables Orders`

**Comment by smitpatel** [comment] 2018-05-14 19:10
Root cause: GroupBy constant caused us to create a subquery but the bindings for custom selector still uses old references rather than from pushed down query.

**Comment by smitpatel** [comment] 2018-05-14 19:14
This occurs in latest 2.1 nightlies too. Removing custom selector or grouping by constant make it work.

**Comment by ajcvickers** [comment] 2018-05-22 21:55
@smitpatel @anpete @maumar Let's discuss this one again in triage tomorrow with specific focus on risk for patching. /cc @divega

**Comment by ajcvickers** [comment] 2018-05-24 15:48
Removing patch-proposed until we are ready to take this to shiproom.

**Comment by ajcvickers** [comment] 2018-05-24 19:38
This is approved by shiproom for 2.1.1 patch, but please wait for the branch to be open before merging.

**Comment by ajcvickers** [comment] 2018-05-29 17:47
@smitpatel The release/2.1 branch is now open for 2.1.1 patch issues. Can we get this merged ASAP?

**Closed** 2018-05-30 18:28 UTC
Labels: customer-reported, patch-approved, regression, type-bug
