### ISSUE TITLE
Migrations: Adding new owned type references causes strange renames

### ISSUE THREAD

**Issue by mrswain** [aspnet/EntityFrameworkCore#10099] opened 2017-10-17 18:05 UTC
I have not distilled this down to a simple example from my model, but I have traced the problem to a point in the code.

The basic gist is that I have three entity types that all inherit from a base type, have a complex type property mapped to the same table, and point to similar tables (separated by database schema, basically TPT).

Adding a fourth table in a new migration will, instead of creating the new table, rename the first table to the new schema, append the new columns to it, rename the second table to the first schema, rename the third table to the second, and then recreate the third table with the first tables schema.

Via debugging and stepping through I have narrowed down the problem to https://github.com/aspnet/EntityFrameworkCore/blob/rel/2.0.1/src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L435

Mainly the problem is that the TableMapping of the types includes both the entity type and the complex type. The new table also has its entity type, and the same complex type, and is considered a match, since an Any comparison is used. This causes the migration code to think that the table is being moved (changing schema).

I understand that this is an edge case and I will see if I can overload the differ and come up with a workable solution for myself, but I think this may also be an oversight of the addition of the owned relational code (it is very likely that complex types will be shared).

### Further technical details
EF Core version: 2.0
Database Provider: SqlServer
Operating system: Win10
IDE: Visual Studio 2017

**Comment by mrswain** [comment] 2017-10-17 20:20
I got a variant that works for me, thought I have not refactored or optimized it, just broke it out and made it as verbose as possible to step through.

WARNING: UGLY CODE
`
                foreach (var se in s.EntityTypes)
                    foreach (var te in t.EntityTypes)
                        if (string.Equals(se.Name, te.Name, StringComparison.OrdinalIgnoreCase)
                            && string.Equals(se.DefiningNavigationName, te.DefiningNavigationName, StringComparison.OrdinalIgnoreCase))
                        {
                            var dse = se.DefiningEntityType;
                            var dte = te.DefiningEntityType;
                            while(string.Equals(dse?.Name, dte?.Name, StringComparison.OrdinalIgnoreCase))
                            {
                                dse = dse?.DefiningEntityType;
                                dte = dte?.DefiningEntityType;
                                if (dse == null || dte == null)
                                    break;
                            }
                            if (string.Equals(dse?.Name, dte?.Name, StringComparison.OrdinalIgnoreCase))
                                return true;
                        }

                return false;
`

This recursively follows the defining navigation if present to compare the tree instead of just the first set of names.

Better ways could be to filter out the complex in the type mapping, or a better way to get the identity of a complex, but this works for my needs.

**Comment by bricelam** [comment] 2017-10-18 17:33
Dupe of #9873?

**Comment by mrswain** [comment] 2017-10-18 19:17
Didn't see that one... Yes I would say their problem is the same as mine. I wonder if my "fix" would work for them.

**Comment by bricelam** [comment] 2017-10-18 22:18
We're happy to accept a PR on this if you're willing to write a few tests 😁

**Comment by mrswain** [comment] 2017-10-27 14:40
I do not have the time right now to create any tests and my model is fairly complex and not a good candidate. I am not working with the checked out source on my system but I did find new problems with the last preview release (2.1.0-preview1-27377) so I cleaned up my code, and created a commit for it. I created it by creating a custom class, modeling your source and then working out the changes. (for me this was simpler than downloading the whole repo and building a source version and then binding it.)

If you want I can submit the fix as a PR but it is only the fix, no tests and I would like it if someone else who is having this issue (and has made some test code) could patch it in and test it.

**Comment by rousseauo** [comment] 2017-11-29 18:55
I encoutered the same problem. Adding a migration that should generate a new table caused a bad migration when this new table owned a complex type property.  

Ex: I had 2 entities, Member & Business, wich both have a complex type Address
I created a 3rd one, Entrepreneur, also with a complex type property (owned property). 
The generated migration renamed Member-->Entrepreneur, Business-->Member and created the Business. And also adjusting properties for each modified Table. 

My work around is to add a migration with this new table without the complex type property first, so basicly an empty table in my case. And then add another migration with the complex type. This way the generated migration won't be messed up. 

Ex: If you have Member & Business, wich both have a complex type Address
Create the new entity Entrepreneur without Address, Add-Migration. 
Add the Address property to Entrepreneur, Add-Migration. 
It should generate the migration as expected.

**Comment by mrswain** [comment] 2018-01-09 16:26
This commit does not fully solve the issue, I am still getting a migration like in #10334 and I think it is because the migrator still does not properly handle schemas. My structure has three tables that are identical (and have complex types) but separated by schema, I am adding a fourth table that is nearly identical but has an additional column, and adjusted PK, again with a different schema.

The migrator will scaffold a DropKey, two RenameTables, an AddColumn, an Add Primary Key, then A CreateTable that recreates one of the original tables, instead of the new one. All it should be doing is just adding a new table.

**Comment by mrswain** [comment] 2018-01-09 19:21
Ok, looks like this fix is simpler.

https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs#L483

Add
```C#
&& EntityTypePathEquals(se, te, c)
```

after the string.Equals so if there are multiple mapped tables (which owned tables are) the match only succeeds when the Navigations match as well. Adding that in fixed all issues for me.

**Comment by bricelam** [comment] 2018-01-09 23:04
Re-opening

**Closed** 2018-01-22 22:45 UTC
Labels: closed-fixed, type-bug

**Comment by mrswain** [comment] 2018-01-23 19:24
Just wanted to comment and verify that this issue is no longer reproducible with build 28148.

**Comment by bricelam** [comment] 2018-01-23 20:05
@mrswain Thanks a million for catching this case and following up

**Comment by kjbetz** [comment] 2018-08-06 15:46
I encountered this issue last night, I believe. Should I open a new issue or post here? Thanks!

**Comment by ajcvickers** [comment] 2018-08-06 17:18
@kjbetz Please post a new issue, including a runnable project/solution or complete code listing that demonstrates the behavior you are seeing.

**Comment by kjbetz** [comment] 2018-08-06 17:19
Got it @ajcvickers, Thanks!
