### ISSUE TITLE
error NU1202: Package dotnet-ef 3.0.1 is not compatible with netcoreapp3.0

### ISSUE THREAD

**Issue by yongsauheung** [aspnet/EntityFrameworkCore#18977] opened 2019-11-19 04:17 UTC
I'm installing dotnet-ef 3.0.1 on Azure DevOps release pipeline with dotnetcore 3.0; installation fails with incompatibility error.

### Steps to reproduce
Run
```
dotnet tool install --global dotnet-ef --version 3.0.1
```

Expected
```
Tool 'dotnet-ef' (version '3.0.1') was successfully installed.
```

Actual
```
error NU1202: Package dotnet-ef 3.0.1 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0) / any. Package dotnet-ef 3.0.1 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1)
```

### Further technical details
EF Core version: 3.0
dotnet-ef version: 3.0.1

Issue is **NOT** seen in dotnet-ef version **3.0.0**. I'm currently using this version to resolve the issue.

**Comment by Nothing-Works** [comment] 2019-11-19 05:15
same here

**Comment by misaka4e21** [comment] 2019-11-19 09:01
same here, and `dotnet tool install --global dotnet-ef --version 3.0.0-*` is not affected too.
It seems that the one for `.NET Core 3.1` is `dotnet-ef 3.1.0`.

I think this issue a typo `netcoreapp2.1` instead of `netcoreapp3.0`.

**Comment by ffloimair** [comment] 2019-11-19 12:55
Guess there is a bug that was meant to be netcoreapp >= 2.1 instead of netcoreapp == 2.1.
3.0.0 also shows netcoreapp2.1 as dependency but works as expected

**Comment by ajcvickers** [comment] 2019-11-19 19:23
@bricelam @Pilchie @dougbu Looks possible from this that the package for `dotnet-ef` was not built correctly.

**Comment by ErikEJ** [comment] 2019-11-19 19:36
![image](https://user-images.githubusercontent.com/4169187/69179574-0cc56e80-0b0c-11ea-833d-f3d7ac4f5277.png)

![image](https://user-images.githubusercontent.com/4169187/69179694-39798600-0b0c-11ea-8f0e-42443814dda4.png)

**Comment by Pilchie** [comment] 2019-11-20 01:10
I'm assuming we didn't make any changes to `dotnet-ef` in 3.0.1?  Should we just unlist the package and tell people to keep using the 3.0.0 version?

**Comment by bricelam** [comment] 2019-11-20 02:06
I fixed the package in master for 3.1.0-preview2, but it looks like it also got broken in release/3.0. I can backport the fix.

**Comment by andre-dasilva** [comment] 2019-11-20 15:17
Does someone know when this issue will be fixed?

**Comment by bricelam** [comment] 2019-11-20 15:31
@Pilchie Is unlisting enough to prevent `dotnet tool install` from picking it? I suppose it will be once we ship 3.1.0.

**Comment by Pilchie** [comment] 2019-11-20 15:43
I think it will, but looping in @nguerrera to confirm.

**Comment by nguerrera** [comment] 2019-11-20 15:45
@wli3

**Comment by nguerrera** [comment] 2019-11-20 15:50
I don’t know so I’ve added Will to confirm

**Comment by Kant8** [comment] 2019-11-20 15:51
Right now without 3.0.1 you cannot run `dotnet ef` commands when on .net core 3.0.100. You get smth like this
`The EF Core tools version '3.0.0' is older than that of the runtime '3.0.1'. Update the tools for the latest features and bug fixes.`

**Comment by ajcvickers** [comment] 2019-11-20 16:44
@bricelam Presumably the workaround for anyone hitting this is to install the 3.0.0 version explicitly?

```
dotnet tool install --global dotnet-ef --version 3.0.0
```

**Comment by derekforeman** [comment] 2019-11-20 16:49
I've got 3.0.0 installed and it still errors with. 

"The EF Core tools version '3.0.0' is older than that of the runtime '3.0.1'. Update the tools for the latest features and bug fixes."

**Comment by wli3** [comment] 2019-11-20 16:59
@nkolev92 can unlist stop nuget restore "*" that version? I heard from Gallery folks that unlist only controls nuget.org's search

**Comment by dougbu** [comment] 2019-11-20 17:09
@Kant8 and @derekforeman I have the `3.0.0` version of `dotnet-ef` installed as well as the `3.0.100` SDK. I'm not seeing the inability to roll forward you describe.
```
> dotnet --version
3.0.100

> dotnet ef --version
Entity Framework Core .NET Command-line Tools
3.0.0

> dotnet ef migrations list
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
00000000000000_CreateIdentitySchema
```
What's different in your environment?

**Comment by joshuasnyder** [comment] 2019-11-20 18:41
When taking ajcvickers recommendation to explicitly install 3.0.0, I no longer receive the error message.

**Comment by Pilchie** [comment] 2019-11-20 18:48
Tagging @JunTaoLuo who was interested in this.

**Comment by nkolev92** [comment] 2019-11-20 19:40
> @nkolev92 can unlist stop nuget restore "*" that version? I heard from Gallery folks that unlist only controls nuget.org's search

That is correct, unlist only affects search.

**Comment by KbKev78** [comment] 2019-11-21 02:49
In my Azure Devops Pipeline I have a task using EF-Migrations-Script-Generator-Task. This task has a checkbox to install dotnet-ef for Core 3.x projects
![image](https://user-images.githubusercontent.com/32636605/69299721-fc70d900-0c5c-11ea-951a-81bd327b2cf9.png)

... but this now fails because it is installing dotnet-ef 3.0.1

I have unchecked that option the added another task before:
![image](https://user-images.githubusercontent.com/32636605/69299764-18747a80-0c5d-11ea-9def-f98b375aeedf.png)

My Pipeline is now building again. Obviously I'm keen to undo this when the "latest version" option works, but it will suffice for now.

**Comment by lavanyadavluri** [comment] 2019-11-21 04:41
dotnet tool install -g --version 1.1.0-pre dotnet-ef

**Comment by Kant8** [comment] 2019-11-21 08:31
@dougbu Completely the same, but I also had Microsoft.EntityFrameworkCore.SqlServer of version 3.0.1. I've downgraded this one too and now everything works perfectly.

**Comment by miguellira** [comment] 2019-11-21 22:13
I have both the `3.0.100` and `3.0.101` SDKs installed so I pegged my project to the `3.0.100` SDK by placing a `global.json` file in my root with the following:
```json
{
  "sdk": {
    "version": "3.0.100"
  }
}
```
and then ran the command @ajcvickers suggested [above](https://github.com/aspnet/EntityFrameworkCore/issues/18977#issuecomment-556092925).

Hopefully `3.1` ships soon so we can forget about `3.0` 😃

**Comment by lautarogalancid** [comment] 2019-11-23 23:53
use

> dotnet tool install --global dotnet-ef --version 3.0

for now

**Comment by pekspro** [comment] 2019-11-24 08:30
@KbKev78, I’ve updated [EF-Migrations-Script-Generator-Task](https://marketplace.visualstudio.com/items?itemName=pekspro.pekspro-efcore-migration-script-generator)  so you are able to specify which version of dotnet-ef to be install. If you enter 3.0.0 you should be fine. I hope this makes the problem easier to deal with until it’s solved.

**Comment by KbKev78** [comment] 2019-11-26 07:01
@pekspro,

> @KbKev78, I’ve updated [EF-Migrations-Script-Generator-Task](https://marketplace.visualstudio.com/items?itemName=pekspro.pekspro-efcore-migration-script-generator) so you are able to specify which version of dotnet-ef to be install. If you enter 3.0.0 you should be fine. I hope this makes the problem easier to deal with until it’s solved.

Nice job, thanks.
I have now removed that additional step.

Once the underlying issue is resolved I will clear that version number.

Oh, and that's a nice plugin, by the way. Cheers.

**Closed** 2019-11-26 22:00 UTC
Labels: Servicing-consider, closed-fixed, customer-reported, type-bug

**Comment by sibeliuz** [comment] 2019-11-28 10:14
I have "dotnet ef" version 3.0.0 installed. Now command "dotnet ef dbcontext scaffold ..." stopped working, giving this message: "The EF Core tools version '3.0.0' is older than that of the runtime '3.0.1'. Update the tools for the latest features and bug fixes."

**Comment by Kant8** [comment] 2019-11-28 15:27
@sibeliuz check you do not have any EFCore related dependencies in project of version 3.0.1. You probably have Microsoft.EntityFrameworkCore.Design 3.0.1 (or ...SqlServer, etc.)

**Comment by smitpatel** [comment] 2019-12-05 23:37
> The EF Core tools version '3.0.0' is older than that of the runtime '3.0.1'. Update the tools for the latest features and bug fixes.

For me it is just a warning, and command still works after printing it.

**Comment by alexandra142** [comment] 2019-12-06 15:00
It is weird,but for me helped add 
            var connectionString = Configuration.GetConnectionString("IdentityServerConnection");
            services.AddDbContext<ApplicationDbContext>(options => ...
I've used different DbContext here before.

**Comment by chungonion** [comment] 2019-12-11 03:02
> > The EF Core tools version '3.0.0' is older than that of the runtime '3.0.1'. Update the tools for the latest features and bug fixes.
> 
> For me it is just a warning, and command still works after printing it.

Yes, it turns out **it is just a warning** and everything functioned as intended for me.

I am not sure whether it is appropriate to make suggestion here, and I found that this message is extremely confusing and lack of explaining what's happening underneath. If this message is only intended as a warning, then at a minimal extent, it should has some sort of hints (i.e. [WARNING]) to tell the user it is a warning indeed,

Thanks!

**Comment by ajcvickers** [comment] 2019-12-11 17:21
@chungonion It's not actually even a warning. It's just letting you know that you're not running the latest so you won't be getting the latest features and bug fixes.

**Comment by chungonion** [comment] 2019-12-12 00:37
> @chungonion It's not actually even a warning. It's just letting you know that you're not running the latest so you won't be getting the latest features and bug fixes.
@ajcvickers That's why some sort of indications should be displayed in the terminal

**Comment by catalin27es** [comment] 2019-12-16 17:11
I follow the suggestion from here:
https://github.com/aspnet/EntityFrameworkCore/issues/18977#issuecomment-556092925
and the error was gone. 
Now, I can run the entity framework command line interface.

**Comment by mahrijemalsaparova** [comment] 2020-07-29 18:17
In  .csproj file: 
 <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0"/>
 <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0"/>

it helps me. i guess they have to be same version.

**Comment by mahrijemalsaparova** [comment] 2020-07-29 18:19
in .csproj file:

`<PackageReference `Include="Microsoft.EntityFrameworkCore"` Version="3.0.0"/>`
` <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0"/>`

it helps me. i guess they have to be same version.

**Comment by juliofalbo** [comment] 2020-09-16 14:44
I just started a completely new webapi via Visual Studio and I'm getting the error below when I'm trying to install dotnet-ef 3.1.8

```
Package dotnet-ef 3.1.8 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package dotnet-ef 3.1.8 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any
Invalid project-package combination for dotnet-ef 3.1.8. DotnetToolReference project style can only contain references of the DotnetTool type 
```

**Comment by dougbu** [comment] 2020-09-16 17:10
@juliofalbo **Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem
