### ISSUE TITLE
Incorrect translation of cast inside an aggregate

### ISSUE THREAD

**Issue by AlirezaHaghshenas** [aspnet/EntityFrameworkCore#13885] opened 2018-11-05 11:28 UTC
The sample code I've provided below, should create this sql

```sql
SELECT SUM(cast([x].[Amount] as BigInt))
FROM [Payments] AS [x]
```
but instead creates 

```sql
SELECT SUM([x].[Amount])
FROM [Payments] AS [x]
```

which will result in arithmetic overflow exception.

```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace EfCoreBugs
{
  class Program
  {
    static void Main(string[] args)
    {
      using (var dbContext = new MyDbContext())
      {
        Console.WriteLine(dbContext.Payments.Sum(x => (long?)x.Amount));
      }
      Console.ReadLine();
    }

    public class MyDbContext : DbContext
    {
      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
        optionsBuilder.UseSqlServer(@"Server=.;Database=EfCoreBugs;Trusted_Connection=True;MultipleActiveResultSets=True;");
      }
      public DbSet<Payment> Payments { get; set; }
    }

    public class Payment
    {
      public int Id { get; set; }
      public int Amount { get; set; }
    }
  }
}
```

### Further technical details
EF Core version: 2.1.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.9

**Comment by AlirezaHaghshenas** [comment] 2018-11-05 11:51
Apparently, a workaround (to prevent arithmetic overflow) is to use: 

```c#
dbContext.Payments.Sum(x => Convert.ToIn64(x.Amount))
```

**Comment by bricelam** [comment] 2018-11-05 18:01
Dupe of #10642?

**Comment by ajcvickers** [comment] 2018-11-05 19:36
@smitpatel to check for duplicate.

**Comment by smitpatel** [comment] 2018-11-05 20:12
Closely related to #13587 (which I was thinking as dupe)

After #13587 is fixed, if you apply cast which would have impact, we preserved it. In above case if you are casting a long column to int before summing up, it would include the cast.

In this particular case, we did not add cast, since converting int to long has no effect, except for the case of aggregate operator which we don't know about when we are making the decision to add cast.

**Closed** 2019-09-19 00:13 UTC
Labels: closed-fixed, customer-reported, type-bug
