### ISSUE TITLE
Long Load Times For Large Datasets - Possible Solution?

### ISSUE THREAD

**Issue by cculver** [aspnet/EntityFrameworkCore#13518] opened 2018-10-05 17:30 UTC
I'm a relative novice to EF and EF Core, but one of the things that has been really bothering me is the amount of time it takes me to load a large dataset. Googling this, it seems to bother quite a few people. It may be clear to everyone developing the project what's causing this slowdown, but I wanted to start a discussion in case it isn't, and hopefully work towards a solution that makes the project better.

Reading about common frustrations with EF Core, you'll find that most people suggest that to decrease load time for large datasets that you don't intend on changing, you should set:
```
Context.ChangeTracker.AutoDetectChangesEnabled = false;
Context.ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
```
After trying to load a dataset 1.6M rows deep with these options set as listed, I still found the performance to be less than stellar. SQL Server Express will return these rows to me in a mere 20 seconds, but the total time to load them using EF was 428 seconds.

So, I cloned the most current version of the code and added it to my project. After stepping through everything, I found that there is a reason: a relatively hidden function in EFCore, Microsoft.EntityFrameworkCore.Query.Internal.WeakReferenceIdentityMap<TKey>.CollectGarbage()

Since I've not been around this project for a while, I can't speak to this function's necessity. But because I did load up the code, I was able to gather some empirical statistics surrounding my particular dataset with and without this function call. Below, you'll find two images illustrating the cumulative and incremental time taken inside the entity framework code to load the entire dataset into memory. Each image shows two series: one with CollectGarbage() enabled, and one with the call to CollectGarbage() commented out.

![image](https://user-images.githubusercontent.com/1117512/46549859-5e2b8380-c8a1-11e8-83f2-f0cde1394014.png)
![image](https://user-images.githubusercontent.com/1117512/46549864-61bf0a80-c8a1-11e8-92f6-a42195d325ff.png)

As you can plainly see, this function seems to be adding O(N^2) complexity to basic loading of entities. An inspection of the offending function yields a little insight. Every 500 rows loaded will cause an inspection of the full array of already-loaded objects. 

```
        private const int IdentityMapGarbageCollectionThreshold = 500;
...
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void CollectGarbage()
        {
            if (++_identityMapGarbageCollectionIterations == IdentityMapGarbageCollectionThreshold)
            {
                var deadEntries = new List<TKey>();

                foreach (var entry in _identityMap)
                {
                    if (!entry.Value.TryGetTarget(out _))
                    {
                        deadEntries.Add(entry.Key);
                    }
                }

                foreach (var keyValue in deadEntries)
                {
                    _identityMap.Remove(keyValue);
                }

                _identityMapGarbageCollectionIterations = 0;
            }
        }
```

That's basically my report. I don't know if anything can be done about this, because simply I don't understand the ramifications of removing it or disabling it. If there are few ramifications and we could have the option to disable this feature at the very least, I am certain many users would appreciate it.

### Further technical details
EF Core version: 2.2.0-preview2-35143
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win 10 Pro 
IDE: (e.g. Visual Studio 2017 15.9.0 Preview 3.0)

**Comment by ajcvickers** [comment] 2018-10-06 02:03
@cculver Also, thanks for the epic filing. The graphs are compelling. :clap:

**Comment by davidroth** [comment] 2018-10-10 14:14
@ajcvickers I have a question regarding your statement  _"For 3.0, we will stop doing identity resolution for no-tracking queries."_.

Does this mean that you plan to completely remove identity resolution in combination with AsNotTracking in 3.0, without an option to enable it?

I would not be happy if this would be removed without an option to enable it.

The documentation of `QueryTrackingBehavior.NoTracking` clearly states that:

`Identity resolution will still be performed to ensure that all occurrences of an entity with a given key in the result set are represented by the same entity instance.`

Please consider adding a new Option `QueryTrackingBehavior.NoTrackingNoIdentityTracking`.  
Benefits:

- No breaking change, usage of NoTracking and identity resolution is a good thing for some scenarios
- Still allow users to disable identity tracking, if they see a performance improvements.
- Can reduce memory usage + GC-Time if specific instances are very common in a query (ex. a company query where most companies reference the same country).

**Comment by ajcvickers** [comment] 2018-10-10 16:19
@davidroth Tracking queries will still do full identity resolution. In essence, no tracking queries were trying to behave like tracking queries in this respect, since normally the tracking is what provides the identity resolution.

**Comment by davidroth** [comment] 2018-10-10 17:12
@ajcvickers So to recap, NoTracking in EF 3.0 will not perform any identity resolution, right? Will we have at least identity resolution within each materialisation phase (per query) when using NoTracking?

**Comment by ajcvickers** [comment] 2018-10-10 17:28
@davidroth Current plan is to go back to the EF6 way of doing things for this, so no.

**Comment by divega** [comment] 2018-10-10 19:53
@davidroth after this change is effective, if you want a query to execute with identity resolution within its results, but without interfering with the context’s state, you can still do so by executing the query on a separate DbContext instance. I wonder if we can make that easier than it is now. I am also curious what kind of queries you are concerned about returning duplicate instances.

**Comment by davidroth** [comment] 2018-10-11 08:31
@divega  Nothing specific in my mind. I was just thinking, that there might be usages in disconnected scenarios, where one would like to have the combination of "NoChangeTracking + IdentityTracking" (Better query performance because no ChangeTracking is involved but still have unique instances in the resulting graph).

Sure, spinning up a new context with Tracking enabled, will give you Identity tracking. But this always comes with the price of populating EntityEntries with Old/NewValues etc.

**Comment by ajcvickers** [comment] 2019-01-31 21:16
Note from planning: I re-tested the behavior in EF6 and confirmed that it does not do any identity resolution beyond a single navigation. For example, with this model:
```C#
public class Blog
{
    public int Id { get; set; }

    public ICollection<Post> Posts { get; set; }
    public ICollection<Post> MasterPosts { get; set; }
}

public class Post
{
    public int Id { get; set; }

    public int? BlogId { get; set; }
    public Blog Blog { get; set; }

    public int? MasterBlogId { get; set; }
    public Blog MasterBlog { get; set; }
}
```
And this query:
```C#
var blogs = context.Blogs
    .AsNoTracking()
    .Include(e => e.Posts.Select(p => p.MasterBlog))
    .ToList();
```
Note that:
* Fixup between Blog and Posts is correct in both directions
* Fixup between Post and MasterBlog is correct in both directions
* But, there are two different instances of Blog for the two relationships, even though these are the same entity.
![image](https://user-images.githubusercontent.com/1430078/52085859-65feea00-255a-11e9-8376-4553e742d63a.png)

**Comment by smitpatel** [comment] 2019-01-31 21:34
@ajcvickers - For query like `context.Posts.AsNoTracking().Include(p => p.Blog)` are all the posts of single blog refers to same blog in their navigation?

**Comment by ajcvickers** [comment] 2019-01-31 21:47
@smitpatel Nope.
![image](https://user-images.githubusercontent.com/1430078/52087588-b8daa080-255e-11e9-9c99-304b8f1b2248.png)

**Comment by ajcvickers** [comment] 2019-02-01 18:11
@davidroth That's essentially what we try to do now. But it's added complexity, which leads to bugs like this one, for something that we don't think is especially useful. We could always revisit this in the future, but for now we think it's more pragmatic to go back to very simple semantics and implementation.

**Comment by ajcvickers** [comment] 2019-05-12 00:04
The query pipeline no longer does identity resolution for no-tracking queries, so closing this.

**Comment by ajcvickers** [comment] 2019-08-05 19:45
Re-opening: breaking change documentation is missing.

**Closed** 2019-08-09 20:49 UTC
Labels: breaking-change, closed-fixed, customer-reported, type-enhancement
