### ISSUE TITLE
SQLite: Client-eval OrderBy() on DateTimeOffset, decimal, TimeSpan & ulong

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#11925] opened 2018-05-07 16:58 UTC
#11889 updates `<`, `<=`, `>`, `>=`, MIN & MAX to client-eval on these types. Should we do the same for `ORDER BY`?

**Comment by smitpatel** [comment] 2019-01-25 01:06
Possible duplicate of #10265

**Comment by bricelam** [comment] 2019-06-20 21:01
@smitpatel Are Average, Max, Min, and Sum regressed in 3.0? If not, I think we can punt this.

**Comment by smitpatel** [comment] 2019-06-20 21:11
Aggregate are not blocked right now. It can be done once we refactor for GroupBy aggregate support.

**Comment by divega** [comment] 2019-06-24 04:05
Clearing up milestone so we can decide what to do in triage.

**Closed** 2019-08-16 16:39 UTC
Labels: closed-fixed, type-bug

**Comment by Ignatella** [comment] 2020-09-17 12:01
And TimeSpan OrderBy still does not work

**Comment by ajcvickers** [comment] 2020-09-17 19:22
@Ignatella Please file a new issue and attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by bricelam** [comment] 2020-09-22 19:42
@Ignatella After #18844, you could do `.OrderBy(e => e.TimeSpan.TotalDays)`
