### ISSUE TITLE
2.2.6 migrations fail after upgrade to 3.0.0 if model has nested owned types

### ISSUE THREAD

**Issue by mcetkovsky** [aspnet/EntityFrameworkCore#18183] opened 2019-10-02 10:23 UTC
`Add-Migration` fails after upgrading a project from 2.2.6 to 3.0.0 if the project contains nested owned entities.

### Steps to reproduce

What steps can we follow to reproduce the issue?

1. Open the [attached solution](https://github.com/aspnet/EntityFrameworkCore/files/3680581/EFCoreOwnTypesTest.zip) with a .NET Core 2.2 project
2. Run `Add-Migration InitialMigration`
3. Upgrade the project to .NET Core 3.0 
   - Edit `EFCoreOwnTypesTest.csproj` and replace `netcoreapp2.2` with `netcoreapp3.0` and all `2.2.6` with `3.0.0`
   - Edit `OrderConfiguration.cs` and replace all `ReferenceOwnershipBuilder` with `OwnedNavigationBuilder`
    - Save changes in both files
4. Run `Add-Migration -v AfterUpgrade`

The second `Add-Migration` call fails complaining that 
`The type 'EFCoreOwnTypesTest.Buyer' cannot be configured as non-owned because an owned entity type with the same name already exists.`.
(stack trace bellow)

Further steps shows that the exception is not thrown if migrations are generated directly using .NET Core 3.0, i.e. the exception is specific to upgrade scenarios only. However, there seems to be an additional cache-like issue affecting the steps.

5. Delete the Migrations folder so the project is again without any migrations
6. Run `Add-Migration -v CleanMigration`

The third `Add-Migration` call fails complaining that 
`The type 'EFCoreOwnTypesTest.Buyer' cannot be configured as non-owned because an owned entity type with the same name already exists.`.
(stack trace bellow)
Remember, the project is now based on .NET Core 3.0

7. Close Visual Studio
8. Start Visual Studio and reopen the solution 
9. Run `Add-Migration -v CleanMigration`

The `Add-Migration` command now succeeds even the code and the configuration is the same as when performing the step 6.

I'm not sure whether this step 6 vs step 9 difference in results is a separate issue or not.

### Stack trace

```
PM> Add-Migration -v AfterUpgrade
Using project 'EFCoreOwnTypesTest'.
Using startup project 'EFCoreOwnTypesTest'.
Build started...
Build succeeded.
C:\Program Files\dotnet\dotnet.exe exec --depsfile c:\Users\user\Repos\EFCoreOwnTypesTest\bin\Debug\netcoreapp3.0\EFCoreOwnTypesTest.deps.json --additionalprobingpath C:\Users\alik\.nuget\packages --additionalprobingpath "C:\Program Files\dotnet\sdk\NuGetFallbackFolder" --runtimeconfig c:\Users\user\Repos\EFCoreOwnTypesTest\bin\Debug\netcoreapp3.0\EFCoreOwnTypesTest.runtimeconfig.json C:\Users\user\.nuget\packages\microsoft.entityframeworkcore.tools\3.0.0\tools\netcoreapp2.0\any\ef.dll migrations add AfterUpgrade --json --verbose --no-color --prefix-output --assembly c:\Users\user\Repos\EFCoreOwnTypesTest\bin\Debug\netcoreapp3.0\EFCoreOwnTypesTest.dll --startup-assembly c:\Users\user\Repos\EFCoreOwnTypesTest\bin\Debug\netcoreapp3.0\EFCoreOwnTypesTest.dll --project-dir c:\Users\alik\Repos\EFCoreOwnTypesTest\ --language C# --working-dir C:\Users\user\Repos\EFCoreOwnTypesTest --root-namespace EFCoreOwnTypesTest
Using assembly 'EFCoreOwnTypesTest'.
Using startup assembly 'EFCoreOwnTypesTest'.
Using application base 'c:\Users\user\Repos\EFCoreOwnTypesTest\bin\Debug\netcoreapp3.0'.
Using working directory 'c:\Users\user\Repos\EFCoreOwnTypesTest'.
Using root namespace 'EFCoreOwnTypesTest'.
Using project directory 'c:\Users\user\Repos\EFCoreOwnTypesTest\'.
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Found IDesignTimeDbContextFactory implementation 'MyDbContextDesignFactory'.
Found DbContext 'MyDbContext'.
Finding application service provider...
Finding Microsoft.Extensions.Hosting service provider...
No static method 'CreateHostBuilder(string[])' was found on class 'Program'.
No application service provider was found.
Finding DbContext classes in the project...
Using DbContext factory 'MyDbContextDesignFactory'.
Using context 'MyDbContext'.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding design-time services referenced by assembly 'EFCoreOwnTypesTest'.
No referenced design-time services were found.
Finding IDesignTimeServices implementations in assembly 'EFCoreOwnTypesTest'...
No design-time services were found.
'MyDbContext' disposed.
System.InvalidOperationException: The type 'EFCoreOwnTypesTest.Buyer' cannot be configured as non-owned because an owned entity type with the same name already exists.
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity& type, ConfigurationSource configurationSource, Nullable`1 shouldBeOwned)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(String name, ConfigurationSource configurationSource, Nullable`1 shouldBeOwned)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.OwnedNavigationBuilder.FindRelatedEntityType(String relatedTypeName, String navigationName)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.OwnedNavigationBuilder.HasOne(String relatedTypeName, String navigationName)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.OwnedNavigationBuilder.HasOne(String navigationName)
   at EFCoreOwnTypesTest.Migrations.MyDbContextModelSnapshot.<>c.<BuildModel>b__0_3(OwnedNavigationBuilder b2) in c:\Users\user\Repos\EFCoreOwnTypesTest\Migrations\MyDbContextModelSnapshot.cs:line 62
   at Microsoft.EntityFrameworkCore.Metadata.Builders.OwnedNavigationBuilder.OwnsOne(String ownedTypeName, String navigationName, Action`1 buildAction)
   at EFCoreOwnTypesTest.Migrations.MyDbContextModelSnapshot.<>c.<BuildModel>b__0_2(OwnedNavigationBuilder b1) in c:\Users\user\Repos\EFCoreOwnTypesTest\Migrations\MyDbContextModelSnapshot.cs:line 49
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.OwnsOne(String ownedTypeName, String navigationName, Action`1 buildAction)
   at EFCoreOwnTypesTest.Migrations.MyDbContextModelSnapshot.<>c.<BuildModel>b__0_1(EntityTypeBuilder b) in c:\Users\user\Repos\EFCoreOwnTypesTest\Migrations\MyDbContextModelSnapshot.cs:line 34
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity(String name, Action`1 buildAction)
   at EFCoreOwnTypesTest.Migrations.MyDbContextModelSnapshot.BuildModel(ModelBuilder modelBuilder) in c:\Users\user\Repos\EFCoreOwnTypesTest\Migrations\MyDbContextModelSnapshot.cs:line 32
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot.CreateModel()
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot.get_Model()
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The type 'EFCoreOwnTypesTest.Buyer' cannot be configured as non-owned because an owned entity type with the same name already exists.
```

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: NET Core 3.0
Operating system: Windows 10 1903
IDE: Visual Studio 2019 16.3.2
[EFCoreOwnTypesTest.zip](https://github.com/aspnet/EntityFrameworkCore/files/3680581/EFCoreOwnTypesTest.zip)

**Comment by dandenton** [comment] 2019-10-02 15:51
It's probably not the best workaround but after getting that error I found the v2.2.0 `HasOne()` line referenced in the ModelSnapshot.cs file for the owned type (found from the stack trace) and replaced it manually with the v3.0 `WithOwner()`.  After that Add-Migration worked.  To fix the attached example you'd change line 62 from
```C#
b2.HasOne("EFCoreOwnTypesTest.Buyer")
	.WithOne("Address")
	.HasForeignKey("EFCoreOwnTypesTest.Address", "BuyerOrderId")
	.OnDelete(DeleteBehavior.Cascade);
```
to

```C#
b2.WithOwner()
	.HasForeignKey("BuyerOrderId");
```

**Comment by AndriySvyryd** [comment] 2019-10-03 01:12
@dandenton This is by design and that's the best workaround.

**Comment by dandenton** [comment] 2019-10-03 01:33
@AndriySvyryd Should the [breaking changes document](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-3.0/breaking-changes#config) be updated to state that all existing migrations also need to be updated and not just the current configuration?   The way I read the document was that only your current configuration would need to change.  I assumed that a migration's `Designer.cs` file would ever need to be manually updated.  Is there no way to use the legacy model building using the product version stored with the migration's snapshot?

**Comment by AndriySvyryd** [comment] 2019-10-03 01:51
@mcetkovsky I forgot to mention that when upgrading to 3.0 you need to close and reopen VS to load the correct ef tools
@dandenton Are you saying that old migrations don't work even after closing and reloading VS?

**Comment by dandenton** [comment] 2019-10-03 02:09
Yes.  The error always occurs even after an update/restart.  It also happens when you script migrations using the 3.0 tool against migrations created with version 2.2.6-servicing-10079.

**Comment by mcetkovsky** [comment] 2019-10-03 05:16
@AndriySvyryd The 3.0 tools were loaded without needed to restart VS. However, they were still using no-longer-present deleted files from the deleted Migrations folder until the VS was restarted.

**Closed** 2019-10-23 23:10 UTC
Labels: closed-fixed, customer-reported, type-bug
