### ISSUE TITLE
InMemory database throwing NullReferenceException when using a nullable value-converted property in a query

### ISSUE THREAD

**Issue by klafa** [aspnet/EntityFrameworkCore#25492] opened 2021-08-11 12:29 UTC
When upgrading our application to EF Core 5, we encountered problems when using the InMemory database on an entity class that contains a (non-required) property which is value-converted from string to a custom data class.

We managed to reduce our production code to a very simplified program that exhibits the problem.

Any help with this is greatly appreciated!

## Reproduction code

The following program works with EF Core 3.1 but breaks with EF Core 5.0 and InMemoryDb:

```C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

public static class Program
{
    static void Main(string[] args)
    {
        // Use SQL server -- this works
        var sqlContext = new FooDbContext(new DbContextOptionsBuilder<FooDbContext>()
            .UseSqlServer("Server=(localdb)\\MSSQLLocalDB;Database=EfCoreIssueTestDb").Options);
        Test(sqlContext);

        // Use InMemoryDB -- this breaks
        var inMemoryContext = new FooDbContext(new DbContextOptionsBuilder<FooDbContext>().UseInMemoryDatabase("EfCoreIssueTestDb").Options);
        Test(inMemoryContext);
    }

    private static void Test(FooDbContext context)
    {
        Console.WriteLine($"Testing with database provider {context.Database.ProviderName}");
        context.Database.EnsureDeleted();
        context.Database.EnsureCreated();

        context.Device.Add(new Device { NetworkId = null });
        context.Device.Add(new Device { NetworkId = new NetworkId("x") });
        context.Device.Add(new Device { NetworkId = new NetworkId("y") });
        context.Device.Add(new Device { NetworkId = null });
        context.Device.Add(new Device { NetworkId = null });
        context.SaveChanges();

        Console.WriteLine($"We have {context.Device.Count(_ => _.NetworkId != null)} Devices with a NetworkId.");
        Console.WriteLine($"We have {context.Device.Count(_ => _.NetworkId == null)} Devices without a NetworkId.");
        Console.WriteLine();
    }
}

public class FooDbContext : DbContext
{
    public FooDbContext(DbContextOptions<FooDbContext> options) : base(options)
    {
    }

    public DbSet<Device> Device { get; set; }

    protected override void OnModelCreating(ModelBuilder model)
    {
        base.OnModelCreating(model);

        model.Entity<Device>(entity =>
        {
            entity.HasKey(_ => _.Id);

            entity.Property(_ => _.NetworkId)
                .HasConversion(new ValueConverter<NetworkId, string>(
                    bar => bar != null ? bar.ToString() : null,
                    str => str != null ? new NetworkId(str) : null));
        });
    }
}

public class Device
{
    public int Id { get; set; }

    public NetworkId NetworkId { get; set; }
}

public class NetworkId
{
    private readonly string _eui;

    public NetworkId(string eui) => _eui = eui;

    public override string ToString() => _eui;

    private bool Equals(NetworkId other) => other != null && Equals(_eui, other._eui);

    public override bool Equals(object obj) => ReferenceEquals(this, obj) || (obj is NetworkId other && Equals(other));

    public override int GetHashCode() => _eui != null ? _eui.GetHashCode() : 0;

    public static NetworkId FromString(string s) => s != null ? new NetworkId(s) : null;

    public static bool operator ==(NetworkId left, NetworkId right)
    {
        return Equals(left, right);
    }

    public static bool operator !=(NetworkId left, NetworkId right)
    {
        return !Equals(left, right);
    }

    public static explicit operator string(NetworkId networkId)
    {
        return networkId?.ToString();
    }

    public static explicit operator NetworkId(string s)
    {
        return FromString(s);
    }
}
```

Project file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="5.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.9" />
    </ItemGroup>
</Project>
```

### Output with EF Core version 5.0.9

```
Testing with database provider Microsoft.EntityFrameworkCore.SqlServer
We have 2 Devices with a NetworkId.
We have 3 Devices without a NetworkId.

Testing with database provider Microsoft.EntityFrameworkCore.InMemory
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.WhereListIterator`1.GetCount(Boolean onlyIfCheap)
   at lambda_method(Closure )
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryExpression.ResultEnumerable.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextHelper()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source, Expression`1 predicate)
   at Program.Test(FooDbContext context) in C:\dev\hagleitner\scratch\EFCoreIssue\Program.cs:line 33
   at Program.Main(String[] args) in C:\dev\hagleitner\scratch\EFCoreIssue\Program.cs:line 17
```

### Program output with EF Core version 3.1.18
```
Testing with database provider Microsoft.EntityFrameworkCore.SqlServer
We have 2 Devices with a NetworkId.
We have 3 Devices without a NetworkId.

Testing with database provider Microsoft.EntityFrameworkCore.InMemory
We have 2 Devices with a NetworkId.
We have 3 Devices without a NetworkId.
```

## Further observations

* The problem goes away when removing the `public override bool Equals(object obj)` method from the `NetworkId` class.

* However, stepping through with a debugger reveals that neither of the Equals method throw.

* Interestingly, the problem still persists when changing the overridden Equals method to `public override bool Equals(object obj) => base.Equals(obj)`

**Comment by ajcvickers** [comment] 2021-08-13 13:34
@klafa A workaround here is to specify a `ValueComparer<T>` along with the converter. For example:

```C#

entity.Property(_ => _.NetworkId)
    .HasConversion(new ValueConverter<NetworkId, string>(
            bar => bar != null ? bar.ToString() : null,
            str => str != null ? new NetworkId(str) : null),
        new ValueComparer<NetworkId>(
            (l, r) => (l == null && r == null) || (l != null && l.Equals(r)),
            v => v.GetHashCode()));
```

Notes for triage: I am able to reproduce this, but I don't know what is going on. It repros using the default equality methods added by R#, but only if the `==` and `!=` operators are implemted:

```C#
public class NetworkId
{
    private readonly string _eui;

    public NetworkId(string eui) => _eui = eui;

    public override string ToString() => _eui;
    
    protected bool Equals(NetworkId other)
    {
        return _eui == other._eui;
    }
    
    public override bool Equals(object obj)
    {
        if (ReferenceEquals(null, obj)) return false;
        if (ReferenceEquals(this, obj)) return true;
        if (obj.GetType() != this.GetType()) return false;
        return Equals((NetworkId)obj);
    }
    
    public override int GetHashCode()
    {
        return (_eui != null ? _eui.GetHashCode() : 0);
    }
    
    public static bool operator ==(NetworkId left, NetworkId right)
    {
        return Equals(left, right);
    }
    
    public static bool operator !=(NetworkId left, NetworkId right)
    {
        return !Equals(left, right);
    }
}
```

Stack trace is:

```
Testing with database provider Microsoft.EntityFrameworkCore.InMemory
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method30(Closure , ValueBuffer )
   at System.Linq.Enumerable.WhereListIterator`1.GetCount(Boolean onlyIfCheap)
   at lambda_method29(Closure )
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryExpression.ResultEnumerable.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextHelper()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source, Expression`1 predicate)
   at Program.Test(FooDbContext context) in C:\local\AllTogetherNow\FiveOh\Program.cs:line 71
   at Program.Main(String[] args) in C:\local\AllTogetherNow\FiveOh\Program.cs:line 55
```

**Comment by smitpatel** [comment] 2021-08-13 16:25
https://github.com/dotnet/efcore/blob/eb9a2b8ac70dc1736e49302d19d76ad3186b4744/src/EFCore.InMemory/Query/Internal/InMemoryExpressionTranslatingExpressionVisitor.cs#L215-L221

My bet is that we shouldn't pass `binaryExpression.Method` arg if there is a property on left/right which has value converter but no value comparer as it would be using wrong methodInfo to compare even after conversion.

**Comment by smitpatel** [comment] 2021-08-17 20:34
The issue turns out to be not in query.
Root cause is the Equality comparison of `(v1, v2) => v1.Equals(v2)` coming from value comparer. We replace `v1` with the value coming from database which is indeed null throwing NRE. Since user didn't configure a value comparer we gave it a default one but  looks like we are not taking care of nulls properly here.

The overloaded Equality operators twist this thing.
`networkId == null` when `==` overloaded uses that method info so both sides have `NetworkId` type and which matches the comparer types and we use the value comparer as above throwing error.
If overloaded operators are removed then it uses default operators where right side has type `object` which doesn't match comparer type and we bypass using comparer and end up using the overloaded method call which works without throwing NRE. (not sure if it gives correct results)

**Comment by smitpatel** [comment] 2021-08-17 20:35
Test in QueryBugsInMemoryTest
```C#
        #region Issue23934

        [ConditionalFact]
        public virtual void Test()
        {
            using (CreateScratch<MyContext25492>(Seed25492, "25492"))
            {
                using var context = new MyContext25492();

                Assert.Equal(2, context.Device.Count(_ => _.NetworkId != null));
                Assert.Equal(3, context.Device.Count(_ => _.NetworkId == null));
            }
        }

        private static void Seed25492(MyContext25492 context)
        {
            context.Device.Add(new Device { NetworkId = null });
            context.Device.Add(new Device { NetworkId = new NetworkId("x") });
            context.Device.Add(new Device { NetworkId = new NetworkId("y") });
            context.Device.Add(new Device { NetworkId = null });
            context.Device.Add(new Device { NetworkId = null });

            context.SaveChanges();
        }

        private class Device
        {
            public int Id { get; set; }

            public NetworkId NetworkId { get; set; }
        }

        private class NetworkId
        {
            private readonly string _eui;

            public NetworkId(string eui) => _eui = eui;

            public override string ToString() => _eui;

            private bool Equals(NetworkId other) => other != null && Equals(_eui, other._eui);

            public override bool Equals(object obj) => ReferenceEquals(this, obj) || (obj is NetworkId other && Equals(other));

            public override int GetHashCode() => _eui != null ? _eui.GetHashCode() : 0;

            public static NetworkId FromString(string s) => s != null ? new NetworkId(s) : null;

            public static bool operator ==(NetworkId left, NetworkId right)
            {
                return Equals(left, right);
            }

            public static bool operator !=(NetworkId left, NetworkId right)
            {
                return !Equals(left, right);
            }

            public static explicit operator string(NetworkId networkId)
            {
                return networkId?.ToString();
            }

            public static explicit operator NetworkId(string s)
            {
                return FromString(s);
            }
        }

        private class MyContext25492 : DbContext
        {
            public DbSet<Device> Device { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder
                    .UseInternalServiceProvider(InMemoryFixture.DefaultServiceProvider)
                    .UseInMemoryDatabase("25492");
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                modelBuilder.Entity<Device>(entity =>
                {
                    entity.HasKey(_ => _.Id);

                    entity.Property(_ => _.NetworkId)
                        .HasConversion(new ValueConverter<NetworkId, string>(
                            bar => bar != null ? bar.ToString() : null,
                            str => str != null ? new NetworkId(str) : null));
                });
            }
        }

        #endregion
```

**Comment by ajcvickers** [comment] 2021-08-18 09:46
Thanks @smitpatel . Assigning to me.

**Comment by klafa** [comment] 2021-08-18 12:57
Thanks @ajcvickers for providing the workaround! This enabled us to finish our upgrade to EF Core 5.

**Closed as completed** 2021-09-11 09:03 UTC
Labels: customer-reported, area-change-tracking
