### ISSUE TITLE
Table Splitting: Does not set INDENTITY on primary key

### ISSUE THREAD

**Issue by JonPSmith** [aspnet/EntityFrameworkCore#9652] opened 2017-08-31 07:54 UTC
I wrote an example of table splitting (see below) and I noticed that the primary key did not have the IDENTITY keyword on the primary key. It worked in EF Core (I assume EF Core assigned a primary key value) but it doesn't work in the database.

PS. I tried changing the primary key to `Id`, as that's what you had in your example, but it still left the IDENTITY keyword off the primary key

### Steps to reproduce
Here are my two entity classes that are mapped to the database
```c#
public class BookSummary
{
    public int BookId { get; set; }
    [Required] //#A
    [MaxLength(256)] //#B
    public string Title { get; set; }
    public string AuthorsString { get; set; }
    public BookDetail Details { get; set; }
}
```
```c#
public class BookDetail
{
    public int BookId { get; set; }
    public string Description { get; set; }
    public DateTime PublishedOn { get; set; }
    [MaxLength(64)] 
    public string Publisher { get; set; }
    public decimal Price { get; set; }
    [MaxLength(512)] 
    public string ImageUrl { get; set; }
}
```
Here are my configuration files
```c#
public class BookSummaryConfig : IEntityTypeConfiguration<BookSummary>
{
    public void Configure
        (EntityTypeBuilder<BookSummary> entity)
    {
        entity.HasKey(p => p.BookId);
        entity
            .HasOne(e => e.Details).WithOne()
            .HasForeignKey<BookDetail>(e => e.BookId);
        entity.ToTable("BookSummaryAndDetail");
    }
}
```
```c#
public class BookDetailConfig : IEntityTypeConfiguration<BookDetail>
{
    public void Configure
        (EntityTypeBuilder<BookDetail> entity)
    {
        entity.HasKey(p => p.BookId);

        entity.ToTable("BookSummaryAndDetail");
    }
}
```
When I create the database using `Database.EnsureCreated()` then the SQL that is produced is.  
Note the missing IDENTITY keyword on the end of the `BookId` column.
```SQL

Executed DbCommand (138ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
CREATE DATABASE [Test.EfCoreInActionDb.Chapter07.Ch07_CheckSqlServer.SplitOwnDbContext];
Executed DbCommand (27ms) [Parameters=[], CommandType='Text', CommandTimeout='60']
IF SERVERPROPERTY('EngineEdition') <> 5 EXEC(N'ALTER DATABASE [Test.EfCoreInActionDb.Chapter07.Ch07_CheckSqlServer.SplitOwnDbContext] SET READ_COMMITTED_SNAPSHOT ON;');
Executed DbCommand (4ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE [BookSummaryAndDetail] (
    [BookId] int NOT NULL,
    [Description] nvarchar(max) NULL,
    [ImageUrl] nvarchar(512) NULL,
    [Price] decimal(18, 2) NOT NULL,
    [PublishedOn] datetime2 NOT NULL,
    [Publisher] nvarchar(64) NULL,
    [AuthorsString] nvarchar(max) NULL,
    [Title] nvarchar(256) NOT NULL,
    CONSTRAINT [PK_BookSummaryAndDetail] PRIMARY KEY ([BookId])
);
-- other tables left out
);
```

### Further technical details
EF Core version: EF Core 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer (also wrong in Sqlite)
Operating system: Window 10
IDE: Visual Studio 2017 15.3

**Comment by JonPSmith** [comment] 2017-08-31 19:14
Hi @smitpatel,

From your example I assumed the primary key names have to be the same (you use `Id` in both classes), but I changed the `BookSummary` primary key to `BookSummaryId`  and the  `BookDetail` primary key to `BookDetailId` so they wouldn't clash.

Unfortunately that didn't fix the problem, i.e. the primary key is still not database generated.

**Comment by ajcvickers** [comment] 2017-09-02 00:11
Notes for triage:
* The property in the model is already marked as ValueGenerated.OnAdd
* Forcing store-generation with `ValueGeneratedOnAdd` doesn't change this and Identity column is still not created
* Forcing SQL Server identity column with `UseSqlServerIdentityColumn` puts the annotation on the property, but an Identity column is still not created

Leaving for re-triage since this could be a Migrations issue and the obvious workarounds don't.

**Comment by bricelam** [comment] 2017-09-13 22:46
Adding the following to `BookDetailConfig` (the dependent end) works around the issue for me.

``` csharp
entity.Property(x => x.BookId).ValueGeneratedOnAdd();
```

Without this, the property is *not* marked as `ValueGenerated.OnAdd` in the model.

**Comment by bricelam** [comment] 2017-09-13 22:48
@AndriySvyryd Is the model correct? If so, we just need to update Migrations to honor the property configuration from the owning type.

**Comment by bricelam** [comment] 2017-09-13 22:52
Simplified repro:
``` csharp
[Table("Book")]
public class BookSummary
{
    public int Id { get; set; }
}

[Table("Book")]
public class BookDetail
{
    public int Id { get; set; }
}

class BookContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BookSummary>()
            .HasOne<BookDetail>().WithOne().HasForeignKey<BookDetail>(e => e.Id);
        //modelBuilder.Entity<BookDetail>().Property(b => b.Id).ValueGeneratedOnAdd();
    }
}

class Program
{
    static void Main()
    {
        var value = new BookContext().Model.FindEntityType(typeof(BookDetail)).FindProperty("Id").ValueGenerated;
        Console.WriteLine(value);
    }
}
```

**Comment by AndriySvyryd** [comment] 2017-09-13 23:05
The model is partially correct as the dependent property shouldn't be marked as `ValueGeneratedOnAdd` since it's part of an FK, but it should be marked as Identity since all properties need to have the same facets to unify to the same column. Currently we don't have this check for Identity, but we should add it too.

**Comment by bricelam** [comment] 2017-09-13 23:20
Ok, it looks like Migrations works if the dependent property has `UseSqlServerIdentityColumn()` but `.ValueGeneratedNever()`. I'll reassign to you since it appears to be a model building issue.

**Comment by ajcvickers** [comment] 2017-09-14 00:36
This is the model I get from @bricelam's code:
```
Model: 
  EntityType: BookDetail
    Properties: 
      Id (int) Required PK FK AfterSave:Throw 0 0 0 -1 0
        Annotations: 
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.Storage.IntTypeMapping
    Keys: 
      Id PK
    Foreign keys: 
      BookDetail {'Id'} -> BookSummary {'Id'} Unique
    Annotations: 
      Relational:TableName: Book
  EntityType: BookSummary
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
    Keys: 
      Id PK
    Annotations: 
      Relational:TableName: Book
Annotations: 
  ProductVersion: 2.0.0-rtm-26452
  SqlServer:ValueGenerationStrategy: IdentityColumn
```
To me, this looks like the conceptually correct model. Specifically:
* The PK on the principal end (BookSummary) is marked as generated
* The PK on the dependent end is marked also as an FK and is not marked as generated
* IdentityColumn is set at the model layer

**Comment by AndriySvyryd** [comment] 2017-09-14 00:48
@ajcvickers But it's not correct. Model-level Identity is just the default for any key property with ValueGenerated.OnAdd. So you have one property that maps to a column with Identity and another property that maps to the same columns without Identity.

Suppose we mark both `Id` as `ValueGeneratedNever` and add another property to both of the types `SerialNumber` mapped to the same column and not part of any key. But it's configured as Identity on only one of the types. Should we just assume that the user meant to use Identity for both? We don't do this for DefaultValue and other facets.

**Comment by ajcvickers** [comment] 2017-09-14 00:57
@AndriySvyryd But if we take table splitting out of the picture, then the model is this:
```
  Model: 
  EntityType: BookDetail
    Properties: 
      Id (int) Required PK FK AfterSave:Throw 0 0 0 -1 0
        Annotations: 
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.Storage.IntTypeMapping
    Keys: 
      Id PK
    Foreign keys: 
      BookDetail {'Id'} -> BookSummary {'Id'} Unique
  EntityType: BookSummary
    Properties: 
      Id (int) Required PK AfterSave:Throw ValueGenerated.OnAdd 0 0 0 -1 0
        Annotations: 
          Relational:TypeMapping: Microsoft.EntityFrameworkCore.Storage.IntTypeMapping
    Keys: 
      Id PK
Annotations: 
  ProductVersion: 2.0.0-rtm-26452
  SqlServer:ValueGenerationStrategy: IdentityColumn
```
In other words, exactly the same except that there are two relational annotations missing. It seems wrong to me that this model should _conceptually_ change just because there is a _relational_ mapping to the same table.

Would be interested what @divega and @anpete think on this?

**Comment by AndriySvyryd** [comment] 2017-09-14 00:59
@ajcvickers Identity is a sql server annotation, core model wouldn't change.

**Comment by ajcvickers** [comment] 2017-09-14 01:05
@AndriySvyryd Okay, I see what you are saying. It's unfortunate that the model-level annotation doesn't work for this. Can we try to make that work before putting property-specific annotations on for this case? (i.e. When resolving what SqlServer:ValueGenerationStrategy is being used for a property, take into account that it might be a table splitting scenario and do the right thing?)

**Comment by AndriySvyryd** [comment] 2017-09-14 19:40
Given there's a reasonable workaround and this isn't a regression I don't this this meets the 2.0.1 bar.

**Closed** 2017-09-15 20:07 UTC
Labels: type-bug
